GoogleCloudPlatform/google-cloud-eclipse

- plugins/com.google.gcp.eclipse.appengine.localserver/pom.xml
@akerekes Fixes BUILD when the old version isn't around 
close #17
> make versions match

- eclipse/mars/gcp-eclipse-mars.target
- eclipse/mars/pom.xml
- pom.xml
@akerekes @briandealwis mostly copied from Brian's work on the legacy plugin
> Set up explicit target for Eclipse Mars

- pom.xml
@akerekes @briandealwis @rdayal Maven builds are annoyingly not hermetic so this issue was missed.
> correct eclipse version

- .travis.yml
> turn on travis

- .travis.yml
- plugins/com.google.gcp.eclipse.appengine.localserver.test/.classpath
- plugins/com.google.gcp.eclipse.appengine.localserver.test/.project
- plugins/com.google.gcp.eclipse.appengine.localserver.test/.settings/org.eclipse.core.resources.prefs
- plugins/com.google.gcp.eclipse.appengine.localserver.test/.settings/org.eclipse.jdt.core.prefs
- plugins/com.google.gcp.eclipse.appengine.localserver.test/.settings/org.eclipse.m2e.core.prefs
- plugins/com.google.gcp.eclipse.appengine.localserver.test/META-INF/MANIFEST.MF
- plugins/com.google.gcp.eclipse.appengine.localserver.test/build.properties
- plugins/com.google.gcp.eclipse.appengine.localserver.test/pom.xml
- plugins/com.google.gcp.eclipse.appengine.localserver.test/src/com/google/gcp/eclipse/appengine/localserver/XmlTest.java
- plugins/com.google.gcp.eclipse.appengine.localserver/build.properties
- pom.xml
@briandealwis @akerekes I'm trying to get a simple test to run. However I'm missing something because I get the error message
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: com.google.gcp.appengine.localserver.test 94.0.0.qualifier
[ERROR]   Missing requirement: com.google.gcp.appengine.localserver.test 94.0.0.qualifier requires 'bundle com.google.gcp.appengine.localserver 0.0.0' but it could not be found
[ERROR] 
I suspect this is a one line fix. Anyone see what I'm missing?
> setup test framework

- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/build.properties
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/src/com/google/cloud/tools/eclipse/appengine/whitelist/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/build.properties
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/pom.xml
- pom.xml
> infrastructure for whitelist plugin

- eclipse/mars/pom.xml
- eclipse/neon/pom.xml
- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
- features/com.google.cloud.tools.eclipse.suite.e45.feature/pom.xml
- gcp-repo/category.xml
- gcp-repo/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/gcloud_serverdef.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/pom.xml
- pom.xml
> change version to 0.1.0

- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.properties
- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
- features/com.google.licenses.apache_v2/.project
- features/com.google.licenses.apache_v2/.settings/org.eclipse.core.resources.prefs
- features/com.google.licenses.apache_v2/.settings/org.eclipse.m2e.core.prefs
- features/com.google.licenses.apache_v2/LICENSE-2.0.txt
- features/com.google.licenses.apache_v2/build.properties
- features/com.google.licenses.apache_v2/feature.properties
- features/com.google.licenses.apache_v2/feature.xml
- features/com.google.licenses.apache_v2/pom.xml
- pom.xml
> Add license to feature.xml

- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/src/com/google/cloud/tools/eclipse/appengine/whitelist/AppEngineJreWhitelistTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/src/com/google/cloud/tools/eclipse/appengine/whitelist/AppEngineJreWhitelist.java
> whitelist all non-JRE classes

- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/src/com/google/cloud/tools/eclipse/appengine/whitelist/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/plugin.xml
> define problem marker

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/util/TerminateAction.java
> Fix #75 - Access debug icons via DebugUITools

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/deploy/CloudSdkDeployProjectHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/facet/CloudSdkFacetInstallDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/facet/CloudSdkFacetUninstallDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkServerStartupChecker.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/util/CustomMessageConsole.java
>  Fix a few warnings. 

- pom.xml
> Ensure tests run on main thread on OS X

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
@briandealwis This is to make the wizard easier to find in autocomplete. I found myself typing "Google" and wondering why the wizard didn't show up.
> Add "Google" to wizard name

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardProjectConfigTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardProjectConfig.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/templates/HelloAppEngine.java.ftl
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/templates/appengine-web.xml.ftl
@briandealwis The more I look at this the more I'm convinced we should use FreeMarker. Otherwise we'll just end up reinventing it. However for now this will get us to MVP.
> Generate servlet java code from wizard

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardProjectConfigTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardProjectConfig.java
> remove unused methods

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardProjectConfig.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/templates/index.html.ftl
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/templates/web.xml.ftl
> link to servlet

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/templates/pom.xml.ftl
@briandealwis @patflynn 
fix #131
> Generate a pom.xml

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProjectTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
> add Java facet to project

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
@briandealwis #118
I was expecting this to add servlet-api.jar to the classpath and it didn't. Sending this out for early review while I try to figure that out in case you happen to know how to do that.
> add jst.web 2.5 facet

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
@briandealwis This doesn't actually work. When I call createDataModel it seems to throw a NullPointerException without much of a stack trace. I'm trying to find an example of configuring the jst.web facet
> Don't generate an extra deployment descriptor web.xml

- TESTPLAN.md
> Start work on a test plan

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
> set web content folder to src/main/webapp

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
> set error message when project creation fails

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
Get rid of the big blank space in the wizard.
> set title and description in wizard

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/runtime/CloudSdkRuntimeTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/GCloudCommandDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/runtime/CloudSdkRuntime.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/CloudSdkRuntimeWizardFragment.java
> don't pop up error dialog on every keystroke

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/JavaPackageValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/JavaPackageValidator.java
> more specific error messages on invalid package names

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenCoordinatesValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenCoordinatesValidator.java
Adds validation for Maven GAV coordinates.
> Fix #180 - Add Maven-specific project page

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/gcloud_serverdef.xml
fix #181 @briandealwis @nbashirbello
> set charset to UTF-8

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
@nbashirbello 
start work on #188 
This does not yet actually locate the SDK. That can be done in the next PR, but it does configure it once we find it.
> locate cloud SDK

- eclipse/neon/gcp-eclipse-neon.target
- eclipse/neon/gcp-eclipse-neon.tpd
@elharo PTAL.  Will need to update it in June on release day too.
> Update targets for Neon 4.6 RC3

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProjectTest.java
> remove unused code

- README.md
> Update README.md with details to regenerate the .tpd files

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
> standardize font sizes in dialog per user prefs

- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
Fixes #218 
PTAL @nbashirbello (if you're still awake)
> Add missing bundles to the suite feature

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/templates/pom.xml.ftl
@briandealwis @loosebazooka This is template for generated code from the new project wizard.
> switch sample to use new plugin

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/templates/pom.xml.ftl
> remove vestigial reference to gcloud-maven-plugin

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/LocalAppEngineServerDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviourTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/runtime/AppToolsRuntime.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkLaunchConfigurationDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkServer.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
@nbashirbello @loosebazooka @meltsufin start planning out for #242 to switch over to app-tools-lib-for-java
> Start sketching out the app-tools-lib-for-java based server

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
@briandealwis We do want to get rid of this runtime, but while working on that I found a bug we should fix that will also help us change the runtime going forward.
> Fix finding of GSF runtime in new app engine wizard

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
@nbashirbello this corrects dependencies to unbreak the creation of an appengine project
> require facets bundle

- plugins/com.google.cloud.tools.eclipse.appengine.facets/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.facets/.project
- plugins/com.google.cloud.tools.eclipse.appengine.facets/.settings/org.eclipse.core.resources.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.facets/.settings/org.eclipse.jdt.core.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.facets/.settings/org.eclipse.m2e.core.prefs
- plugins/com.google.cloud.tools.eclipse.preferences/.settings/org.eclipse.core.resources.prefs
@briandealwis check in the eclipse preferences for the new plugin.
> eclipse prefs

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProviderTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProvider.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
@nbashirbello @briandealwis Any idea what I'm doing wrong here? The classes are not found and as best I can tell that's because the runtimeClasspathProvider is never actually consulted. (I.e. debugger won't stop in its constructor)
> use custom runtime

- pom.xml
> app-tools-lib-for-java to appengine-plugins-core

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
> use groupId as default package name if necessary

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkPublishOperation.java
- plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/Activator.java
- plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/CloudToolsPreferencePage.java
- plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/PreferenceInitializer.java
> Add @Override annotations

- .travis.yml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProviderTest.java
> install google cloud sdk on travis

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/CloudSdkRuntimeWizardFragment.java
- plugins/com.google.cloud.tools.eclipse.sdk.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkContextFunctionTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkProviderTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferencePage.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPrompter.java
- plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/CloudSdkProvider.java
- plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkContextFunction.java
To preempt a question, I tried Mockito here. It didn't work. We can figure out how to use Mockito later, but that's not enough reason to hold back this PR now if it does indeed fix the tests (which is still an open question)
> Attempt to fix tests on travis

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
> remove unused imports

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/.project
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/.settings/org.eclipse.core.resources.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/.settings/org.eclipse.jdt.core.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/.settings/org.eclipse.m2e.core.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/build.properties
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/.project
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/.settings/org.eclipse.core.resources.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/.settings/org.eclipse.jdt.core.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/.settings/org.eclipse.m2e.core.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/build.properties
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/pom.xml
- pom.xml
> skeleton for deploy plugin

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkServer.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEnginePublishOperation.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
> set Cloud SDK location when creating a custom runtime in the wizard

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
Had some branch/merge problems with first PR (#286)
> Run app engine dev server in debug mode via the app tools lib (2)

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineOutputLineListenerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineOutputLineListener.java
@briandealwis @elharo @akerekes
> Adds a test for LocalAppEngineOutputLineListener#onOutputLine

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
@akerekes @briandealwis close #307
> fix runtime name

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineFacet.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
> add appengine facet to maven based projects

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/XmlTest.java
@akerekes @nbashirbello close #316
> add XmlTest

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineSdkClasspathContainerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/FacetInstallDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/FacetInstallDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProviderTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProvider.java
From either runtimes or facets. Let maven handle it
@nbashirbello @akerekes 
close #312
> Don't add entries to classpath in maven project

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProvider.java
@akerekes @briandealwis 
close #320
> use preference to find cloud SDK

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineStandardDeployCommandHandlerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineStandardDeployCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/Messages.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/messages.properties
Related to #283 , implements item 2)
> Add no-op context menu item for deploy

- plugins/com.google.cloud.tools.eclipse.appengine.facets/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineSdkClasspathContainer.java
- plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/CloudSdkProvider.java
@briandealwis @akerekes 
close #327
> don't use PathResolver directly

- plugins/com.google.cloud.tools.eclipse.appengine.deploy/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/plugin.xml
Related to #283 , implements item 3)
> Enables deploy command when app engine project is selected

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/runtime/AppToolsRuntime.java
> delete vestigial class

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
> unused imports

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LocalAppEngineConsoleTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/ConsoleUtilities.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/TargetPlatform.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LocalAppEngineConsole.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LocalAppEngineConsolePageParticipant.java
> Opens a console with a stop button for app-tools-lib runtime

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
> fix capitalization of constant

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineFacet.java
> make app-tools-lib-for-java the default runtime

- build/verify-feature-completeness/.project
- build/verify-feature-completeness/.settings/org.eclipse.core.resources.prefs
- build/verify-feature-completeness/.settings/org.eclipse.m2e.core.prefs
> Add verify-feature-completeness project settings

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
> Continue cutting out the custom runtime

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
> remove icons from custom runtime and server

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
> remove the word custom from runtime ID

- pom.xml
> app-tools-lib 0.1.4 non snapshot

- pom.xml
> Restore usagetracker.test

- TESTPLAN.md
- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
> Note feature is for 4.5 and 4.6

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppToolsTabGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/AppToolsTabGroup.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppToolsTabGroup.java
> add an empty tab group for app tools launch configuration

- plugins/com.google.cloud.tools.eclipse.appengine.login/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginService.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginTemporaryTester.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/Messages.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/messages.properties
- Updates the UI message of the login menu and the tooltip of the login toolbar button based on the current login state.
- Now users can log out, with a logout confirmation dialog.
One gripe is that the same messages are duplicated both in `plugin.properties` and `messages.properties` for some localized messages (for the initial menu name and tooltip). It would be nice if `plugin.xml` could pull values directly from `messages.properties`.
> Update UI (login menu and button) based on login state / enable logout

- .travis.yml
> update cloud sdk to 118.0.0

- plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/messages.properties
> correct URL

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppEngineTabGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppEngineTabGroup.java
> AppToolsTabGroup --> AppEngineTabGroup

- plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/AnalyticsOptInArea.java
> unify font sizes

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.ui.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/META-INF/MANIFEST.MF
> better test bundle names

- plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml
> containerInitializer to classpathContainerInitializer

- plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppEngineTabGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppEngineTabGroup.java
> add server launch tab

- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java
Fix spacing and link font to match.
> Fix spacing of the Cloud SDK Location to match the Analytics area.

- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/util/ProjectFromSelectionHelper.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/AdapterUtil.java
Based on the comment from @briandealwis :
https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/pull/485#issuecomment-236762625
> Add AdapterUtil and use the adapter pattern to get the IProject from selection in ProjectFromSelectionHelper

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppEngineTabGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppEngineTabGroup.java
> add environment tab to run configuration

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsEvents.java
Part of #140.
Tracking client-side, opt-in usage on launching the new project wizard and completing the wizard.
> Instrument code to send Analytics hits

- plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/messages.properties
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/messages.properties
@chanseokoh finish up and close #138
> sync opt-in messages

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
@briandealwis @nbashirbello This PR disables (grays out) the profile launch button. I'll file a separate issue to actually support profiling when we have time. 
close #471
> disable the profile launch button

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineSdkClasspathContainer.java
> add stubs to new project classpath

- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineProjectDeployer.java
> spelling correction to test two-factor auth

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineSdkClasspathContainer.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
Updating the plugin.xml to fix some merge errors in earlier PR: Removed the profile mode; publish task extension point was pointing to the wrong class (a class that was renamed)
close #559
> Fix the dev app server; fix for #559

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/plugin.xml
@briandealwis also fix broken test that pointed at wrong plugin.xml
close #561
> Limit Google pref page to showing up on GCP projects

- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
Disables Analytics altogether if in the dev mode or the Analytics tracking ID is not defined.
> Disable Analytics in dev mode

- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.properties
> Fix feature description

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
> only LocalAppEngineConsole should be a console page participant

- plugins/com.google.cloud.tools.eclipse.appengine.login/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/ui/LoginServiceUi.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsEvents.java
Fixes #537.
Did actual testing; working fine.
> Send Analytics login events

- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/ui/LoginServiceUi.java
> Wait uninterruptibly to ignore spurious wake-ups 

- pom.xml
> upgrade appengine-plugins-core to 0.1.6

- plugins/com.google.cloud.tools.eclipse.integration.appengine/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/AbstractProjectTests.java
- pom.xml
> Fix hangs in ITs on OS X

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java
> upgrade app engine sdk to latest

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployPreferencesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesModel.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPropertyPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/DeployPreferenceInitializer.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployPreferences.java
> Enable 'Restore Defaults' button for deploy preferences page

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewNativeAppEngineStandardProjectTest.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/templates/appengine/AppEngineTemplateUtilityTest.java
- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/appengineWebXml.txt
- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/appengineWebXmlWithProjectId.txt
- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/appengineWebXmlWithoutProjectId.txt
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/appengine-web.xml.ftl
@akerekes I'm not sure if we should take it out from the wizard or not. Are we going to use the wizard to set the project default preference?
> don't set project ID from new project wizard

- build.sh
> add initial build script

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProjectTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
> fill in project ID from wizard

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
#618 fixes caused the launch to be terminated when the server is stopped.
This fix handles the opposite case to ensure the server is stopped when the launch is terminated.
I also pulled the listeners into a single class to simplify listener cleanup.
Fixes #597
> Cause server listen and react to to launch termination

- eclipse/ide-target-platform/category.xml
- features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml
- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk/META-INF/MANIFEST.MF
- pom.xml
> upgrade appengine-plugins-core to 0.1.7

- .travis.yml
> upgrade cloud sdk on travis

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
> don't load DTD in tests

- kokoro/ubuntu/release.cfg
- kokoro/ubuntu/release.sh
> release scripts for kokoro

- .travis.yml
@nbashirbello @briandealwis @akerekes Travis seems to be timing out when it tries to upgrade 124 to 125
> gcloud to 125.0.0

- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/SdkUiMessages.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/messages.properties
> notice when App Engine Java components aren't installed

- kokoro/ubuntu/release.cfg
@chanseokoh see if kokoro is in fact always reading from master
> remove extra fields

- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewMavenBasedAppEngineProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewNativeAppEngineStandardProjectTest.java
- plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotProjectActions.java
@briandealwis fix #700 
This one bit me a couple of days ago, when my missing app engine java components caused my local tests to fail and I couldn't easily figure out why.
> better error messages on failure

- pom.xml
> 0.1.9 version of plugins core

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
- plugins/com.google.cloud.tools.eclipse.ui.util/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/ProjectFromSelectionHelper.java
> Updated GAE standard facet for deploy and localserver run.

- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginService.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/Messages.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/messages.properties
> Remove loginInProgress sync mechanism

- .travis.yml
Parallelizes the build along JDK7 + Eclipse 4.5 and JDK8 + Eclipse 4.6.
> Use travis matrix to speed builds

- .travis.yml
> gcloud 127.0.0

- .travis.yml
> Update gcloud to 128.0.0

- kokoro/ubuntu/release.cfg
> change repo name

- pom.xml
> Upgrade appengine-plugins-core to 0.1.10

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/MavenAppEngineFacetUtilTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/MavenAppEngineFacetUtil.java
fix #747 @nbashirbello @akerekes
> set jstl scope to provided

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProjectTest.java
> slightly better error messages on failure

- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginService.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/Messages.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/ui/LoginServiceUi.java
fix #695 @nbashirbello @chanseokoh
> Yes/No --> Sign Out/Don't Sign Out

- kokoro/ubuntu/release.cfg
- kokoro/ubuntu/release.sh
- kokoro/ubuntu/sign.sh
> Sign the jars

- plugins/com.google.cloud.tools.eclipse.ui.util.test/src/com/google/cloud/tools/eclipse/ui/util/databinding/ProjectIdInputValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/databinding/ProjectIdInputValidator.java
While I was trying to tackle part of #759, I noticed this is dead code.
> Remove dead code

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardArchetypeWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java
> don't use artifact in Java package

- .travis.yml
> update Cloud SDK to 129.0.0

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardArchetypeWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/Messages.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/messages.properties
> Externalize some more UI strings in the maven wizard

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/AppEngineLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryFileTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/xsd/com.google.cloud.tools.eclipse.appengine.libraries.xsd
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Library.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainer.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/config/LibraryFactory.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
Libraries added to the project are now correctly getting exported in the WAR file; also changing export attributes to optional and default to true
> API Attacher - Fixes WAR dependencies

- pom.xml
> upgrade appengine-plugins-core to 0.1.12

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewMavenBasedAppEngineProjectWizardTest.java
> Ensure MavenArchetypeProjectWizard uses configured output location

- README.md
> https://github.com/GoogleCloudPlatform/google-cloud-eclipse.git

- README.md
> JDK 1.7_79

- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/messages.properties
> Mention App Engine Java Components required 

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.login.test/src/com/google/cloud/tools/eclipse/appengine/login/ui/AccountSelectorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/ui/AccountSelector.java
Alternative fix #831
(Or if you prefer to refactor, we can close this.)
> Use databinding converter and update strategy to avoid validation issues on deploy dialog

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardProjectConfigTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardProjectConfig.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProject.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewNativeAppEngineStandardProjectTest.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/templates/appengine/AppEngineTemplateUtilityTest.java
- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/appengineWebXml.txt
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/appengine-web.xml.ftl
> don't require application element and project ID until deploy

- .travis.yml
> Cloud SDK 131.0

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java
Fixes #872. Setting the text after changing to the bold font fixes the problem.
> Fix clipped "Advanced" label in deploy dialog

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- pom.xml
> Configure dev_appserver to avoid restarting modules on detected change

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineComponentPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/Messages.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/messages.properties
> Adds an App Engine component check in the Create New 'Maven' App Engine project wizard

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk/META-INF/MANIFEST.MF
> move every plugin to appengine-plugins-core 0.1.13

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
Subsequent PR will add dependencies.
Part of the fix for #803
> Attach the APIs library panel to the maven wizard.

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
Reveals staging location of modules which can be helpful for add-ons
like GWT that wish to introduce resource changes during execution.
Fixes #904
> Implement WTP IModulePublishHelper

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizard.java
> Add the selected App Engine library dependencies to the maven project

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java
Fixes the Objectify attach bug. (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/803#issuecomment-256994524)
Closes #803.
> Fix Objectify+Guava attach bug in Maven project

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
Alternative fix outlined in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/896#pullrequestreview-6093155
Fixes #889
> Alternative fix for #889

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppEngineTabGroup.java
> Schedule a job to update launch configuration tab

- plugins/com.google.cloud.tools.eclipse.test.util/.classpath
- plugins/com.google.cloud.tools.eclipse.test.util/.project
- plugins/com.google.cloud.tools.eclipse.test.util/.settings/org.eclipse.core.resources.prefs
- plugins/com.google.cloud.tools.eclipse.test.util/.settings/org.eclipse.jdt.core.prefs
- plugins/com.google.cloud.tools.eclipse.test.util/.settings/org.eclipse.m2e.core.prefs
- plugins/com.google.cloud.tools.eclipse.test.util/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.test.util/build.properties
- plugins/com.google.cloud.tools.eclipse.test.util/plugin.properties
- plugins/com.google.cloud.tools.eclipse.test.util/pom.xml
- pom.xml
> create empty test util bundle

- .travis.yml
> Update to cloud SDK 133.0.0

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
> Remove redundant canStop() check

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
> Remove code dup and clean up code in new project wizard

- .travis.yml
@nbashirbello @briandealwis also appengine sdk 1.4.6
> gcloud 134.0

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployConsolePageParticipant.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesDialog.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployCommandHandler.java
> mostly line length

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/Messages.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/messages.properties
@briandealwis @nbashirbello fix #900 
FYI, I verified that the appengine-java components are auto-installed in this case if they're missing.
> warn user if cloud sdk is not available when running local server

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java
> pop open console when deploying

- kokoro/ubuntu/sign.sh
> don't need category.xml; have to make artifacts.jar later in process

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml
> remove reference to no longer defined flex facet

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui.test/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineJavaComponentMissingPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui.test/src/com/google/cloud/tools/eclipse/appengine/ui/CloudSdkMissingPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/CloudSdkMissingPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/MissingComponentPage.java
@briandealwis also refactors out duplicate code
> Handle user answering No to CloudSDKPrompter in Maven Wizard

- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/TestProjectCreator.java
> Wait for any jobs to complete before deleting test projects

- kokoro/ubuntu/sign.sh
@briandealwis as you suggested
> content.jar will be generated after signing

- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineLibrariesSelectorGroup.java
> reformatting for line length

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryClasspathContainerSerializerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryClasspathContainerSerializer.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/templates/appengine/AppEngineTemplateUtilityTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/templates/appengine/AppEngineTemplateUtility.java
> stop using FileWriter and FileReader

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
> better configure work for progress monitors

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/WebProjectUtil.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/EclipseContextHolder.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/ModuleUtilsTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/appengine-web.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/appengine-web_module.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/appengine-web_noservice.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEnginePublishOperation.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/ModuleUtils.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/AppEngineDescriptor.java
@briandealwis error in ModuleUtils found by static analysis looks like a potentially serious bug
> fix bad use of static builder method

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
@briandealwis noticed a couple more places we were using the old icons
> app engine icons

- features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml
> Remove hamcrest from .3rdparty.feature

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java
> Handle when a module is possibly added to a server with the module

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.properties
> improve description of App Engine runtime

- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/CloudSdkPreferenceAreaTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/SdkUiMessages.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/messages.properties
> better error message for cloud SDK not found in configured directory

- plugins/com.google.cloud.tools.eclipse.appengine.ui.test/src/com/google/cloud/tools/eclipse/appengine/ui/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/messages.properties
> fix properties file

- README.md
@patflynn End user documentation and installation instructions can be found in the Github Wiki.
> End user documentation is in the Github Wiki.

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardRuntimeChangeListener.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java
- Removes the public variable `AppEngineStandardFacet.APPENGINE_STANDARD_VERSION` that is not being used (except in testing).
- Misc. clean-ups
> Remove test-only variable

- .travis.yml
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkContextFunctionTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/MockSdkGenerator.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk/META-INF/MANIFEST.MF
- pom.xml
> upgrade to appengine-plugins-core 0.2.1

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesDialog.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/messages.properties
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/SdkUiMessages.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/messages.properties
> Cloud SDK version check in the plugin

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/MavenUtils.java
@chanseokoh also fix some line length issues
> update default versions of maven dependencies

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LocalAppEngineServerWizardFragmentTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/Messages.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LocalAppEngineServerWizardFragment.java
> work around WTP issues when runtime config wizard doesn't have any pages

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenCoordinatesValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/messages.properties
@akerekes @chanseokoh  fix #1054
> fix some messages

- README.md
> Select your new target platform in the `Target Platform` preferences.

- README.md
> apply to OK

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/JavaPackageValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/Messages.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/messages.properties
> externalize strings

- plugins/com.google.cloud.tools.eclipse.welcome.test/src/com/google/cloud/tools/eclipse/welcome/test/ContentXmlTest.java
- plugins/com.google.cloud.tools.eclipse.welcome/intro/cloud-tools-for-eclipse.xml
- plugins/com.google.cloud.tools.eclipse.welcome/intro/css/intro.css
Part of #1009.
Also adds a new test to check if the content XML file is well-formed. (Should have done that before.)
> Link Migration and Tutorial docs in Welcome intro

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetUninstallDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/ui/AccountsPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProjectTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineLibrariesSelectorGroup.java
- plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkContextFunctionTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
> fix assorted Eclipse warnings

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LocalAppEngineServerWizardFragment.java
- plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/messages.properties
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java
> add missing preposition

- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryClasspathContainerSerializerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.login.test/src/com/google/cloud/tools/eclipse/appengine/login/ui/LoginServiceUiTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
> Make sure to use StandardCharsets.UTF_8

- features/com.google.cloud.tools.eclipse.suite.e45.feature/build.properties
- features/com.google.cloud.tools.eclipse.suite.e45.feature/p2.inf
> Cannot install CT4E if GPE is already installed and vice versa

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/PluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
fix #1011 @nbashirbello @briandealwis
> Remove references to flex facet

- .gitignore
> more eclipse metadata to ignore

- README.md
@briandealwis as discussed yesterday in email
> Updating Dependencies

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/PluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.login.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.login.test/src/com/google/cloud/tools/eclipse/appengine/login/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.ui.test/src/com/google/cloud/tools/eclipse/appengine/ui/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist.test/src/com/google/cloud/tools/eclipse/appengine/whitelist/XmlTest.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/BasePluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/PluginXmlDocument.java
- plugins/com.google.cloud.tools.eclipse.welcome.test/src/com/google/cloud/tools/eclipse/welcome/test/PluginXmlTest.java
fix #178 @chanseokoh @briandealwis
> Use BasePluginXmlTest

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/messages.properties
> adjust messages to align with UI guidelines

- plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/areas/AreaBasedPreferencePage.java
- plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/areas/PreferenceArea.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/SdkUiMessages.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/messages.properties
@briandealwis fixes another part of #367
> show error message as soon as preferences are opened, if necessary

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
> Move message to tool tip

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/messages.properties
> show enter a project name on new wizard

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
> Move Java Package label to left of text input field

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
Close #1126.
This PR does try to align the input fields.
> Move Java package label to the left of input text in Maven project wizard

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProjectTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
@briandealwis begin work on #1127 
still need to do maven wizard
> open most important file in editor on wizard completion

- plugins/com.google.cloud.tools.eclipse.welcome/build.properties
Fixes #1152. I think this might be it. @briandealwis?
> Export plugin.xml in .welcome bundle

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java
@chanseokoh some minor tech debt while I dig into this bug
> adjust progress monitors and line length

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/ProjectFromSelectionHelper.java
The name's misleading, and it bit me.
> Change util method name: getProject() --> getAppEngineStandardProject()

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProjectTest.java
#1086 is closed, hence removing the debug logging code. I had added these for #1086.
> Remove now-unnecessary debug logging code

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/Messages.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
@chanseokoh fix how leading/trailing spaces are embedded
> fix bad line breaks

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
> check for a different failure message

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.integration.appengine/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk/META-INF/MANIFEST.MF
- pom.xml
> Bump appengine-plugins-core to 0.2.5

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/FacetedProjectHelperTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFlexFacet.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DeployPropertyPageTest.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewMavenBasedAppEngineProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewNativeAppEngineStandardProjectTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/FacetedProjectHelper.java
`FacetedProjectHelper.projectHasFacet()` is better suited for `static`.
> Make projectHasFacet a static method

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/Library.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactory.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui.test/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineLibrariesSelectorGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineLibrariesSelectorGroup.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/messages.properties
> add tooltips on the library selectors

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/build.properties
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/helpContexts.xml
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPropertyPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/helpContexts.xml
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/helpContexts.xml
- plugins/com.google.cloud.tools.eclipse.welcome/build.properties
> help for deployment preference page

- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
> don't rule out 4.7

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
Address quoting issue from #1139
> Use DebugPlugin.parseArguments()

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelperTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelper.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/messages.properties
Update `LaunchHelper` to:
- handle finding a project for elements that can be adapted to an `IResource` but not `IProject`
- add tests for the above
- remove obsolete message
Fixes #1204
> Handle launches with selection = JDT IJavaElement

- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardProjectStaging.java
> don't check for updates during stage to work avoid incorrect fix message

- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/BasePluginXmlTest.java
> test at least one extension point exists

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java
> Don't set Java App Engine SDK path in App Engine runtime

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPropertyPage.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/CloudSdkPreferenceAreaTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java
> clear status on empty string

- .travis.yml
- pom.xml
> Measure code coverage

- .travis.yml
@chanseokoh Let's see what happens with the new gcloud on Travis. Perhaps our code is confused by the .0.1.
> gcloud 139.0.1

- README.md
> From the `Run` menu select `Run History > gcloud-eclipse-tools`

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java
@briandealwis by unnesting composites
fix #676
> Align fields in deploy dialog

- plugins/com.google.cloud.tools.eclipse.welcome/intro/cloud-tools-for-eclipse.xml
> point to new docs on cloud.google.com instead of github

- plugins/com.google.cloud.tools.eclipse.welcome/intro/cloud-tools-for-eclipse.xml
> tighten up language

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/messages.properties
@briandealwis @hray2003 I'm not 100% sure this one's worth it, since I haven't figured out how to line up with the widgets we inherit from WizardNewProjectCreationPage, but it maybe looks a little better:
> align two fields in new project wizard

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/messages.properties
> remove warning about unable to check for latest version

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MessagesTest.java
> added testIllegalPackageName Test

- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/build.properties
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.whitelist/plugin.xml
- plugins/com.google.cloud.tools.eclipse.preferences.test/src/com/google/cloud/tools/eclipse/preferences/PluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.preferences/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.preferences/build.properties
- plugins/com.google.cloud.tools.eclipse.preferences/plugin.properties
- plugins/com.google.cloud.tools.eclipse.preferences/plugin.xml
- plugins/com.google.cloud.tools.eclipse.test.util/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/BasePluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/EclipseProperties.java
- plugins/com.google.cloud.tools.eclipse.util/META-INF/MANIFEST.MF
fix #1161 We've forgotten to add files to bin.includes shockingly often.
> test what we bundle in our binaries

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui.test/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineLibrariesSelectorGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineLibrariesSelectorGroup.java
> Fix button enablement bug when selecting libraries

- release/release_after_kokoro.sh
This one got slipped while resolving the merge conflict.
> Missed one: eclipse.appengine.login --> .login

- eclipse/ide-target-platform/category.xml
- features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml
> Fix gson and guava OSGi versions

- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/MockHttpServletResponse.java.ftl
> Slight clarification of Javadoc in the sample

- .travis.yml
> Use maven wrapper to use Maven 3.3.9

- release/release_after_kokoro.sh
Fixes #1102. The Wiki instructions have been updated too.
I tested and verified that the file gets uploaded to a final release bucket.
> Upload $SIGNED_DIR/index.html into final bucket

- plugins/com.google.cloud.tools.eclipse.appengine.compat.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.compat.test/src/com/google/cloud/tools/eclipse/appengine/compat/GpeMigratorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.compat/src/com/google/cloud/tools/eclipse/appengine/compat/GpeMigrator.java
Fixes #1295.
I closed #1296 and reopened this, because I gave a wrong git branch name to it.
I also added a test.
> Don't log error if WTP metadata file doesn't exist when converting to App Engine project

- release/release_after_kokoro.sh
Fixes #1305 #1306 #1307 #1308 #1309
> Fix GCS bucket path extraction / don't ask to go

- release/release_after_kokoro.sh
> Create and use temp work directory in release script

- .travis.yml
> Add more useful comment for requiring maven-3.3.9

- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/CloudSdkPreferenceAreaTest.java
Introduced with the Win10 test changes in #1300.
> Avoid potential NPE in CloudSdkPreferenceAreaTest

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
Purpose wasn't clear. 
#904 #905
> Document purpose for implementing IModulePublishHelper

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallationTest.java
From the test errors, it looks like there are multiple things deleting the project?  I wonder if we can `jstack` ourselves at runtime.
#1196
> Add diagnostics for StandardFacetInstallationTest flakiness

- plugins/com.google.cloud.tools.eclipse.welcome/intro/cloud-tools-for-eclipse.xml
The doc is live now. However, the new link doesn't say anything about GWT.
> Point Migration link to google doc

- eclipse/oxygen/gcp-eclipse-oxygen.target
- eclipse/oxygen/gcp-eclipse-oxygen.tpd
- pom.xml
- change from `/releases/oxygen` to dated sub-repo
- update Orbit to stable release for M5
> Update for Oxygen M5.

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/BuildPath.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java
@akerekes We're going to need to add libraries to the build after new project creation as well.
> make methods static in prep for moving to common utility class

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebBlacklistTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/ApplicationQuickFixTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/BlacklistSaxParserTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/BlacklistScannerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/MarkerResolutionGeneratorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.validation/build.properties
- plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ApplicationMarkerResolutionGenerator.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ApplicationQuickFix.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/BlacklistScanner.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/xslt/application.xsl
- plugins/com.google.cloud.tools.eclipse.appengine.validation/xslt/application.xsl
> provide quick fix for project id warning

- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/Xslt.java
> fix up argument names

- plugins/com.google.cloud.tools.eclipse.projectselector.test/src/com/google/cloud/tools/eclipse/projectselector/ProjectSelectorTest.java
- plugins/com.google.cloud.tools.eclipse.projectselector/META-INF/MANIFEST.MF
remove duplicate Bundle-ClassPath, remove unused import
> Minor project selector code cleanup

- plugins/com.google.cloud.tools.eclipse.projectselector.test/pom.xml
> Include org.eclipse.rcp feature for com.google.cloud.tools.eclipse.projectselector.test

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployPreferencesConverterTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployPreferencesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanelTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesDialog.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployPreferences.java
- plugins/com.google.cloud.tools.eclipse.projectselector.test/src/com/google/cloud/tools/eclipse/projectselector/ProjectRepositoryTest.java
- plugins/com.google.cloud.tools.eclipse.projectselector.test/src/com/google/cloud/tools/eclipse/projectselector/ProjectSelectorTest.java
- plugins/com.google.cloud.tools.eclipse.projectselector/src/com/google/cloud/tools/eclipse/projectselector/ProjectRepository.java
- plugins/com.google.cloud.tools.eclipse.projectselector/src/com/google/cloud/tools/eclipse/projectselector/ProjectSelector.java
fix #1401 @akerekes @chanseokoh
> handle accounts without access to GCP

- .travis.yml
> nexus.codehaus.org --> oss.sonatype.org

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidator.java
> add marker location

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebBlacklistTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/BlacklistSaxParserTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/BlacklistScannerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/messages.properties
> fix quick fix description

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/AppEngineLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/AppEngineLibrariesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/PluginXmlValidationTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryClasspathContainerSerializerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/xsd/com.google.cloud.tools.eclipse.appengine.libraries.xsd
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/OSGI-INF/com.google.cloud.tools.eclipse.appengine.libraries.repository.LibraryClasspathContainerResolverService.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/AppEngineLibraries.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/ILibraryClasspathContainerResolverService.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainer.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/Library.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactory.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFile.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/ArtifactBaseLocationProvider.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryClasspathContainerSerializer.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryContainerStateLocationProvider.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/SerializableClasspathEntry.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/SerializableLibraryClasspathContainer.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/ILibraryRepositoryService.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineLibrariesSelectorGroup.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/BasePluginXmlTest.java
> Load library definitions from plugin.xml

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidator.java
> Better Name for Blacklist Marker

- plugins/com.google.cloud.tools.eclipse.projectselector/src/com/google/cloud/tools/eclipse/projectselector/messages.properties
- plugins/com.google.cloud.tools.eclipse.ui.util.test/src/com/google/cloud/tools/eclipse/ui/util/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/messages.properties
> Migrate localized messages

- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
> add libraries UI to feature.xml

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java
- plugins/com.google.cloud.tools.eclipse.appengine.flex.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.flex.test/.project
- plugins/com.google.cloud.tools.eclipse.appengine.flex.test/.settings/org.eclipse.core.resources.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.flex.test/.settings/org.eclipse.jdt.core.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.flex.test/.settings/org.eclipse.m2e.core.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.flex.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.flex.test/build.properties
- plugins/com.google.cloud.tools.eclipse.appengine.flex.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.flex.test/src/com/google/cloud/tools/eclipse/appengine/flex/AppEngineFlexFacetTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.flex/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.flex/.project
- plugins/com.google.cloud.tools.eclipse.appengine.flex/.settings/org.eclipse.core.resources.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.flex/.settings/org.eclipse.jdt.core.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.flex/.settings/org.eclipse.m2e.core.prefs
- plugins/com.google.cloud.tools.eclipse.appengine.flex/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.flex/build.properties
- plugins/com.google.cloud.tools.eclipse.appengine.flex/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.flex/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.flex/pom.xml
The flex facet is in a new bundle "com.google.cloud.tools.eclipse.appengine.flex", that will not be included in the build along with the appropriate test bundle "com.google.cloud.tools.eclipse.appengine.flex.test".  This way flex feature would not be visible to customers
> Created the flex facet 

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XsltQuickFixTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/XsltSourceQuickFix.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/messages.properties
> Appengine-web.xml display string

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java
> update default app engine Java SDK

- .travis.yml
> cloud SDK 145.0.0

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/PomXmlScannerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/PomXmlScanner.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/messages.properties
fix #1498 
Should this be a warning or an error? 
> Gcloud warning

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/BannedElementTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/BannedElement.java
> Override equals() and hashCode() in BannedElement

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/AppEngineLibrariesPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/AppEngineLibrariesPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/M2RepositoryService.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/MavenHelper.java
> some tests for  AppEngineLibrariesPage

- README.md
> BUILD status badge

- plugins/com.google.cloud.tools.eclipse.appengine.flex.test/.project
- pom.xml
@nbashirbello This should assist with importing projects, as well as turn on travis tests for flex.
> add flex modules to pom.xml

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AbstractXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidatorTest.java
Using `IMarker.PROBLEM`.
Other changes are auto-fixes from my IDE.
> Use IMarker.PROBLEM for "org.eclipse.core.resources.problemmarker"

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/AppEngineLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
fix #1545 
This syncs the standard project libraries with the maven archetype libraries.
@akerekes @chanseokoh
> add JSTL to JSP library and servlet group

- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
> Wait for more validation jobs in waitForProjects()

- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
About the second issue in #1166.
> Wait for build errors when importing zip project

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardWizardPage.java
Standard shows the library selector group and flex does not.
> Added option to show the Library selector group in the Create New App Engine wizard.

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPathTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/AppEngineLibrariesPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPath.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/ILibraryClasspathContainerResolverService.java
> don't double add classpath entries

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java
> Defer WTP DepdendencyGraph update job

- build/jacoco/.project
@chanseokoh @briandealwis  fix #1509
> add jacoco .project

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> JSTL javadoc URL

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
> Fix NPE in LocalAppEngineServerLaunchConfigurationDelegate

- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/internal/properties/DataflowVersionTester.java
> remove unneeded suppression

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializerTest.java
> line length

- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/.classpath
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/.project
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/.settings/org.eclipse.core.resources.prefs
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/.settings/org.eclipse.jdt.core.prefs
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/.settings/org.eclipse.m2e.core.prefs
- plugins/com.google.cloud.tools.eclipse.dataflow.core/.classpath
- plugins/com.google.cloud.tools.eclipse.dataflow.core/.project
- plugins/com.google.cloud.tools.eclipse.dataflow.core/.settings/org.eclipse.core.resources.prefs
- plugins/com.google.cloud.tools.eclipse.dataflow.core/.settings/org.eclipse.jdt.core.prefs
- plugins/com.google.cloud.tools.eclipse.dataflow.core/.settings/org.eclipse.m2e.core.prefs
@tgroh We've been checking our .settings et al files into Github.
> dataflow eclipse metadata

- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/CloudSdkPreferenceAreaTest.java
> minor formatting

- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/project/GcsDataflowProjectClientTest.java
@tgroh a few random cleanups I banged out between conference sessions
> fix a few more warnings

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializerTest.java
@akerekes @chanseokoh fix #1605
> Deflake LibraryClasspathContainerInitializerTest

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/FlexDeployPreferencesPanelTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/FlexDeployPreferencesPanel.java
> add back line that was deleted accidentally

- pom.xml
@briandealwis fix #1641 
This may not absolutely guarantee the integration tests run last, but it does have that effect on my system.
> move integration tests to end of list

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/PomTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Pom.java
> keep history of rewritten pom.xml

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XsltQuickFixTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/Xslt.java
@chanseokoh @abbiefarr 
also adds test that transformed files are synced.
> keep history of transformed files

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/WebProjectUtil.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/io/ResourceUtils.java
> Don't create folder that already exists

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java
Minor nit: `LocalAppEngineServerDelegate` was passing the wrong class type into `StatusUtil`.
> Fix mistaken StatusUtil class reference

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> Support GCS Client Libraries

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> More dependencies needed for GCS

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> add oauth servlet to clientapis dependencies

- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
- features/com.google.cloud.tools.eclipse.suite.e45.feature/pom.xml
- gcp-repo/metadata.p2.inf
- gcp-repo/metadata.product
> version 1.0.2

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProject.java
@chanseokoh fix #1717 fix #1682
> don't create two app.yaml's

- plugins/com.google.cloud.tools.eclipse.appengine.flex/plugin.xml
> open app.yaml inside Eclipse

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/JavaContext.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/MavenContext.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ServletMappingElement.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/messages.properties
Fix #1582 
Validates that the `<servlet-mapping>` name matches a name defined in a `<servlet>` in web.xml.
> Validate servlet-mapping

- README.md
> We currently maintain three target platforms, targeting the latest version of the current, previous, and next releases

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/RunConfigConflictTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
- pom.xml
@chanseokoh appengine-plugins-core 0.2.11
This PR goes one version higher than @briandealwis's and makes some changes to account for the API changes in 0.2.11.
It does not add SnakeYAML to the target platform.
> switch to devappserver1

- plugins/com.google.cloud.tools.eclipse.ui.util.test/src/com/google/cloud/tools/eclipse/ui/util/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/WorkbenchUtil.java
- plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/messages.properties
> add missing invalid URL message

- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java
> little b boolean preferred

- plugins/com.google.cloud.tools.eclipse.appengine.flex/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/plugin.xml
- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/GoogleLandingPageTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/build.properties
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/plugin.xml
> combine GCP categories

- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java
> share code

- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/page/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/Messages.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardDefaultRunOptionsPage.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardLandingPage.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/messages.properties
> Add messages class

- plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.xml
> Add autocomplete to appengine-web.xml

- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/PluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/PluginXmlTest.java
@tgroh checks for well-formedness, that all extensions are defined, and a few other common problems
> add plugin test

- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java
> unused import

- pom.xml
For #1685. I need https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/373.
> Upgrade to appengine-plugins-core 0.3.1

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/WarPublisherTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/WarPublisher.java
> Add method to create WAR file for flex deploy

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/RunConfigConflictTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
@chanseokoh fix #1772
On reflection, we have no idea whether these conflicting ports will still be an issue when/if devappserver2 returns; or if it is, whether the current code will still work. So I just went ahead and deleted it. Anything more would require us to predict the future.
> Don't error on conflicting admin ports/storage paths

- plugins/com.google.cloud.tools.eclipse.appengine.facets/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/ui/AppEngineStandardProjectConvertCommandHandler.java
> Ensure valid Cloud SDK configured before App Engine project conversion

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProjectTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProject.java
> Add Dynamic Web Module facet 3.1 instead of 3.0 to new flex projects

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/plugin.properties
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/plugin.xml
> wizard description

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/plugin.properties
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/plugin.xml
> Google Cloud Dataflow Java Project

- plugins/com.google.cloud.tools.eclipse.googleapis.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.googleapis.test/src/com/google/cloud/tools/eclipse/googleapis/internal/GoogleApiFactoryTest.java
- plugins/com.google.cloud.tools.eclipse.googleapis/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.googleapis/src/com/google/cloud/tools/eclipse/googleapis/IGoogleApiFactory.java
- plugins/com.google.cloud.tools.eclipse.googleapis/src/com/google/cloud/tools/eclipse/googleapis/internal/GoogleApiFactory.java
- plugins/com.google.cloud.tools.eclipse.googleapis/src/com/google/cloud/tools/eclipse/googleapis/internal/GoogleApiUrl.java
@tgroh @chanseokoh Needed for #1745
> Add methods to retrieve a storage API client

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlValidatorTest.java
See #1801 
I couldn't find an obvious reason why this test was flaky, but I didn't think it would hurt to have less static test data.
> Flaky test

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
> unused field

- plugins/com.google.cloud.tools.eclipse.appengine.ui.test/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineLibrariesSelectorGroupTest.java
> fix indents

- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTabTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
> handle no project selected

- eclipse/mars/gcp-eclipse-mars.target
- eclipse/mars/gcp-eclipse-mars.tpd
- eclipse/neon/gcp-eclipse-neon.target
- eclipse/neon/gcp-eclipse-neon.tpd
- eclipse/oxygen/gcp-eclipse-oxygen.target
- eclipse/oxygen/gcp-eclipse-oxygen.tpd
Necessary for a few more WTP source bundles.
> Add WTP enterprise_sdk feature

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/ProjectSelectorSelectionChangedListenerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/CommonDeployPreferencesPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
- plugins/com.google.cloud.tools.eclipse.projectselector/src/com/google/cloud/tools/eclipse/projectselector/ProjectSelector.java
Fixes #1780.
- Deploy dialog:
- Preference page (resizable):
> Wrap UI texts in deploy dialog

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesDialogTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesDialog.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesDialog.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
- plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/event/OpenUriSelectionListener.java
Fixes #499. The message was taken from IntelliJ (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/499#issuecomment-291177014).
> Warn that flex deployments cost money

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/MavenCoordinates.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/areas/AreaBasedPreferencePage.java
- plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/MockSdkGenerator.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPrompter.java
- plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/databinding/ProjectVersionValidator.java
- third_party/com.google.cloud.tools.eclipse.jst.server.core/src/com/google/cloud/tools/eclipse/jst/server/core/BasePublishOperation.java
> more warnings fixes

- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardLandingPageTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardLandingPage.java
> mark some methods static

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelper.java
> Fix NPE from stale server definitions during launch

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java
> don't enable create button when no bucket is specified

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/helpContexts.xml
@chanseokoh fix #1795
Note that I can't hard wrap the entities because the line breaks would be preserved in the displayed HTML. Thus the lines are really long.
> Fix up flexible wizard help

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> new version

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk/META-INF/MANIFEST.MF
- pom.xml
> core 0.3.2

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineDeployOutputTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/DataflowPipelineLaunchDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/options/TypeHierarchyPipelineOptionsHierarchyTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/project/MajorVersionTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/LaunchableResourceTest.java
> remove expected exception per google style

- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/project/GcsDataflowProjectClientTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/GcsDataflowProjectClient.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/VerifyStagingLocationJob.java
> return false

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/AppEngineDeployPreferencesPanelTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesDialogTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesPanelTest.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/ui/CompositeUtil.java
Moved common code to traverse a `Composite` for finding a certain control to the test util bundle.
> Refactor test code

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java
> StandardFacetInstallDelegate must refresh generated appengine-web.xml

- kokoro/windows/continuous.bat
> Use "gcloud" and "mvn" provided in Kokoro Windows env / suppress "mvn" garbage log messages

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/flex/FlexStagingDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/DeployPropertyPageForFlexProjectTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/pom.xml
Forgot cleaning up this: adding a flex facet takes care of creating `src/main/appengine/app.yaml`.
> Clean up code

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/ModuleUtilsTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/appengine-web_malformed.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/ModuleUtils.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/src/com/google/cloud/tools/eclipse/appengine/standard/java8/ConversionTests.java
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/src/com/google/cloud/tools/eclipse/appengine/standard/java8/JavaFacetChangeTests.java
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/src/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineWebBuilder.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk/META-INF/MANIFEST.MF
- pom.xml
> Upgrade to appengine-plugins-core 0.3.3

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardStagingDelegateTest.java
The only cause for #1848 I can think of is that the appcfg staging fails. This will make it clear if that's the case when it fails again.
> Log appcfg staging output in tests

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
> flag off the devappserver2 arguments

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
@briandealwis @chanseokoh fix #1922
> use project JDK to run localserver

- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/xslt/addJava8Runtime.xsl
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/xslt/removeJava8Runtime.xsl
> line break after XML declaration

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/helpContexts.xml
> indent libraries to add to build path

- plugins/com.google.cloud.tools.eclipse.appengine.compat.test/src/com/google/cloud/tools/eclipse/appengine/compat/GpeMigratorXsltTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/PomTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryClasspathContainerSerializer.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/ContextXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/ContextXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProject.java
- plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/CredentialHelperTest.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/EclipseProperties.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/PluginXmlDocument.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/templates/appengine/AppEngineTemplateUtilityTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/io/FileDownloader.java
- plugins/com.google.cloud.tools.eclipse.welcome.test/src/com/google/cloud/tools/eclipse/welcome/ContentXmlTest.java
> use Files.new instead of new File...Stream

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/AppYamlValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/RelativeFileFieldSetter.java
> fix javadoc warnings

- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/src/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineWebBuilderTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/src/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineWebBuilder.java
> don't move to servlet 3.1 automatically

- plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/LabelImageLoadJobTest.java
- plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/LabelImageLoaderTest.java
- plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/LabelImageLoaderWithServerTest.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/AccountsPanel.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/LabelImageLoadJob.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/LabelImageLoader.java
Fixes #1942.
We don't have to resize profile pictures ourselves. This will save network bandwidth too. I've also verified we can ask for any size.
> Request server to resize image

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardLandingPage.java
> remove advanced section

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/messages.properties
> add wizard title

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProjectTest.java
> Wait for WTP validation job when deleting project

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/EclipseProperties.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/PluginXmlDocument.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/templates/appengine/AppEngineTemplateUtility.java
There have been missing places for #1898.
> "Files.new{Input|Output}Stream" instead of "new File{Input|Output}Stream"

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProjectTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardArchetypeWizardPage.java
> Pin down archetype versions for Maven project wizard

- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardDefaultRunOptionsPageTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardDefaultRunOptionsPage.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/wizard/NewDataflowProjectWizard.java
> store staging location

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacetTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/FacetUtilTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/FacetUtil.java
Fixes #2028.
This takes care of both standard and flex.
> Add WTP library container when installing App Engine standard

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/SourceAttacherJobTest.java
> don't use Expected

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> add App Engine Admin API library

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineWtpProjectTest.java
> Restore waitForProjects() to fix flaky test

- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/ThreadDumpingWatchdog.java
> Reset Thread interrupted state before tests

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> revert app engine admin API

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/FlexFacetInstallDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/TemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/Templates.java
> templates aren't just for App Engine

- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowDependencyManager.java
> update comment since Maven no longer uses LATEST

- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/MavenUtilsTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/MavenUtils.java
> unused code

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectWizard.java
> Clear interrupted flag in AppEngineWizardPage#addPages()

- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTabTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/DefaultedPipelineOptionsComponent.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
Fixes #2136. @tgroh I think this is the right behavior.
> Select and save runner selection

- .github/ISSUE_TEMPLATE.md
- plugins/com.google.cloud.tools.eclipse.bugreport.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.bugreport.test/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandlerTest.java
- plugins/com.google.cloud.tools.eclipse.bugreport/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.bugreport/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandler.java
> Request Google Cloud SDK version in issues

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/messages.properties
Reword labels as per feedback in #2139.
> Update Java runtime labels

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactoryTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactory.java
> Test for LibraryFactory

- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/src/com/google/cloud/tools/eclipse/appengine/standard/java8/GpeConversionTest.java
> Cause GpeConversionTest to wait for validators before deletion

- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowArtifactRetriever.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowDependencyManager.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowMavenCoordinates.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowMavenModel.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowProjectCreator.java
@tgroh uses 2.0.0 instead of 2.0.0-beta1
> use 2.0.0 release

- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/TestProjectCreator.java
Towards identifying cause of #2093
> Dump current threads on project-deletion failure

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XsltSourceQuickFixTest.java
- Spin the SWT event loop to process any events
- Use Hamcrest containsString() to show current contents
🤞 #2076
> Fix XsltSourceQuickFixTest.testApply()

- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowArtifactRetriever.java
Fixes #2181
This test feels a bit… icky.
> Fix Dataflow SDK artifactId

- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/util/SelectFirstMatchingPrefixListenerTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/util/SelectFirstMatchingPrefixListener.java
Fixes #2118.
It was surprisingly difficult to fix it, due to the bizarre event dispatch workings that defer delivering events. The proposed solution is to just short-circuit if the modification is meaningless in the sense that it did not change a previous value.
> Short-circuit if setting same text

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java
> Check widget disposal before updating UI

- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
@tgroh @briandealwis I'd like to soft launch this (no fanfare) early next week.
> turn on dataflow

- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
- features/com.google.cloud.tools.eclipse.suite.e45.feature/pom.xml
- gcp-repo/metadata.product
I just did quick tests with the most basic and important features (creating new projects, local run, deploy, dataflow stuff). The critical paths work fine at least.
> Bump version to 1.3.0

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/AppEngineDeployPreferencesPanelTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/AppEngineDeployPreferencesPanel.java
Fixes #2023. The `authUser` part will continue to be appended as usual.
> Change project creation URL

- plugins/com.google.cloud.tools.eclipse.appengine.deploy/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/util/CloudSdkProcessWrapper.java
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/.settings/org.eclipse.core.resources.prefs
> fix spelling

- plugins/com.google.cloud.tools.eclipse.appengine.ui.test/src/com/google/cloud/tools/eclipse/appengine/ui/PluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/plugin.xml
> add new dataflow wizard to toolbar button

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java
> Disable create button after successful bucket creation

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/plugin.xml
@briandealwis @tgroh fix #2242
> smaller dataflow command icon

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java
Configure server defaults to publish changes immediately.
Fixes #2210
> Set devappserver to auto-publish changes immediately

- codecov.yml
> only fail on 10% or higher drop in coverage

- codecov.yml
@chanseokoh currenlty 68.5% by default
> reduce patch target to 50%

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/helpContexts.xml
> update new project wizard help

- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/status/StatusUtilTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/MavenUtils.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/status/StatusUtil.java
@chanseokoh I'm futzing with some of the codecov results. This looked like an easy win, and uncovered one minor inconsistency in our formatting.
> remove unused methods and fill gaps in test coverage

- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/wizard/NewDataflowProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/messages.properties
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardDefaultRunOptionsPage.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/wizard/NewDataflowProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/MavenUtilsTest.java
> test for NewDataflowProjectWizard

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/messages.properties
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowProjectCreator.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/JavaPackageValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/JavaPackageValidator.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/Messages.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/messages.properties
> More accurate package name validation

- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/index.txt
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/index.html.ftl
> upgrade sample HTML to XHTML 5

- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/web25.txt
- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/web31.txt
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/web.xml.ftl
> include JSP as index file

- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/status/StatusUtilTest.java
> fill a couple of easy coverage gaps

- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/helloAppEngineWithPackage.txt
- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/helloAppEngineWithoutPackage.txt
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/HelloAppEngine.java.ftl
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/HelloAppEngineTest.java.ftl
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/MockHttpServletResponse.java.ftl
> default to UTF-8

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/Library.java
> update app engine library version

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardJre7ProjectFacetDetector.java
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/src/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineStandardJre8ProjectFacetDetector.java
> remove some log messages

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/ClientApisLibrariesSelectorGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/LibrarySelectorGroup.java
all libraries can be added to non App Engine Java projects
> refactor to clarify behavior and intent

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> Add Cloud Translate APIs

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/PomTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/MavenCoordinatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/MavenCoordinatesHelperTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/ClientApisLibrariesSelectorGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/Library.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactory.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFile.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/MavenCoordinates.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/M2RepositoryService.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/MavenCoordinatesHelper.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProject.java
> make maven coordinates immutable with a builder

- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineProjectDeployer.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/util/CloudSdkProcessWrapper.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/ConvertJobSuspender.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StringVersionComparator.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/MavenCoordinates.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/CloudSdkDebugTargetPresentation.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenCoordinatesUi.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/MajorVersionPipelineRunnerConfigurationTest.java
- plugins/com.google.cloud.tools.eclipse.projectselector/src/com/google/cloud/tools/eclipse/projectselector/ProjectSelector.java
> fix some Javadoc warnings

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> upgrade to endpoints v2

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/TemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/helloAppEngineJava8.txt
- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/web31.txt
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/HelloAppEngine.java.ftl
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/web.xml.ftl
> use annotations for Servlet 3.1

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactoryTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibraries.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactory.java
> make stateless method static

- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/AccountSelector.java
> @exception --> @throws

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactory.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowDependencyManager.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowProjectCreator.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ArtifactRetrieverIntegrationTest.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/ArtifactRetrieverTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/ArtifactRetriever.java
@briandealwis since we want to cache shared artifacts
> share a single retriever for Maven Central

- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/DependencyResolverTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/DependencyResolver.java
> Return artifacts instead of strings

- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/src/com/google/cloud/tools/eclipse/appengine/standard/java8/m2e/AppEngineStandardProjectDetector.java
> excess logging removed

- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/ArtifactRetrieverTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/ArtifactRetriever.java
> cache artifact retrievers

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFileTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFile.java
@chanseokoh This restores the behavior of the previous release.
> export library files by default

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> v1-rev108-1.22.0

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
@chanseokoh fix #2369 by removing translate for the time being
> remove translate library

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> more datastore classes

- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewMavenBasedAppEngineProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewNativeAppEngineStandardProjectTest.java
> Use different project names to avoid flakiness

- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponentTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java
> Deflake tests by explicitly calling RunOptionsDefaultsComponent#validate()

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/plugin.xml
> Reformat plugin.xml

- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/src/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineStandardJava8PresetTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/messages.properties
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java
> remove beta label from Java 8

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPath.java
> make method non-public

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProvider.java
@briandealwis I don't think there's anything else left to do here, but if there is, let's file a new issue.
> we closed this bug

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectConfig.java
> reduce visibility

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> New appengine-api-1.0-sdk 1.9.56

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java
@briandealwis breaking off some smaller fixes since the AI container work is getting large
> use actual monitor

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardWizardPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardWizardPage.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProjectTest.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewNativeAppEngineStandardProjectTest.java
Fixes #2385. The wizard does show Java 8 selected when opened.
> Make Java 8 default in App Engine std wizard

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/AppEngineDeployPreferencesPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/AppYamlValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/DeployArtifactValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/RelativeFileFieldSetter.java
Somehow I lost all the code changes in #2411, so I restored them here.
> Refactor a few deploy-related classes

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> new SDK release 1.9.57

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.bugreport.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.bugreport/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.integration.appengine/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk/META-INF/MANIFEST.MF
- pom.xml
> appengine-plugins-core 0.3.7

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviourTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
> I2466 dev appserver1 admin port

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPathTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPath.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java
> add some progress monitors

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibraries.java
> catch ClassCastException

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/LibrarySelectorGroup.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibraries.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/Library.java
> don't show GRPC libraries for App Engine Standard Java 7 projects

- gcloud-eclipse-tools.launch
> Change launcher to clear config area and use the SDK IDE project

- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowProjectCreator.java
> surface error on project creation to user

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/PomTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactoryTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPath.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Pom.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibraries.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/Library.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactory.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java
> only load direct dependencies into pom.xml

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPath.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryClasspathContainerSerializer.java
fix #2490 @briandealwis @chanseokoh
> preserve previously added libraries

- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ArtifactRetrieverIntegrationTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/ArtifactRetriever.java
> allow final qualifier

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/PomTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPath.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializer.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Pom.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/Library.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java
@chanseokoh fix #2499 #2493 
Fixing the Maven issue unexpectedly led into an unrecognized bug where transitive dependency versions were incorrectly updated. We should have been only updating versions of direct dependencies. 
This also has the side effect of working around, if not exactly fixing, #2502
> Update versions of Maven dependencies too. 

- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/DependencyResolver.java
> Propagate dependency resolution exceptions

- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/ArtifactRetrieverTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/ArtifactRetriever.java
> fix cache issue involving equal URLs

- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ArtifactRetrieverIntegrationTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/ArtifactRetriever.java
This method gets the latest version irrespective of qualifiers.
> True getLatestVersion method

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/plugin.xml
> Rename Google API Libraries -> Google Cloud Client Libraries for Java

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> endpoints 2.0.9

- .github/ISSUE_TEMPLATE.md
- plugins/com.google.cloud.tools.eclipse.bugreport.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.bugreport.test/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandlerTest.java
- plugins/com.google.cloud.tools.eclipse.bugreport/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.bugreport/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandler.java
> Add Eclipse version in bug report template

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFileTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Pom.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactory.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFile.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ArtifactRetrieverIntegrationTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/ArtifactRetriever.java
> most recent nonrelease version if necessary

- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ChildModuleWarPublishTest.java
It was deleting only the main project to be tested.
> Delete all projects when test is done

- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
- features/com.google.cloud.tools.eclipse.suite.e45.feature/pom.xml
- gcp-repo/metadata.product
> Bump version to 1.4.1

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFlexJarFacetTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFlexWarFacetTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/FlexFacetInstallDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFlexWarFacet.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineWtpProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProject.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/CreateAppEngineStandardWtpProject.java
Refactoring, plus several tests as a bonus.
> Refactoring and code cleanups

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsEvents.java
We were always sending "standard" deploy events even when deploying to flex.
> Fix analytics for App Engine deploy

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java
(Was included in #2553 but was intended to be standalone)
Fixes #2454
> Report library resolution errors with a relevant message

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/DataflowPipelineLaunchDelegate.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/wizard/NewDataflowProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/LoginServiceUi.java
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerWithServerTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsEvents.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
Fixes #548.
I'll do actual testing in the meantime.
> Allow passing multiple metadata key-value pairs

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesPanel.java
> Fix text field height

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.standard.ftl
> Upgrade appengine-api-sdk to 1.9.59

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesDialog.java
- plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/LabelImageLoadJobTest.java
- plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/LabelImageLoaderTest.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/LabelImageLoadJob.java
- plugins/com.google.cloud.tools.eclipse.ui.test/src/com/google/cloud/tools/eclipse/ui/util/images/SharedImagesTest.java
@briandealwis could you look into this?
> Fix Image creation issues

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/AppEngineApplicationQueryJobTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/ProjectSelectorSelectionChangedListenerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/AppEngineApplicationQueryJob.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
@briandealwis 
should make the error message a bit more specific.
Inspired by but not yet a complete fix for #2582 
I still plan to see if I can handle that case a little more clearly.
> Include project ID in error message

- plugins/com.google.cloud.tools.eclipse.appengine.compat/src/com/google/cloud/tools/eclipse/appengine/compat/cte13/CloudToolsEclipseProjectNotifier.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/convert/AppEngineStandardProjectConvertJob.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowProjectCreator.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/status/StatusUtilTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/status/StatusUtil.java
> Turn OK MultiStatus -> Status.OK_STATUS

- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponentTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java
- plugins/com.google.cloud.tools.eclipse.projectselector/src/com/google/cloud/tools/eclipse/projectselector/MiniSelector.java
> Deflake RunOptionsDefaultsComponent tests by explicitly joining jobs

- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java
- plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTreeUtilities.java
> Fix flaky integration test

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/GcpLocalRunTab.java
> shorter service key field

- plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/LabelImageLoadJobTest.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/LabelImageLoadJob.java
> Save Display early in user profile picture load job

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/wizard/NewDataflowProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/ui/CompositeUtil.java
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/OptInDialogTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/OptInDialog.java
Fixes #2622.
Misc: removed Javadocs that do not make sense as public description for the methods.
> Fix opt-in dialog closing bug

- plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/GoogleLoginServiceTest.java
- plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/AccountSelectorTest.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/GoogleLoginService.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/IGoogleLoginService.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/AccountSelector.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/AccountsPanel.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/GoogleLoginCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/LoginServiceUi.java
There has been no place of a customized login message, and I feel like this feature will never be used.
> Remove customer login dialog message feature

- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/OptInDialogTest.java
Fixes #2639.
We will see if this will fix the issue on Kokoro.
> Close dialog in a robust way on Windows

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/messages.properties
> Use correct library name "Cloud Client Libraries for Java"

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
- plugins/com.google.cloud.tools.eclipse.projectselector.test/src/com/google/cloud/tools/eclipse/projectselector/ProjectRepositoryTest.java
- plugins/com.google.cloud.tools.eclipse.projectselector/src/com/google/cloud/tools/eclipse/projectselector/ProjectRepository.java
> Cloud Resource Manager's Projects API can return null

- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java
> Attempt to open import wizard at least twice

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/GcpProjectQueryJobTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/GcpLocalRunTabTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/BannedElementTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/PipelineLaunchConfigurationTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/OptInDialogTest.java
> fix warning by democking

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallationTest.java
> begin consolidating createFolders method

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/Activator.java
> remove unused method

- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponentTest.java
Fixes one cause of https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2378#issuecomment-351155572, https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2378#issuecomment-351186875, and https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2378#issuecomment-351182009.
> De-flake RunOptionsDefaultsComponentTest

- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
> Change ProjectUtils#importProjects to show errors from all projects

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallationTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryTest.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/BasePluginXmlTest.java
Some trivial tweaks to remove unnecessary imports and throws.
> Fix up some unnecessary imports and throws

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> Update initial endpoints version

- .travis.yml
> Set correct Cloud SDK PATH / upgrade Cloud SDK version

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.flex.ftl
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.standard.ftl
> always pick latest Maven plugin version

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
> make test more robust

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactory.java
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/plugin.xml
> pin the Java 8 servlet libraries too

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelper.java
> IServer#getServerType() can return null

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPathTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryClasspathContainerSerializerTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Activator.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPath.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryClasspathContainerSerializer.java
> Remove _libraries.container file when Google Cloud Libraries container is removed

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ServiceAccountUtilTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/MajorVersionPipelineRunnerConfigurationTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/DataflowPipelineLaunchDelegate.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/PipelineLaunchConfiguration.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTabTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/DataflowPipelineLaunchConfigurationTabGroup.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineOptionsSelectionDialog.java
I had a branch hanging around for too long.
> Minor fixes

- features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
- features/com.google.cloud.tools.eclipse.suite.e45.feature/pom.xml
- gcp-repo/metadata.product
> 1.5.1 release

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> new objectify version

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/messages.properties
> shrink width of group title and add space between groups

- eclipse/oxygen/gcp-eclipse-oxygen.target
- eclipse/oxygen/gcp-eclipse-oxygen.tpd
Currently Oxygen builds are failing.
Let's see if this will work.
> Use versioned WTP oxygen repo

- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/CloudSdkPreferenceAreaTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java
> Set correct validation result when switching SDK management option

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
> Make test more robust against version changes

- plugins/com.google.cloud.tools.eclipse.sdk.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk.ui/plugin.xml
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/InstallManagedCloudSdkStartup.java
> Trigger installation of Google Cloud SDK on startup

- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/CloudSdkPreferenceAreaTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceAreaTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/MessagesTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/messages.properties
fix #2809 @briandealwis @patflynn
> Choose SDK

- plugins/com.google.cloud.tools.eclipse.ui.status/build.properties
> fix one more warning

- .gitignore
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/AccountSelectorObservableValue.java
> fix warning

- README.md
> no more mars

- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProjectTest.java
- plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTestingUtilities.java
> Wait for App Engine console view to populate

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/AppEngineDeployPreferencesPanelTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/GcpProjectQueryJobTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesDialogTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/AppEngineApplicationQueryJobTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/AppEngineDeployPreferencesPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/GcpProjectQueryJob.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/AppEngineApplicationQueryJob.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/ProjectSelectorSelectionChangedListener.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/ConvertJobSuspenderTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/ConvertJobSuspender.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Pom.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviourTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/GcpLocalRunTabTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTabTest.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/AccountSelector.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/AccountSelectorObservableValue.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/LoginServiceUi.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/MenuContributionInitializer.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/ui/CompositeUtil.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/jobs/PluggableJobTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/jobs/PluggableJob.java
Some more Java 8 adoptions.
Let me see if tests will pass. I have some problem locally inside Eclipse. Not sure why.
> Migrate to Java 8 lambdas

- README.md
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Activator.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardLandingPage.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java
- plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTreeUtilities.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
- plugins/com.google.cloud.tools.eclipse.ui.status/src/com/google/cloud/tools/eclipse/ui/status/PollingStatusServiceImpl.java
> missing default

- README.md
> explorer not editor

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/FacetUtil.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/WebProjectUtil.java
> fix javadoc warning

- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceAreaTest.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/MockSdkGenerator.java
> Fixes test dependency on local environment state

- .travis.yml
> build/install-cloudsdk.sh 190.0.1

- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceAreaTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/messages.properties
Button is only enabled when in automatic mode.
> Add update button to Cloud SDK prefpage

- plugins/com.google.cloud.tools.eclipse.ui.status/src/com/google/cloud/tools/eclipse/ui/status/Messages.java
- plugins/com.google.cloud.tools.eclipse.ui.status/src/com/google/cloud/tools/eclipse/ui/status/PollingStatusServiceImpl.java
- plugins/com.google.cloud.tools.eclipse.ui.status/src/com/google/cloud/tools/eclipse/ui/status/messages.properties
Previously the job would appear in the progress view by default.
> Make GCP status polling job a system job and externalize

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.bugreport.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.bugreport/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.integration.appengine/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/MessageConsoleWriterListenerTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkInstallJobTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkUpdateJobTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/ProgressWrapperTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/MessageConsoleWriterListener.java
- plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkInstallJob.java
- plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/ProgressWrapper.java
- pom.xml
Towards #2853: 0.4.4 must wait it is on Maven Central.
> Update to appengine-plugins-core 0.4.4

- plugins/com.google.cloud.tools.eclipse.ui.status/src/com/google/cloud/tools/eclipse/ui/status/PollingStatusServiceImpl.java
> close json reader

- eclipse/neon/gcp-eclipse-neon.target
- eclipse/neon/gcp-eclipse-neon.tpd
- eclipse/oxygen/gcp-eclipse-oxygen.target
- eclipse/oxygen/gcp-eclipse-oxygen.tpd
- features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml
- gcp-repo/metadata.p2.inf
> Restore Docker Editor for 1.6.0

- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceAreaTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/MockSdkGenerator.java
@chanseokoh @briandealwis fix #2897
> default locations

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
> update library versions

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEnginePublishOperationTest.java
About #1798.
For the failure of `assertNotNull(serverModule)`, I'm taking a loop to wait until it becomes non-null. Some related components may not have been initialized yet (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1798#issuecomment-361392184).
For the failure of `assertTrue(new File(webInf, "classes/sox/server/GreetingServiceImpl.class").isFile())`, I'm not actually doing anything to remedy it, but putting the debug code below to see if my theory (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1798#issuecomment-371563891) is correct.
> Wait until modules are available

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFacetPresetsTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/messages.properties
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java
> Mark Java 7 runtime as deprecated

- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidator.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/GoogleLoginService.java
> Prefer workbench window for login failure dialog

- plugins/com.google.cloud.tools.eclipse.appengine.compat/src/com/google/cloud/tools/eclipse/appengine/compat/cte13/CloudToolsEclipseProjectNotifier.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployConsole.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesDialog.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPropertyPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/GcpLocalRunTab.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LocalAppEngineServerWizardFragment.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProjectTest.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewDataflowProjectWizardLandingPageTest.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java
- plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotProjectActions.java
- plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTestingUtilities.java
- plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotWorkbenchActions.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
- plugins/com.google.cloud.tools.eclipse.ui.test/src/com/google/cloud/tools/eclipse/ui/util/DisplayExecutorTest.java
- plugins/com.google.cloud.tools.eclipse.ui/src/com/google/cloud/tools/eclipse/ui/util/OpenDropDownMenuHandler.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/jobs/FuturisticJob.java
Mostly direct replacements, except a few.
> Clean up code: removing Runnable

- plugins/com.google.cloud.tools.eclipse.bugreport/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.bugreport/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerWithServerTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/CloudToolsInfo.java
> Add platform info in Analytics pings

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidator.java
> Do not add Dynamic Web Module facet

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/RunAppEngineShortcutTest.java
> Refactor code

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEnginePublishOperationTest.java
Hopefully this is the last PR for #1798.
> Wait until classes are built: LocalAppEnginePublishOperationTest

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsEvents.java
> Track Maven vs. native project creation for App Engine Standard and Flex

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/BannedElementTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/ToServlet25SourceQuickFixTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidatorPluginJspTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidatorPluginTest.java
> Avoid Dynamic Web project

- plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/LoginServiceUiTest.java
- plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/LoginServiceUi.java
> Wire login success/failure landing pages

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/BomTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/testdata/testpom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Bom.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.flex.ftl
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.standard.ftl
@briandealwis @chanseokoh fix BOM artifact ID until I figure out how to read dependencyManagement element with Aether
> google-cloud --> google-cloud-bom

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPathTest.java
@chanseokoh tracking down some flakiness for #2980
> better failure message

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/AppEngineLibrariesSelectorGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviourTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProvider.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.standard.ftl
@chanseokoh fix #2972 at least as much of it as we can fix in CT4E
> appengine-api-sdk not provided

- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ChildModuleWarPublishTest.java
> don't fail test in tearDown

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployCommandHandlerTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/natures/DataflowJavaProjectNatureTest.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceAreaTest.java
@briandealwis like before, this is faster, as it doesn't have to wait until the exception.
> Fast menu item check

- plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/ProgressWrapperTest.java
- plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkUpdateJob.java
- plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/ProgressWrapper.java
> submonitor

- kokoro/windows/continuous.bat
Kokoro syncs every file back to the agent, so it takes a lot of time to exit. Deleting files before exiting will give us substantial speed-up.
Also, #2284 and #2872 have been fixed by #2999, so we no longer need to pre-download JARs for test projects.
> Speed up Kokoro build

- plugins/com.google.cloud.tools.eclipse.bugreport.test/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandlerTest.java
- plugins/com.google.cloud.tools.eclipse.bugreport/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.bugreport/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandler.java
> Reveal Cloud SDK management option in bug report

- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/DataflowPipelineLaunchDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/DataflowPipelineLaunchDelegate.java
> Do not modify original env map

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Pom.java
> use namespace

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidator.java
fix #2390 I think all other uses of these methods are for non-namespaced files like plugin.xml
> more namespacing

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviourTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidator.java
`BiFunction<InetAddress, Integer, Boolean>`
to
`BiPredicate<InetAddress, Integer>`
> Substitute BiPredicate with BiFunction

- plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/ManagedCloudSdkStartup.java
Fixes #3062.
Another minor change is to factor out `ManagedSdkVersionMismatchException`, like in `CloudSdkInstallJob` and `CloudSdkUpdateJob`. It's thrown only when not giving "LATEST"; it's when the given Managed SDK version is different from what is actually read from the `VERSION` file.
> Update error log message

- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProjectTest.java
> Print diagnositc messages

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactoryTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/AppEngineLibrariesSelectorGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibraries.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/Library.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineWizardPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexWizardPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardWizardPage.java
fix #3073 @briandealwis @chanseokoh
> Objectify 6.0

- features/com.google.cloud.tools.eclipse.suite.feature/feature.xml
- features/com.google.cloud.tools.eclipse.suite.feature/pom.xml
- gcp-repo/metadata.product
> prepare 1.7.0 release

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/PomTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/FlexibleLibrariesSelectorGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Pom.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFile.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
fix #3111  @chanseokoh @briandealwis
> stick to Objectify 5 on standard

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/DatastoreIndexUpdateDataTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/DatastoreIndexUpdateData.java
fix #3118 @chanseokoh @briandealwis
> don't merge empty files

- eclipse/ide-target-platform/category.xml
- eclipse/neon/.project
- eclipse/neon/gcp-eclipse-neon.target
- eclipse/oxygen/gcp-eclipse-oxygen.target
- eclipse/photon/gcp-eclipse-photon.target
Fixes #3125
Just did right-clicking on the `.tpd` files and selecting "Create Target Definition File". It did update the hamcrest versions, so I feel like this will fix the problem.
> Update target platform definitions

- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
@briandealwis per https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/3117#issuecomment-393013475
Nothing significant.
> Push down project retrieval logic

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/GcpProjectQueryJob.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
> new version of App Engine SDK for Java 1.9.64

- plugins/com.google.cloud.tools.eclipse.sdk/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkInstallJob.java
- plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkUpdateJob.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsEvents.java
Fixes #3143.
It has not been feasible to add tests for sending actual pings at call sites. We just need to look really carefully to send correct event strings and metadata.
> Send Cloud SDK modify events

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProvider.java
> Avoid NPE in ServletClasspathProvider

- pom.xml
> Revert to Tycho 1.1.0

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/CloudSdkStagingHelperTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.sdk.ui/META-INF/MANIFEST.MF
> fix maven BOM template version

- plugins/com.google.cloud.tools.eclipse.welcome/intro/cloud-tools-for-eclipse.xml
> Expand description for welcome page

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/DependencyResolverTest.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/DependencyResolver.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/NonOptionalDependencyFilter.java
> don't include optional dependencies

- pom.xml
> update jackson core

- .travis.yml
- eclipse/.gitignore
- eclipse/eclipse-2018-09/gcp-eclipse-2018-09.target
- eclipse/eclipse-2018-09/gcp-eclipse-2018-09.tpd
- eclipse/eclipse-2018-09/pom.xml
- eclipse/pom.xml
- pom.xml
~~Builds on fixes for #3233 / #3234.~~
Rebased onto head now that #3234 was merged.
Fixes #3228
> Build against Eclipse 2018-09 M2

- README.md
> fix indent for list

- README.md
> explicit is now photon

- eclipse/common-dependencies.tpd
- eclipse/eclipse-2018-09/gcp-eclipse-2018-09.target
- eclipse/eclipse-2018-09/gcp-eclipse-2018-09.tpd
- eclipse/oxygen/gcp-eclipse-oxygen.target
- eclipse/photon/gcp-eclipse-photon.target
> Bump SWTBot to 2.7.0 (official) and 2018-09 M3

- README.md
> Fix commands to build target platform

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlSourceValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebMarkerResolutionGenerator.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ElementProblem.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/MissingRuntime.java
> warn on missing runtime

- README.md
Markdown requires 3-space indentation to work properly.
> Fix doc formatting

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.ftl
> Remove unused pom.xml property

- plugins/com.google.cloud.tools.eclipse.aeri.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.compat.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.ui.test/.classpath
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/.classpath
- plugins/com.google.cloud.tools.eclipse.bugreport.test/.classpath
- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/.classpath
- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/.classpath
- plugins/com.google.cloud.tools.eclipse.googleapis.test/.classpath
- plugins/com.google.cloud.tools.eclipse.login.test/.classpath
- plugins/com.google.cloud.tools.eclipse.preferences.test/.classpath
- plugins/com.google.cloud.tools.eclipse.projectselector.test/.classpath
- plugins/com.google.cloud.tools.eclipse.sdk.test/.classpath
- plugins/com.google.cloud.tools.eclipse.sdk.ui.test/.classpath
- plugins/com.google.cloud.tools.eclipse.ui.status.test/.classpath
- plugins/com.google.cloud.tools.eclipse.ui.test/.classpath
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/.classpath
- plugins/com.google.cloud.tools.eclipse.util.test/.classpath
- plugins/com.google.cloud.tools.eclipse.welcome.test/.classpath
> Add "test=true" attribute to test bundle "src/"

- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProvider.java
> Harden ServletClasspathProvider for deleted project

- plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.properties
- plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.xml
> no separate runtime category

- gcloud-eclipse-tools.launch
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlSourceValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebBlacklist.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ObsoleteRuntime.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/XmlSourceValidator.java
fix #3340 
fix #3335 
@chanseokoh
> put marker on root element

- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/XsltQuickFix.java
> don't depend on subclass

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/UpgradeRuntimeQuickFixTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/xslt/upgradeRuntime.xsl
> preserve whitespace

- pom.xml
> Remove MaxPermSize since we require Java 8 JVM

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/DocumentLocationTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/ElementProblemTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/DocumentLocation.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ElementProblem.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ValidationUtils.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/XmlSourceValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/XmlValidator.java
@chanseokoh fix #3363 
also added a toString method to DocumentLocation and made some refactorings that were useful while debugging this
> extend quick fixes across start and end-tags

- eclipse/.gitignore
- features/com.google.licenses.apache_v2/feature.properties
- gcp-repo/metadata.p2.inf
- plugins/com.google.cloud.tools.eclipse.ui.test/src/com/google/cloud/tools/eclipse/ui/AboutIniTest.java
- plugins/com.google.cloud.tools.eclipse.ui/about.properties
> Update year in copyright

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebProblemsTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/PomXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/ValidationUtilsTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidatorPluginTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlSourceValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineDeprecatedElement.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebProblems.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/JavaServletElement.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/MavenPluginElement.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ObsoleteRuntime.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/PomXmlValidator.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidator.java
> replace many uses of no longer accurate word blacklist

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/ApplicationSourceQuickFixTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidatorPluginJspTest.java
> remove two more uses of term blacklist

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/CloudSdkStagingHelperTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/messages.properties
- plugins/com.google.cloud.tools.eclipse.welcome.test/src/com/google/cloud/tools/eclipse/welcome/ContentXmlTest.java
`git grep LibraryUnavailable` gives nothing.
> Minor fixes / cleanups

- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XsltQuickFixPluginTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XsltQuickFixTest.java
> separate plugin and non-plugin tests

- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.ftl
> remove versions plugin from new projects

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/CloudSdkStagingHelperTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardStagingDelegateTest.java
> Fixes test failures due to Java 7 staging

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviourTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegateTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
dev appsever 2 had a separate admin port, so that can go away too.
> Clean up dev appserver2 code

- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
> simplify AnalyticsPingManager API

- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
> sendPingHelper to sendPing since we're not sending a ping helper

- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/http/TestHttpServer.java
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerPluginTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerWithServerPluginTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/HttpUtilWithServerTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/HttpUtil.java
- plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/CloudToolsInfo.java
@chanseokoh @briandealwis @etanshaul
> set up analytics via Clearcut/Concord

- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
Also log non-200 responses
@briandealwis
> Flag clearcut through environment variable

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/AppEngineLibrariesSelectorGroupTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibraries.java
> pick Objectify 6 on App Engine Standard

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
> set up web listener for Objectify 6

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
> update default versions

- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerPluginTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
For some reason that we can't really understand, Clearcut expects that non-primitive fields be wrapped into a singleton array. At least I checked this works.
Also fixed the metadata format. It should be a list of maps, where each map has two keys "key" and "value".
> Fix JSON structure for Clearcut

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPropertyPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/AppEngineDeployPreferencesPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPropertyPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/ScrolledPageContent.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/GcpLocalRunTab.java
> Info Message for deploy #1417

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/TemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/objectifyWebListenerWithPackage.txt
- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/objectifyWebListenerWithoutPackage.txt
- plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/web25ObjectifyFilter.txt
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/ObjectifyWebListener.java.ftl
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/web.xml.ftl
> Generate web listener in servlet 2.5 projects

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/Library.java
- plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/DependencyResolverTest.java
> update javadoc URLs for objectify

- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerPluginTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerTest.java
- plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
> Set client_machine_id instead of zwieback_cookie for Clearcut

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
Migrated from #3437 #3439 #3440.
Signed-off-by: Lakshminarayana Nekkanti <narayana.nekkanti@gmail.com>
> No icon for "Pipeline Argument Tab"

- plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTabTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
> Pipeline Options area is not scrollable #3460

- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/MockHttpServletResponse.java.ftl
> deprecate mock methods to avoid warnings

- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/MockHttpServletResponse.java.ftl
> one annotation per line

- plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowProjectCreatorTest.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowProjectCreator.java
> default to Java 1.8

- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowProjectArchetype.java
- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/MajorVersion.java
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/helpContexts.xml
@tgroh @briandealwis fixes #3466
> remove dataflow version 1.9 from wizard

- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowProjectCreator.java
1.9 is deprecated and will be turned off soon
fixes #3471 
@chanseokoh @tgroh
> default to major version 2

- plugins/com.google.cloud.tools.eclipse.dataflow.core/plugin.properties
- plugins/com.google.cloud.tools.eclipse.dataflow.core/plugin.xml
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/plugin.properties
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/plugin.xml
> Use plugin.properties to localize dataflow plugin.xml

- plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/CredentialHelperTest.java
Mostly interested in seeing if our tests are flaky right now.
> Specify character set

- README.md
> Install App Engine Java components

- features/com.google.cloud.tools.eclipse.suite.feature/feature.xml
- features/com.google.cloud.tools.eclipse.suite.feature/pom.xml
- gcp-repo/metadata.product
> Release 1.8.2

- README.md
> Don't import verify_feature_completeness

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java
@chanseokoh minor nit I noticed while reviewing warnings in a fresh import
> Eclipse thinks xxx is a todo

- plugins/com.google.cloud.tools.eclipse.appengine.newproject/plugin.properties
- plugins/com.google.cloud.tools.eclipse.dataflow.ui/plugin.properties
starts on #3497
Consistent with other new project wizards
> Imperative mood

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/Bug3380Test.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/testdata/testBug3380.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Bom.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Pom.java
> BOM in non-BOM Maven projects

- gcloud-eclipse-tools.launch
> remove MAX_PERM_SIZE

- plugins/com.google.cloud.tools.eclipse.dataflow.ui/plugin.xml
**JEE perspective**
**Java Perspective**
**Web Perspective**
> Dataflow project not shown in New Menu

- .travis.yml
- eclipse/eclipse-2018-12/gcp-eclipse-2018-12.target
- eclipse/eclipse-2018-12/gcp-eclipse-2018-12.tpd
@briandealwis Make CLABot happy
> Fix Travis build

- README.md
> export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

- .travis.yml
- pom.xml
@briandealwis This is the version that will be used by the next release of appengine-plugins-common
> update apache commons compression

- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineRuntime.java
- plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/messages.properties
> Add Java 11 Jetty runtime constant

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectConfigTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectConfig.java
> add entry point for Java 11

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesSelectionPage.java
@briandealwis @chanseokoh This refactoring pulls out a superclass that is pure UI for potential use in the new application wizard when a project does not yet exist. 
towards #3535
> extract superclass

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesSelectionPage.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineWizardPage.java
> two page new project wizard

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectConfigTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/CreateAppEngineStandardWtpProjectTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectConfig.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineWtpProject.java
> rename appenginelibraries --> libraries

- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/ui/navigator/model/AppEngineProjectElementTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPathTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPageTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/RunAppEngineShortcutTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelperTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/DeployAssemblyEntryRemoveJobTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidationTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/ApplicationSourceQuickFixTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlSourceValidatorTest.java
- plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ProjectContextMenuTest.java
- plugins/com.google.cloud.tools.eclipse.util.test/META-INF/MANIFEST.MF
> Convert tests to java8 runtime

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
Updates Objectify, App Engine API, and Guava versions.
Closes #3553.
> Update library versions: Objectify, App Engine API, Guava

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.properties
> remove some unused messages

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/DeployPreferencesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployPreferencesPanel.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/DeployPreferences.java
fixes #3550 @chanseokoh @briandealwis
> remove option to deploy to obsolete runtimes

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/M2RepositoryServiceTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/ILibraryRepositoryService.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/M2RepositoryService.java
> missing source artifacts is not an error

- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/MavenHelper.java
> method doesn't need to be public

- .gitignore
> ignore a couple more files that get autogenerated

- .gitignore
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.ftl
> appengine-maven-plugin requires Maven 3.5.0 or later

- plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java
> correct spelling

- plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowProjectCreator.java
@briandealwis 
fixes #3579 
fixes #3498 
fixes #3376
> Dataflow only supports Java 1.8

- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectWizardTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectWizard.java
- plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/ui/CompositeUtil.java
> Display "Other Libraries" label for non-App Engine libraries group

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/Bug3380Test.java
- plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Pom.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java
- plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.ftl
> use libraries-bom in pom.xml

- features/com.google.cloud.tools.eclipse.suite.feature/feature.xml
- features/com.google.cloud.tools.eclipse.suite.feature/pom.xml
- gcp-repo/metadata.product
> prepare 1.8.4

- features/com.google.licenses.apache_v2/feature.properties
- gcp-repo/metadata.p2.inf
- plugins/com.google.cloud.tools.eclipse.ui.test/src/com/google/cloud/tools/eclipse/ui/AboutIniTest.java
- plugins/com.google.cloud.tools.eclipse.ui/about.properties
> Update copyright years

- .travis.yml
> disable codecov

- release/copy_repo_to_final_location.py
> Update release script to use Python3

- eclipse/common-dependencies.tpd
- eclipse/eclipse-2018-09/gcp-eclipse-2018-09.target
- eclipse/eclipse-2018-12/gcp-eclipse-2018-12.target
- eclipse/eclipse-2019-09/gcp-eclipse-2019-09.target
- eclipse/eclipse-2019-12/gcp-eclipse-2019-12.target
- eclipse/eclipse-2020-03/gcp-eclipse-2020-03.target
Trying to do  #3675, but properly.
> Updated common TPD location and regenerated target files

- eclipse/ide-target-platform/category.xml
- features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml
Maven version bump was necessary but not sufficient.
> Update gson version in eclipse artifacts

- eclipse/ide-target-platform/category.xml
- features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml
- pom.xml
upgrade to patched version for [vulnerability](https://github.com/advisories/GHSA-3mc7-4q67-w48m).
> update snakeyaml to 1.31

- eclipse/ide-target-platform/category.xml
- features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml
- pom.xml
upgrade to patched version for "snakeYAML before 1.32 vulnerable to Denial of Service due to Out-of-bounds Write".
> Upgrade snakeyaml to 1.32

- features/com.google.cloud.tools.eclipse.suite.feature/feature.xml
- features/com.google.cloud.tools.eclipse.suite.feature/pom.xml
- gcp-repo/metadata.product
A minor version bump, not a bugfix, since there have been quite a few changes in the last year.
> Prepare to release v1.9.0

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.facets.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.bugreport.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.ui.status.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.util.test/pom.xml
- plugins/com.google.cloud.tools.eclipse.welcome.test/pom.xml
Intended to fix flakyness in release testting
> fix(test): disable ptos in every tycho-based test

- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployCommandHandler.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesDialog.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/META-INF/MANIFEST.MF
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineProjectDeployer.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/CloudSdkStagingHelper.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/DeployJob.java
- plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/util/CloudSdkProcessWrapper.java
removes debugging logging and commented precondition checks
> chore: cleanup of `gcloud-cli-creds`

- plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/GcpLocalRunTabTest.java
- plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/GcpLocalRunTab.java
The local server run configuration tab will not load projects when opened. This fixes it
> chore: fix project list initialization in local server launch config

- plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
- plugins/com.google.cloud.tools.eclipse.googleapis.test/src/com/google/cloud/tools/eclipse/googleapis/internal/DefaultAccountProviderTest.java
fixes https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3745
> chore: fix appengine.libraries unit test
