GoogleCloudPlatform/google-cloud-eclipse

.project
Added `features`, `plugins`, `eclipse` to resource filter on parent project
=> Fixes #29 - One Google Cloud Platform for Eclipse Mars target

.travis.yml, eclipse/mars/gcp-eclipse-mars.target, eclipse/mars/gcp-eclipse-mars.tpd, eclipse/neon/gcp-eclipse-neon.target, eclipse/neon/gcp-eclipse-neon.tpd, eclipse/neon/pom.xml, pom.xml
- Update to Mars.2 and include WTP SDK features for source bundles
- Add Neon target; explicitly specify WTP Neon M6 repository as the general WTP Neon repository is not up-to-date
- Configure Travis to build against both Eclipse Mars and Neon
=> Setup target platforms for Mars and Neon

.travis.yml, pom.xml
Allow Travis to opt-out from the toolchains enforcement as its build is configured to always with with `jdk7`.  Uses a Travis profile in case we need to add more options later.
=> Add Travis profile, and allow Maven toolchains can be overridden

plugins/com.google.gcp.eclipse.appengine.localserver/gcloud_serverdef.xml
It turns out these entries are required for Eclipse. If they are missing, an error is shown in the Server Runtime Environment wizard dialog.
However running the server does not need them.
=> Adds classpath entries to the server definition

.travis.yml, pom.xml
And sets `tycho.showEclipseLog` to log any test output to stdout.
=> Re-enable Neon builds on Travis: Neon requires JDK8.

.travis.yml, pom.xml
Configure Tycho to ignore copies of build artifacts found in the local repository.  This should prevent Tycho from resolving missed references to renamed/deleted artifacts from Travis' cached repository.
=> Ensure Travis doesn't pull stale artifacts from the cached repository

features/com.google.cloud.tools.eclipse.3rdparty.feature/.project, features/com.google.cloud.tools.eclipse.3rdparty.feature/.settings/org.eclipse.core.resources.prefs, features/com.google.cloud.tools.eclipse.3rdparty.feature/.settings/org.eclipse.m2e.core.prefs, features/com.google.cloud.tools.eclipse.3rdparty.feature/build.properties, features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml, features/com.google.cloud.tools.eclipse.3rdparty.feature/pom.xml, gcp-repo/category.xml, pom.xml
Introduces a new feature, com.google.cloud.tools.eclipse.3rdparty.feature.
This feature is referenced by our generated repository but not categorized
and so will not normally appear when installing items.
PTAL @elharo
=> Fix #94 - Introduce new feature to collect additional 3rd party features

plugins/com.google.cloud.tools.eclipse.test.dependencies/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.test.dependencies/build.properties
=> Fix warnings in .test.dependencies as it has no source

plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
Setting `fork=false` just means that most of the code is executed within the UI thread, and so progress monitoring never occurs until the operation has already completed.  This doesn't much matter for very short operations, but long operations will lead to the UI hanging.
The flicker happens for two reasons.  The first problem is that the `CreateProjectOperation` and the code in `CodeTemplates` are not executed as a single workspace operation (viz `IWorkspace#run()` and `IWorkspaceRunnable`).  The project creation triggers builder activity, as does each file- and folder-creation (when not run as a workspace operation). So each of the file creations in `CodeTeamplates` is blocked until any current operations complete (hence the _user operation is block_).  The second problem is that the …
=> Fix progress dialog flicker by reworking the project creation as a single workspace operation

plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardProjectConfigTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardProjectConfig.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java
fix #130 
Open questions:
1. Should we also check in CreateAppEngineStandardWtpProject?
2. Should the user have an option to overwrite an existing directory? (My gut says no. This is just a wizard. They can always do that manually if they want to, but let's not make it easy for the user to shoot themselves in the foot.)
=> don't create project on top of existing directory

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/GCloudCommandDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/GCloudCommandDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkLaunchConfigurationDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkPublishOperation.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkPublishTaskDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkServer.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkServerBehaviour.java
This feels a bit hacky:
- explicitly specify timezone=UTC to avoid for the `NoSuchMethodException` on Java8
- copy over module publishing from GPE; run `gcloud` from the published locations
- run debug launch with `quiet=y` to avoid spurious messages on stdout, which interferes with `dev_appserver`'s communication with the running web server
- add support for launching multiple `war`s (App Engine services): have to have same App Engine Application/Project ID, and distinct `<service>` names
PTAL @elharo — I might have a chance to look at this further tonight.
=> Fix #164 - Enable run/debug on local server

plugins/com.google.cloud.tools.eclipse.appengine.localserver/gcloud_serverdef.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver/gcp.xml
@nbashirbello This PR simply builds a war archive from the web application. It does not yet supply it to the dev_appserver at the correct time. 
I may need to add a step to the deploy task that relaunches the dev_appserver to make it pick this up. 
#193
=> Build war archive

README.md, eclipse/ide-target-platform/.project, eclipse/ide-target-platform/.settings/org.eclipse.core.resources.prefs, eclipse/ide-target-platform/.settings/org.eclipse.m2e.core.prefs, eclipse/ide-target-platform/category.xml, eclipse/ide-target-platform/pom.xml, features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml, pom.xml
Tycho is able to resolve dependencies from Maven-style repositories (`pomDependencies=consider`), but the Eclipse IDE cannot.  This patch creates a new project in `eclipse/ide-target-platform` that assembles the dependencies from the Tycho build into a suitable target platform for the IDE.
Fixes #195
=> Assemble IDE Target Platform

README.md, eclipse/ide-target-platform/pom.xml, pom.xml
Instead of `cd eclipse/ide-target-platform; mvn package`, we now have a `ide-target-platform` profile that will cause the Eclipse platform to be built as an additional output of the build.
Further improve documentation of tycho.toolchains, and adds a quick start note for building.
Fixes #232 and #233 
PTAL @elharo
=> Simplify construction of the Eclipse IDE target platform

gcp-repo/category.xml, gcp-repo/invisible.product, gcp-repo/pom.xml
Change the `gcp-repo` project include the `com.google.cloud.tools.eclipse.3rdparty.feature` via an invisible product definition.  This fix ensures that the feature and its referenced bundles are included in the generated repository, but aren't listed as formally published features in the _Install New Software_ dialog.  I've also added a human-meaningful name for the repository, which is shown in the _Preferences > Install/Update > Available Software Sites_ if the user didn't explicitly specify a different label.
Fixes #234
=> Remove need to include the 3rd party feature in the final build

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/GCloudCommandDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/GCloudCommandDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/CloudSdkLaunchConfigurationDelegate.java
Launching the dev_appserver in debug mode often fails due to timing
issues.  Although we have a 500ms wait, it seems insufficient
to ensure the remote JVM has gotten to a debuggable state and
so the debug connection fails.  We instead use the socket-listen
launch, such that the remote JVM connects to the debugger.
Fix #227
=> Change debug launch to use socket-listen instead of socket-connect

plugins/com.google.cloud.tools.eclipse.preferences/.classpath, plugins/com.google.cloud.tools.eclipse.preferences/.project, plugins/com.google.cloud.tools.eclipse.preferences/.settings/org.eclipse.jdt.core.prefs, plugins/com.google.cloud.tools.eclipse.preferences/.settings/org.eclipse.m2e.core.prefs, plugins/com.google.cloud.tools.eclipse.preferences/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.preferences/build.properties, plugins/com.google.cloud.tools.eclipse.preferences/plugin.xml, plugins/com.google.cloud.tools.eclipse.preferences/pom.xml, plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/Activator.java, plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/AnalyticsOptInFieldEditor.java, plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/CloudToolsPreferencePage.java, plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/Messages.java, plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/PreferenceInitializer.java, plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/messages.properties, pom.xml
Sets up a new plugin bundle to accommodate plugin-wide preferences. Also a pre-requisite for #138. It adds a root entry "Google Cloud Tools" to the preference page. (See the screenshot below.)
This bundle is a plugin (i.e., contains 'plugin.xml') and also has an Activator. I thought these are necessary to set up a preference store and UI.
I still have to find a way to launch a web browser when a user clicks on the hyperlink (the "Google Privacy Policy" text).
About `AnalyticsOptInFieldEditor`: I created this class in order to put two controls (`BooleanFieldEditor` and `Link`) into a `Group` (i.e., a panel with a border) to have a nice-looking UI. I couldn't find a way to do so without directly extending the general base `FieldEditor` class.
=> Set up preference page global to all plugins

plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerTest.java, plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
The backend team says we should follow the convention of
/virtual/<event type>/<event name>
Per discussion in https://github.com/GoogleCloudPlatform/gcloud-intellij/pull/754#discussion_r68245423, we set the event type to our application name.
=> Follow the convention /virtual/eventType/eventName

plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
All of a sudden, I noticed that AnalyticsPingManager is not sending a HTTP request, despite the connection being made and closed actually. (No idea why.)
Calling `getResponseCode()` ensures the event message is sent.
I also set a timeout for the extremely unlikely event of the backend server holding a connection while not sending any output back. (This will never happen actually.)
=> Make a message posted / set connection timeout

plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/CloudToolsPreferencePage.java, plugins/com.google.cloud.tools.eclipse.usagetracker.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerTest.java, plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java, plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/OptInDialog.java, plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/OptInDialogCreator.java, plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/OptInPopup.java
Two enhancements:
- `sendPing()` will show the opt-in dialog (only once) if needed.
- Allows a `sendPing()` caller to set the parent shell of the opt-in dialog.
=> sendPing() triggers showing opt-in dialog

eclipse/ide-target-platform/category.xml, eclipse/mars/gcp-eclipse-mars.target, eclipse/mars/gcp-eclipse-mars.tpd, eclipse/neon/gcp-eclipse-neon.target, eclipse/neon/gcp-eclipse-neon.tpd
Required for source bundles such as org.eclipse.jst.common.project.facet.core.
With this patch `mvn -Pide-target-platform package` should include the source for `org.eclipse.jst.common.project.facet.core`.
```
$ ls eclipse/ide-target-platform/target/repository/plugins/org.eclipse.jst.common.project.facet.core*
org.eclipse.jst.common.project.facet.core.source_1.4.400.v201403261418.jar
org.eclipse.jst.common.project.facet.core_1.4.400.v201403261418.jar
```
=> Include the org.eclipse.jst.common.fproj.enablement.jdt.sdk feature

pom.xml
The 0.1.1-SHAPSHOT doesn't seem to exist anymore in the Maven Central.
=> Use 0.1.3-SNAPHSOT for appengine-plugins-core

plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizardTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardArchetypeWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizard.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/Messages.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/messages.properties
Fixes #182.
My take here is to add a second wizard page where a user selects an archetype to use.
I didn't add two Endpoints archetypes since we don't support Endpoints yet. I checked that templates are properly generated for the current two archetypes: skeleton (hello-world) and guestbook.
=> Add Archetype selection page to new project wizard

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/CloudSdkRuntimeWizardFragment.java
Fixes #337.
`configureValidationJob` also depends on the `dirTextBox` field that's triggering the NPE, but `configureValidationJob` checks if the field is initialized currently, so no more problem.
=> Fix NPE from Cloud Sdk directory field validation

plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizardTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
Fixes #229.
#229 mentions "groupId.artifactId", but the label in the wizard page says "Java package: (defaults to group ID)". For now, I just set it to groupId, since I believe artifactId usually contains hyphens.
=> Auto-set package name as groupId in project wizard

build/pom.xml, build/verify-feature-completeness/pom.xml, pom.xml
Add new test for Travis build that attempts to install the
com.google.cloud.tools.eclipse.suite.e45.feature and fails on any
missing dependencies.
Enabled for Travis builds only (i.e., `mvn -Ptravis package`).
Fixes #351
=> Verify that our feature can be installed with no missing dependencies

plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.properties, plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferencePage.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/CloudSdkProvider.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/PreferenceInitializer.java
I.e. App Engine Standard (app-tools-lib-for-java) is now just App Engine Standard
#313
=> remove app-tools-lib-for-java from assorted names

plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java, plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkContextFunctionTest.java, plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkProviderTest.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/CloudSdkProvider.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/PreferenceInitializer.java
Until https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/pull/168 and #362 and fixed, we must continue to use `CloudSdkProvider#createBuilder()` to create and configure `Cloudsdk.Builder` instances.
=> Restore CloudSdkProvider#createBuilder()

README.md, plugins/com.google.cloud.tools.eclipse.appengine.login/.classpath, plugins/com.google.cloud.tools.eclipse.appengine.login/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.login/build.properties, plugins/com.google.cloud.tools.eclipse.appengine.login/java-templates/com/google/cloud/tools/eclipse/appengine/login/Constants.java, plugins/com.google.cloud.tools.eclipse.appengine.login/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginService.java, plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginTemporaryTester.java
For #342.
Set client ID and client secret at compile-time by auto-generating `Constants.java` with `templating-maven-plugin`. (The same mechanism as in the `.eclipse.usagetracker` bundle.)
=> Set OAuth client ID and client secret at compile time

plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineSdkClasspathContainer.java
`appengine-tools-api.jar` isn't very helpful for writing servlets!
This should be exposed by the runtime component, I think: the library is currently marked for being exported.  And there must be something further required to index the jar as the classes aren't being found by content assist.
=> Fix new project setup to reference appengine-api.jar, and point to the online javadocs.

plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginService.java
I added a non-UI version for getting a credential.
In fact, it's mere a simple map query. No login, I/O, API calls involved.
=> Add a non-UI version for getting a credential

plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineProjectDeployerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/ExplodedWarPublisherTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardProjectStagingTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineProjectDeployer.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/ExplodedWarPublisher.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardProjectStaging.java
I was experimenting with cancellation for long running calls like deploy, but I believe rather the app-tools-lib should provide some hooks for this as this might be useful for other libraries building on top of app-tools-lib as well.
=> Fixes #373 - Honor cancel request from user during deploy

README.md, eclipse/ide-target-platform/ide-target-platform.target
I realized we can create a `.target` that references a directory using an Eclipse variable.  No more need to manually create a target, and we can avoid pulling in the features and do away with the warning messages about features.
PTAL @chanseokoh
=> Create a .target definition for the IDE

plugins/com.google.cloud.tools.eclipse.appengine.login.test/.classpath, plugins/com.google.cloud.tools.eclipse.appengine.login/.classpath
`com.google.cloud.tools.eclipse.appengine.login.tests` is pulling in two jars from `.login`, `google-api-client-1.22.0.jar` and `google-oauth-client-1.22.0.jar`, relating to OAuth.  `GoogleLoginServiceTest.java` is referencing `com.google.api.client.auth.oauth2.Credential`, whose definition references classes in `google-http-client-1.22.0.jar`:
```java
public class com.google.api.client.auth.oauth2.Credential implements 
com.google.api.client.http.HttpExecuteInterceptor,
com.google.api.client.http.HttpRequestInitializer,
com.google.api.client.http.HttpUnsuccessfulResponseHandler {
```  
Because this jar is not in `.login.test`'s classpath, `GoogleLoginServiceTest` is generated with errors.
I used PDE's Regenerate Classpath and all is now well.
=> Regenerate .classpath files for .login and .login.tests

plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginService.java
For now, we don't need users' email addresses.
For #461.
=> Remove email auth scope

plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java, plugins/com.google.cloud.tools.eclipse.usagetracker/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java, plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/CloudToolsInfoTest.java, plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/CloudToolsInfo.java
Fixes #137.
I believe, for now, there is only one place in code that requires setting these constants when creating a `CloudSdk` instance for server interaction.
I created a new `CloudToolsInfo` class under `.util`. Let me know if you have better suggestions or better names.
FYI, `getToolsVersion()` currently returns `0.1.0.qualifier`.
=> Enable server-side usage tracking

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
Fixes #433 
Changes our launch delegate to connect to remote JVM directly rather than creating and running a new remote launch configuration, as launch configurations are independent and are shown in the _Debug_ view.  This change ensures the remote JVM is brought under the AppEngine launch configuration.  
Fixes #473
Launches `dev_appserver` with `—max_module_instances 1` to prevent subsequent JVMs crashing trying to connect to the debugger.
=> Fix issues with debug launches for App Engine Standard apps

README.md
The section moved into https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/wiki/Cloud-Tools-for-Eclipse-Release-Instructions.
Fixes #478.
=> Migrate section for injecting comiple-time constants into Release Wiki page

plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/util/ProjectFromSelectionHelper.java
When user runs the deploy command the type of the selection depends on the current ~~perspective~~ explorer (e.g. Project Explorer (default in Java EE perspective) vs Package Explorer (default in Java perspective). If it is ~~Java~~ Package Explorer, then the selection will be an IJavaProject otherwise an IProject.
=> Fixes #482 - Cannot deploy

features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
I'm sure we will need this.
BTW, is it correct that `com.google.cloud.tools.app.lib` is in both `e45` and `3rdparty`?
=> Include usagetracker plugin to e45 feature

plugins/com.google.cloud.tools.eclipse.appengine.deploy/build.properties
I see errors in c.g.c.t.e.appengine.deploy in _ExplodedWarPublisher.java_
- The type `org.eclipse.wst.web.internal.deployables.FlatComponentDeployable` cannot be resolved. It is indirectly referenced from required .class files
- The type `org.eclipse.jst.server.core.IWebFragmentModule` cannot be resolved. It is indirectly referenced from required .class files
This patch adds compile-time dependencies on org.eclipse.wst.web (for `org.eclipse.wst.web.internal.deployables.FlatComponentDeployable`) and 
`org.eclipse.jst.server.core` (for `org.eclipse.jst.server.core.IWebFragmentModule`).  And it fixed indentation in the `Require-Bundle` too.
=> Fix indirect class references issues in com.google.cloud.tools.eclipse.appengine.deploy

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java, pom.xml
Bump maximum `PermGen` settings for Java 7 to avoid OOMEs.
Increase Maven archetype-installation timeout from 15000ms to 45000ms.
=> Avoid failures in integration tests

plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/templates/appengine-web.xml.ftl
It is used to add the appengine-web.xml to projects that install the facet.
@elharo
=> This is a new file that was part of the App Engine facet revamp PR.

plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/messages.properties, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployCommandHandler.java, plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginCommandHandler.java, plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/GoogleLoginService.java, plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/IGoogleLoginService.java, plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/ui/LoginServiceUi.java
Fixes #472 #524.
Moved out `login()` from `launchDeployJob()`, since `launchDeployJob()` sounds like it will launch a job no matter what.
Did some tests: cancel login, deny authorization, deploy while logged in, etc.
=> Inform to sign in for deploy if not signed in

plugins/com.google.cloud.tools.eclipse.integration.appengine/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProject.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTestingUtilities.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTreeUtilities.java
Adds a new test that:
- creates a native App Engine Standard project
- launches in debug mode
- verifies that the app is running
- terminates the app and verifies is no longer accessible
Fixes #560
=> Add integration test for launching native App Engine Standard project

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java
Use SWTBot's `waitUntil()` to spin on the project existence, and should timeout if the project never exists.
Fixes #584 
(I hope)
=> Change SwtBotAppEngineActions to wait for a new project to exist

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
My change that added a default source locator breaks the source locating.
Steps to repeat:
- create new native App Engine Standard project
- set a breakpoint in HelloAppEngine's `doGet`
- launch under debugger and open `http://localhost:8080/hello` to get into debugger
Notice that source is not found without this patch.
Fixes #575
=> Do not set default source locator

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewMavenBasedAppEngineProjectWizardTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewNativeAppEngineStandardProjectTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java
Add calls to `SwtBotWorkbenchActions.waitForIdle(bot)`.
```
testHelloWorld(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 5.78 sec  <<< ERROR!
java.lang.NullPointerException: facetedProject is null
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229)
at com.google.cloud.tools.eclipse.util.FacetedProjectHelper.projectHasFacet(FacetedProjectHelper.java:31)
at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.createAndCheck(NewMavenBasedAppEngineProjectWizardTest.java:103)
at com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest.testHelloWorld(NewMavenBasedAppEngineProjectWizardTest.java:51)
```
=> Wait for pending jobs on project creation

plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/ui/LoginServiceUi.java
When a user cancels login, we release a lock which terminates the dialog task and closes the dialog.
I think it's a better idea to release the lock first, since we shouldn't assume `stopCodeWaitingJob()` will throw an unchecked exception.
=> Release lock first when a user cancels login

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LocalAppEngineConsolePageParticipant.java
Cause server launch to listen and react to server state changes such that stopping the server terminates the launch.
_Note:_ this only clears up the _Debug_ situation; #614 will fix the _Run_ situation
Also cleaned up server stopping to set state to STOPPED once the server process is reported as dead.  This was to fix strange race condition where the server could be reported as STOPPED but continued to write to the console.
Fixes #516
=> Cause server launch to listen and react to server state changes

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
Scan the `dev_appserver` output for special strings to identify the server start or failure state as per #556.
Fixes #556
=> Improve SERVER_STARTED detection

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
In c0e409b1946d92bc5975cc28eb9e6127c225ecca, I mistakenly restored the call to `DefaultRunConfiguration.setMaxModuleInstances(1)` to the _run_ server setup instead of the _debug_ server setup.
=> Fix bug: Set max module instance = 1 in *debug* mode, not in *run* mode

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDebugTarget.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerTargetWrapper.java
Required for _Run_ launches to be able to be terminated.  Not required for _Debug_ launches as the the remote JVMs are added to the launch as they attach to the debugger.
Fixes #614 
Hard to test: will enhance the ITs test to test the various combinations separately.
=> Create an IDebugTarget for the Dev App Server

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployConsolePageParticipant.java
After experimenting with DeployConsolePageParticipant the import for the Messages class was not cleaned up and thus the tooltips for the action buttons were missing.
=> remove import to let the Messages class in the same package to be used

.travis.yml
Untar generates about 5300 log lines. This will cut more than half of the entire log. With this, I expect we won't see the "This log is too long to be displayed." issue (#628).
=> Cut travis log

build.sh
@chanseokoh New plan is to build the binary manually and use kokoro only to sign it. Once kokoro adds maven support, we can let it build too.
=> Kokoro doesn't support mvn yet

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployCommandHandler.java
Fixes #774.
Blocks deploy by showing an error dialog if a project has a "Problem" (i.e., if it has the small red X marker on it, or if there are any errors in the Problems view) when attempting to deploy.
=> Prevent deploy if project has problems

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppEngineTabGroup.java
Server type ID defined in plugin.xml is `com.google.cloud.tools.eclipse.appengine.standard.server`.
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml#L29
With the correct ID, our App Engine Local Server launch config tab can load server instances properly.
=> Fix mismatching server type ID

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/UrlLinkTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
Adds a URL link converter to the launch console to convert URLs into clickable links.
Goes part way to fixing #768.
=> Highlight urls in launch console

plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
Fixes #775.
Of course, attempting to use non-local hosts and IP addresses except for 0.0.0.0 will fail, which is expected.
=> Enable setting arbitrary host for local runs

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewMavenBasedAppEngineProjectWizardTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewNativeAppEngineStandardProjectTest.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotProjectActions.java
Since we're really using `SwtBotProjectActions#getErrorsInProblem()` to determine if there are any build errors, and expanding tree items is painful, just check for error markers directly.
=> Explicitly examine problem markers rather than probing the problems view

plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/Library.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/config/LibraryBuilder.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProjectTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProject.java, plugins/com.google.cloud.tools.eclipse.preferences.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.preferences.test/src/com/google/cloud/tools/eclipse/preferences/PreferenceUtilTest.java, plugins/com.google.cloud.tools.eclipse.preferences/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.preferences/src/com/google/cloud/tools/eclipse/preferences/PreferenceUtil.java
@nbashirbello @akerekes fix #731 
This also moves some now common code into the preferences package. Going forward, we may be able to move some more code here, including constants for various preference IDs.
=> save project ID preference in Maven projects too

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesDialog.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesModel.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPropertyPage.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployCommandHandler.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/DeployPreferenceInitializer.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployPreferences.java, plugins/com.google.cloud.tools.eclipse.appengine.login.test/src/com/google/cloud/tools/eclipse/appengine/login/ui/AccountSelectorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.login/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/ui/AccountSelector.java, plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/ui/AccountSelectorObservableValue.java, plugins/com.google.cloud.tools.eclipse.ui.util.test/src/com/google/cloud/tools/eclipse/ui/util/databinding/ProjectIdInputValidatorTest.java, plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/databinding/ProjectIdInputValidator.java
@akerekes @briandealwis
Fixes #759.
- Saves and loads an account selection choice (email address) into deploy preferences .
- `AccountSelectorObservableValue` defined for databinding.
- Validates the deploy dialog. (The _Deploy_ button is disabled if no account is selected.) Subsequently, the stopgap error popup dialog is removed.
- However, this is an optional preference setting (like project ID), so no validation in the preference page.
Misc:
- `OverrideValidator` constructor: I removed `super(Realm)`, as calling the default constructor (which passes the default realm) seems working fine. @akerekes, is there a reason that we should pass a specific realm?
- `allowedEmptyProjctId` --> `!requireValues`
=> Save and validate account selection

plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizardTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java, plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
Fixes #801.
`getGroupId()` calls `trim()` and doesn't return an actual value typed in the text field.
=> getGroupId() --> groupIdField.getText()

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/TestProject.java, plugins/com.google.cloud.tools.eclipse.appengine.login.test/src/com/google/cloud/tools/eclipse/appengine/login/ui/AccountSelectorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.login.test/src/com/google/cloud/tools/eclipse/appengine/login/ui/AccountsPanelTest.java, plugins/com.google.cloud.tools.eclipse.appengine.login.test/src/com/google/cloud/tools/eclipse/appengine/login/ui/ShellTestResource.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizardTest.java
1. Doing `new Display()` and `display.dispose()` didn't allow running JUnit Plug-in Test inside Eclipse. We should use `Display.getDefault()`.
- As part of this change, I created `ShellTestResoruce` (a JUnit rule) as suggested in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/805#discussion_r83248790.
2. Call `notifyListeners()` instead of directly calling the combo selection listener implementation.
@akerekes PTAL
=> Better display setup / better combo selection simulation in tests

features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml
Updated the `com.google.cloud.tools.eclipse.suite.e45.feature` to include the `.jdt.launching` bundle.  Verified now included in the built repository.
=> Ensure we include our modified JDT launching classes

plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFacetInstallDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/FacetInstallDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/FlexFacetInstallDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/Messages.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/messages.properties
Checks that the App Engine Component is installed during the facet installation. If the App Engine component is not installed, it throws an error (with instructions on how to install the component) and uninstalls the facet. So the only time a project can be flagged to have App Engine functionality is when the App Engine component is installed. 
I originally went the route of creating a builder that puts an error marker on App Engine projects when the App Engine component is missing, but it was seemed confusing because (i) the project themselves did not have any problems, the fix was outside the project (ii) even though it was an incremental builder, the times when there was a change in the project could not be correlated with when the app engine component was installed, so we were …
=> Checks for missing App Engine Component

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java, third_party/com.google.cloud.tools.eclipse.jdt.launching/src/com/google/cloud/tools/eclipse/jdi/internal/connect/SocketListeningMultiConnectorImpl.java, third_party/com.google.cloud.tools.eclipse.jdt.launching/src/com/google/cloud/tools/eclipse/jdt/internal/launching/SocketListenMultiConnector.java, third_party/com.google.cloud.tools.eclipse.jdt.launching/src/com/google/cloud/tools/eclipse/jdt/internal/launching/SocketListenMultiConnectorProcess.java, third_party/com.google.cloud.tools.eclipse.jdt.launching/tests/com/google/cloud/tools/eclipse/jdt/launching/MultipleConnectionsTest.java
Sync up with changes requested in [the Eclipse connection patch](https://git.eclipse.org/r/79579) for #609
- `MultipleConnectionsTest#testDefaultBehaviour()` shouldn't specify "acceptCount" (now "connectionLimit")
- Rename "acceptCount" -> "connectionLimit"
=> Connection limit

plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProject.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardArchetypeWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java
@lesv @akerekes This is a quick and dirty fix so the plugin (and integration tests) continue to work with the latest version of the Hello world archetype. Suggestions for improvement appreciated, though we may need to get this in sooner rather than later, since otherwise I think our integration tests are about to break. We'll definitely need to do something better when we add library configuration to the maven project wizard.
=> add properties for hello world

plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/messages.properties
The `Message` class does not have a field for that. In fact, the message has been moved to the `....appengine.ui` bundle.
=> Removed unused localized message

.travis.yml, eclipse/oxygen/.project, eclipse/oxygen/.settings/org.eclipse.core.resources.prefs, eclipse/oxygen/.settings/org.eclipse.m2e.core.prefs, eclipse/oxygen/gcp-eclipse-oxygen.target, eclipse/oxygen/gcp-eclipse-oxygen.tpd, eclipse/oxygen/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java, pom.xml, third_party/com.google.cloud.tools.eclipse.jdt.launching/META-INF/MANIFEST.MF
Revises the version ranges on our `com.google.cloud.tools.eclipse.jdt.launching` bundle to allow installing in anything from Mars on.  Change our launch configuration to first try using the Eclipse-provided _Socket Listener_ VM connector, providing it supports the _connectionLimit_ argument that was accepted for 4.7M3.  Otherwise uses our _connectionLimit_-supporting VM connector.
We could put the version ranges back into `com.google.cloud.tools.eclipse.jdt.launching`, but we'd need to ship an additional feature.  But as our VM connector won't interfere with future versions, we may as well keep it around until we move our support level to Oxygen.
=> Build with Oxygen

plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/console/BrowserSupportBasedHyperlink.java
Cause `BrowserSupportBasedHyperlink` to configure the opened browser window with location and toolbar.  It's otherwise a bit hard to use:
=> Ensure internal browser editors show the location, and toolbar.

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java
`ServerDelegate#getChildModules(IModule[])` takes an array of modules which is actually the current path down the module hierarchy.  The root module is the first module in the array, and the actual module in question is the last object in the array.
Fixes #914
=> Fix stack overflow in LocalAppEngineServerDelegate#getChildModules()

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/AppEngineLibrariesInPluginXmlTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
It will still not work because of #932 , but once javadoc.io maintainers change the CloudFlare settings, it will.
=> Fixes the URL for Objectify javadoc

plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineLibrariesSelectorGroup.java
Currently, we cast `event.getSource()` into `Button` before checking if the object is a `Button`.
=> Fix cast logic error

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
- removes the `spacing(0,0)` in `StandardDeployPreferencePanel`
- adds quotes around project name in _Deploy to App Engine Standard_ dialog
=> Improve Standard Deployment dialog spacing and title

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
=> Java8 workaround to set appengine.user.timezone=UTC is no longer required

features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml, plugins/com.google.cloud.tools.eclipse.appengine.ui/META-INF/MANIFEST.MF
With these dependencies, I can install our feature in the bare-bones Eclipse Platform (no JDT, no PDE), and create new projects and launch in the debugger with _Run on Server_/_Debug on Server_.
Fixes #981
=> Add Webtools WST+JST dependences

gcp-repo/src/main/resources/index.html
Add default `index.html` that does an immediate meta-redirect to our [installation wiki page](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/)
=> Add default index.html for gcp-repo repository

plugins/com.google.cloud.tools.eclipse.integration.appengine/pom.xml
These dependencies should now be pulled from our `.suite` feature with #986.  Our integration tests should now ensure that we include the necessary dependencies (#981).
=> Remove unnecessary dependencies from integration tests

plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/WebProjectUtil.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/ModuleUtils.java, plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/AppEngineDescriptorTest.java, plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/AppEngineDescriptor.java
- split LocalAppEngineServerDelegate#canModify() into separate methods
to simplify testing
- extract utility class for obtaining the Service ID for a WTP IModule
- extract utility class for resolving web module locations files within a
IProject
- resurrect AppEngineDeployInfo as AppEngineDescriptor for parsing and
extracting information from an appengine-web.xml; left <project>
and <version> accessors as they will be useful for warnings
Fixes #926
=> Ensure projects added to local server have unique Service IDs

pom.xml
Configure Tycho to generate [reproducible version qualifiers](https://wiki.eclipse.org/Tycho/Reproducible_Version_Qualifiers) for our build artifacts to use the date of an artifact's last commit.
=> Use reproducible, git-based artifact timestamps

plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
Associate the generic WTP/JST source computer with our launch types.  This source computer knows how to process the web modules to build up a classpath for resolving source files.
Steps to verify:
1. Close all editors.
1. Create new native CT4E project.
2. Put a breakpoint in HelloAppEngine#doGet()
3. _Debug As Server_
4. Fetch the servlet, see breakpoint trigger.
5. Source code for `#doGet` should appear.
Fixes #887
=> Configure the WTP/JST Generic Source computer

pom.xml
Otherwise the Maven build aborts if there are uncommitted files.
=> Make `jgit.dirtyWorkingTree` a configurable property and default to `warning`

plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizardStaticTest.java
@chanseokoh This should reduce the flakiness in StandardProjectWizard test
=> reorganize tests along fixture lines

plugins/com.google.cloud.tools.eclipse.welcome/build.properties
I think we need to include `intro/` (icon, CSS, and Welcome link contents) in the binary build, right?
=> Include intro/ directory in binary build

plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/ContextXmlTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/helpContexts.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardArchetypeWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizardTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/helpContexts.xml
Part of #696. I think we will want to commit the framework first with minimally acceptable help texts and iterator over them later.
Notes:
- `tycho-surefile-plugin` allows getting a Workbench in tests.
- Lower-case "standard env" in normal text body as in https://cloud.google.com/appengine/docs/about-the-standard-environment
=> Add context help to new Maven project wizard

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/AbstractProjectTests.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProject.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DeployPropertyPageTest.java, plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java
@nbashirbello @briandealwis Noticed in the log from https://api.travis-ci.org/jobs/182184944/log.txt?deansi=true that this is a flaky failure mode that doesn't have to cause the test to fail. If we timeout deleting the project in tearDown, the test itself can still have passed.
=> don't fail test due to timeout in tearDown when deleting project

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployCommandHandlerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/EclipseContextHolder.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LaunchAppEngineStandardHandlerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/ServerTracker.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppEngineTabGroup.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LaunchAppEngineStandardHandler.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LaunchModes.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/ServerPortExtension.java, plugins/com.google.cloud.tools.eclipse.test.util/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/TestProjectCreator.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/ui/ExecutionEventBuilder.java, plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/status/StatusUtil.java
- Creates a new command `com.google.cloud.tools.eclipse.appengine.localserver.launch` that takes a parameter as to whether it should run or debug.  This command can be invoked from the Quick Access.
- Provides a single handler that supports either the selected projects (e.g., from the _Project Explorer_) or if the project containing the file in the current editor.
- extracts a few helper methods from elsewhere to aid in testing
Part of #225
=> Implements _Launch on App Engine_

plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProjectTest.java
I have been investigating #1086 since yesterday afternoon. I looked into the `FacetedProject` code, but I can't get how this error can ever happen. It doesn't make sense. I guess this will be very tricky to find a cause. This PR will log information like this:
```
No. targeted runtimes: 1
Runtime: App Engine Standard Runtime
Primary runtime: App Engine Standard Runtime
File in sync? true
<?xml version="1.0" encoding="UTF-8"?>
<faceted-project>
<runtime name="App Engine Standard Runtime"/>
<fixed facet="wst.jsdt.web"/>
<installed facet="java" version="1.7"/>
<installed facet="jst.web" version="2.5"/>
<installed facet="com.google.cloud.tools.eclipse.appengine.facets.standard" version="1"/>
<installed facet="wst.jsdt.web" version="1.0"/>
</faceted-project>
```
=> Log more info for setPrimaryRuntime CoreException

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/pom.xml
Avoid spurious messages in our tests like the following by replacing SDK features with runtime features:
```
!ENTRY org.eclipse.equinox.registry 2 0 2016-12-09 11:37:52.205
!MESSAGE The extensions and extension-points from the bundle "org.eclipse.wst.common.infopop.source" are ignored. The bundle is not marked as singleton.
!ENTRY org.eclipse.equinox.registry 2 0 2016-12-09 11:37:52.205
!MESSAGE The extensions and extension-points from the bundle "org.eclipse.wst.validation.infopop.source" are ignored. The bundle is not marked as singleton.
!ENTRY org.eclipse.equinox.registry 2 0 2016-12-09 11:37:52.345
!MESSAGE The extensions and extension-points from the bundle "org.eclipse.wst.command.env.infopop.source" are ignored. The bundle is not marked as singleton.
```
=> Avoid running tests with SDK features

plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject/plugin.xml
Adds the native and maven projects to the _New_ menu.  Note that, you'll need to reset your perspective to pick up these changes if you're running from an existing workspace/window.
.
=> Add new project wizard extensions

plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/META-INF/MANIFEST.MF
Fixes #1105.
They were from the `.newproject.maven.test` bundle. (I changed the title of #1105.) The `tycho-surefire-plugin` in `pom.xml` of the bundle already defined the product `org.eclipse.platform.ide`, but it didn't help. Adding the `org.eclipse.equinox.event` bundle eliminates the errors.
=> Add org.eclipse.equinox.event dep to eliminate test output clutters

plugins/com.google.cloud.tools.eclipse.welcome/intro/cloud-tools-for-eclipse.xml, plugins/com.google.cloud.tools.eclipse.welcome/intro/css/intro.css
Closes #1009. Clicking on the link opens https://cloud.google.com/eclipse/docs/release-notes.
=> Add CT4E Release Note link to What's New Welcome page

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties, plugins/com.google.cloud.tools.eclipse.appengine.login/src/com/google/cloud/tools/eclipse/appengine/login/ui/AccountSelector.java
Fixes #1124.
Most of the tooltip text are taken from `gcloud app deploy --help`. I verified that every tooltip is working.
=> Add tooltips to deploy dialog

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelperTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.properties, plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchAppEngineStandardHandler.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelper.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LocalAppEngineStandardLaunchShortcut.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/Messages.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/messages.properties, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
This patch adds support for _Run As_/_Debug As_ launch shortcuts for the local App Engine development server.  Some of the text shown to the UI needs feedback/refinement.
I've backed out the menu contributions to the popup menu (which added a _Debug on App Engine_ options), but kept the launch command/handlers as they will be useful for an GPE-like toolbar drop-down.
Fixes #225
----
_Run As_/_Debug As_ from a selection of projects:
Clicking on the _Debug_ toolbar button when selecting a project or on a file in the editor:
----
I added a check to our `LocalAppEngineServerLaunchConfigurationDelegate#launch()` to check that the server is in a stopped state to prevent double-launches.  Launching an already-running server results in an error message:
----
I added some support in …
=> Add Run As/Debug As support

README.md
On importing the code into a clean installation, M2Eclipse didn't prompt for the Tycho connectors on import but only after restarting.
=> Add note about Tycho connectors

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelper.java
My last commit on #1145 (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1145/commits/f306514d58a85c07c7b423390bf75912f3669b77) backed out an externalized string used in a `Preconditions` call, but neglected to commit the change to the actual `Preconditions` call.
=> Forgotten file on #1145

plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/build.properties
Exports the necessary help context file.
The native wizard had this and was working fine, on the other hand.
=> Export Maven new project wizard help context file

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployCommandHandler.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java
No one calls `Builder.exporter()`, `Builder.staging()`, and `Builder.deployer()`, and we always use `ExplodedWarPublisher`, `StandardProjectStaging`, and `AppEngineProjectDeployer`. In fact, I think we don't even need the fields for these. Even if we may need to provide alternatives for these in the future, it could be YAGNI.
Let me know what you think.
=> Simplify code by removing StandardJobDeployJob builder

features/com.google.cloud.tools.eclipse.suite.e45.feature/build.properties, features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml, plugins/com.google.cloud.tools.eclipse.appengine.ui/about.ini, plugins/com.google.cloud.tools.eclipse.appengine.ui/about.properties, plugins/com.google.cloud.tools.eclipse.appengine.ui/build.properties
Cause `com.google.cloud.tools.eclipse.appengine.ui` to be a _branding plugin_ for CTE, to contribute to the _About_ dialog.  Although this doesn't seem the best bundle to use, I used it as it's the bundle that's hosting our images.
The use of an `about.properties` is required for the `{featureVersion}` substitution to be performed.
=> Add "About" feature branding information

release/release_after_kokoro.sh
The script covers steps from 14 in the release instructions. I used it to make the last release, so I know it's working. It's semi-automatic and interactive, as some steps need to get some values such as a path to an Eclipse executable or a release version string. The script will certainly help a lot, since the steps are long, can be error-prone and time-consuming.
The script is safe (in terms of public visibility) to cancel out anytime and re-run, unless you execute the final step which makes things visible to public.
I don't think I follow the Google-style, if it exists. I won't mind if we don't merge this. For example, this could be kept in a separate branch.
Part of #354
=> Add semi-auto script for the second release part

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/pom.xml, plugins/com.google.cloud.tools.eclipse.integration.appengine/pom.xml, plugins/com.google.cloud.tools.eclipse.test.logback/.classpath, plugins/com.google.cloud.tools.eclipse.test.logback/.project, plugins/com.google.cloud.tools.eclipse.test.logback/.settings/org.eclipse.core.resources.prefs, plugins/com.google.cloud.tools.eclipse.test.logback/.settings/org.eclipse.jdt.core.prefs, plugins/com.google.cloud.tools.eclipse.test.logback/.settings/org.eclipse.m2e.core.prefs, plugins/com.google.cloud.tools.eclipse.test.logback/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.test.logback/build.properties, plugins/com.google.cloud.tools.eclipse.test.logback/logback.xml, plugins/com.google.cloud.tools.eclipse.test.logback/plugin.properties, plugins/com.google.cloud.tools.eclipse.test.logback/pom.xml, plugins/com.google.cloud.tools.eclipse.util.test/pom.xml, pom.xml
Although bringing in Logback for the tests (#1143) did rid us of the SLF4j errors (#263), the cure was worse than the disease as Logback's [default configuration logs at the `DEBUG` level](http://logback.qos.ch/manual/configuration.html#automaticConf), and our logs are now clogged with m2e-related `DEBUG`-level detail.  This patch creates a new fragment, `com.google.cloud.tools.eclipse.test.logback`, hosted against `ch.qos.logback.classic`, that provides a `logback.xml` configuration file that sets the default logging level to `INFO`.
Logback can be configured either by setting system property to point to a `logback.xml`, or by finding the file on its classpath.  Maven doesn't provide a way to easily reference a file (requires using the _assembly_ plugin or something).  We could configure …
=> Quieten Maven builds by specifying a logback configuration for tests

plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineStandardWizardPage.java
The problem started with #1240, when the line was removed (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1240#discussion_r96426626). I believe the removed line was setting `GridData` and not `GridLayout`, so it is necessary.
=> Fix input field length in native wizard

features/com.google.cloud.tools.eclipse.suite.e45.feature/build.properties
Fixes #1246 by including the `.suite` feature's `p2.inf` once again.
=> Feature advice must include p2.inf

release/release_after_kokoro.sh
Part of #1253. I noticed verifying jars takes quite some time, so I decided to let `jarsigner` print verification results.
I also automated verification of constant injection.
Output looks like below:
```
Operation completed over 29 objects/6.4 MiB.
+ set +x
#
#
com.google.cloud.tools.eclipse.appengine.deploy_0.1.0.201701132149.jar: jar verified.
com.google.cloud.tools.eclipse.appengine.deploy.ui_0.1.0.201701161800.jar: jar verified.
com.google.cloud.tools.eclipse.appengine.facets_0.1.0.201701112147.jar: jar verified.
com.google.cloud.tools.eclipse.appengine.libraries_0.1.0.201701132149.jar: jar verified.
com.google.cloud.tools.eclipse.appengine.localserver_0.1.0.201701112147.jar: jar verified.
com.google.cloud.tools.eclipse.appengine.login_0.1.0.201701132149.jar: jar verified. …
```
=> Verify if jars are all signed

plugins/com.google.cloud.tools.eclipse.test.logback/src/README.txt
@briandealwis Hack to avoid occasional build errors in Eclipse since welcome doesn't contain any Java code. 
Description	Resource	Path	Location	Type
Project 'com.google.cloud.tools.eclipse.welcome' is missing required source folder: 'src'	com.google.cloud.tools.eclipse.welcome		Build path	Build Path Problem
=> avoid build problems in eclipse

gcp-repo/src/main/resources/index.html
Change our `index.html` from pointing at our GitHub wiki to _cloud.google.com/eclipse/docs_
=> Update gcp-repo's index.html to point to cloud.google.com

plugins/com.google.cloud.tools.eclipse.sdk.ui.test/.project
Current shows `com.google.cloud.tools.eclipse.util.test`.
=> Fix project name for plugins/com.google.cloud.tools.eclipse.sdk.ui.test

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.ui.test/pom.xml, plugins/com.google.cloud.tools.eclipse.integration.appengine/pom.xml, plugins/com.google.cloud.tools.eclipse.sdk.ui.test/.project
Ensure that tests requiring the Workbench (_useUIHarness=true_) pull in the `org.eclipse.rcp` feature. 
Fixes #1105
=> Ensure `org.eclipse.rcp` feature is on workbench-related tests

eclipse/ide-target-platform/category.xml, eclipse/mars/gcp-eclipse-mars.target, eclipse/mars/gcp-eclipse-mars.tpd, eclipse/neon/gcp-eclipse-neon.target, eclipse/neon/gcp-eclipse-neon.tpd, eclipse/oxygen/gcp-eclipse-oxygen.target, eclipse/oxygen/gcp-eclipse-oxygen.tpd, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/pom.xml, plugins/com.google.cloud.tools.eclipse.integration.appengine/pom.xml, plugins/com.google.cloud.tools.eclipse.util.test/pom.xml
Pull in the log4j facade for slf4j, confusingly named `org.slf4j.log4j` in Eclipse Orbit.  We need the version from Orbit as m2e pulls in the SLF4j bundle from Orbit.  `org.slf4j.log4j` is only used in tests.
Fixes #1290
=> Pull in the lof4j -> slf4j facade for tests

plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallationTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java
Fixes #1291.
WTP doesn't override if `web.xml` already exists, as shown below (WTP source code):
```java
private void createWeb25DeploymentDescriptor(final IProject project, final IProjectFacetVersion fv, 
IFolder webinfFolder, IProgressMonitor monitor) throws CoreException {
// Create the deployment descriptor (web.xml) if one doesn't exist
IFile webxmlFile = webinfFolder.getFile("web.xml"); //$NON-NLS-1$
if (!webxmlFile.exists()) {
try {
// Create a minimal web.xml file, so the model can be initialized
final String webXmlContents = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<web-app id=\"WebApp_ID\" version=\"2.5\" xmlns=\"http://java.sun.com/xml/ns/javaee\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://java.sun.com/xml/ns/javaee …
```
=> Generate web.xml when installing Dynamic Web Module facet

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/SerializableClasspathEntry.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/SerializableLibraryClasspathContainer.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProviderTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPageTest.java, plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/CloudSdkPreferenceAreaTest.java, plugins/com.google.cloud.tools.eclipse.swtbot/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotWorkbenchActions.java, plugins/com.google.cloud.tools.eclipse.test.util/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
Assorted fixes to enable tests to pass on Windows 10:
- a few path comparisons were being done with `IPath.toOSString()` and so messing up `\` with `/`
- Cloud SDK tests used `Files.listRoots()[0]` to obtain a root directory, which is `A:` on Windows, the floppy drive
- Integration tests failing due to files still being written to after deletion.  Enhance test utility classes `SwtBotWorkbenchActions#waitForIdle()` and `ProjectUtils#waitForIdle()` to join to as many WTP job families as I could find.  It's possible the `ValidationFramework` jobs are the only ones we really need to wait for, but the rest cannot hurt.
Fixes #841
=> Get tests working on Windows 10

plugins/com.google.cloud.tools.eclipse.appengine.compat.test/src/com/google/cloud/tools/eclipse/appengine/compat/GpeMigratorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.compat/src/com/google/cloud/tools/eclipse/appengine/compat/GpeMigrator.java, plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/NatureUtilsTest.java
I'm seeing reference errors in my Eclipse as `GpeMigrator` and `NatureUtils` are referencing `FacetedProject.METADATA_FILE` and
`FacetedProjectNature.NATURE_ID` but are not importing
`org.eclipse.wst.common.project.facet.core.internal`.
Not sure why this isn't causing errors in the Travis build.  I do see testing errors in my local build, though it didn't fail the compilation process.
=> Fix compilation errors in .appengine.compat and .test.util

plugins/com.google.cloud.tools.eclipse.appengine.ui/plugin.xml, plugins/com.google.cloud.tools.eclipse.login/plugin.xml
- `.appengine.ui`: adds an `account` placeholder in the GCP toolbar at the end
- `.login`: adds a login contribution to the account placeholder
We should move the GCP toolbar to a more central location than `.appengine.ui`.
=> Add "Accounts" section to the GCP toolbar

README.md
@akerekes end user docs have moved off github
fix #1336
=> https://cloud.google.com/eclipse/docs/

features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml, features/com.google.cloud.tools.eclipse.suite.e45.feature/pom.xml, gcp-repo/metadata.p2.inf
@briandealwis This PR definitely doesn't work. That is, the compile breaks. The question is why? What else needs to change?
Where is com.google.cloud.tools.eclipse.category defined such, specifically the requirement that it needs 'com.google.cloud.tools.eclipse.suite.e45.feature.feature.group [0.1.0,1.0.0]'
That sounds like a MANIFEST.MF problem, not a pom.xml problem. 
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: com.google.cloud.tools.eclipse.dist 1.0.0.qualifier
[ERROR]   Missing requirement: com.google.cloud.tools.eclipse.category 1.0.0 requires 'com.google.cloud.tools.eclipse.suite.e45.feature.feature.group [0.1.0,1.0.0]' but it could not be found
[ERROR]   Cannot satisfy dependency: com.google.cloud.tools.eclipse.dist 1.0.0.qualifier depends on: …
=> another try

plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/GoogleLoginService.java
Now I see no harm in returning a copy of `Accounts`.
=> Return a copy of account set

plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/convert/AppEngineStandardProjectConvertJobTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/ui/AppEngineStandardProjectConvertCommandHandlerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/CreateMavenBasedAppEngineStandardProjectTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineStandardWtpProjectTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/BaseProjectTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProjectTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DeployPropertyPageTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewMavenBasedAppEngineProjectWizardTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/NewNativeAppEngineStandardProjectTest.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotWorkbenchActions.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/ThreadDumpingWatchdog.java
@chanseokoh noticed a sporadic failure that is due to removing the call to `SWTWorkbenchBot#resetWorkbench()` in #1348, which leaves the `DeployPropertyPageTest` dialog up and interferes with some of the subsequent tests.
```
testHelloWorld(com.google.cloud.tools.eclipse.integration.appengine.NewMavenBasedAppEngineProjectWizardTest)  Time elapsed: 31.072 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.exceptions.WidgetNotFoundException: Could not find menu bar for shell: Shell with text {Properties for foo}
at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:522)
at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:496)
at org.eclipse.swtbot.swt.finder.SWTBotFactory.waitUntil(SWTBotFactory.java:484)
at …
```
=> Add safe implementation of SWTBot's resetWorkbench()

plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/NonSystemJobSuspender.java
Ensure that Job changes are not done when object monitors are held.
Fixes #1373
=> Reduce synchronization region in NonSystemJobSuspender

plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProjectTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotProjectActions.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTestingUtilities.java, plugins/com.google.cloud.tools.eclipse.test.util/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/ThreadDumpingWatchdog.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/TestProjectCreator.java
[Address the finding in #1345](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1345#issuecomment-278784059) that there may be Dependency Graph update jobs already in progress by waiting for any DG update jobs to complete.
Follows on to #1375.
Build failures seen have been related to #1373, and will be addressed by #1376.
Fixes #1345 
Fixes #1314
=> Wait for Dependency Graph update job

pom.xml
Verified build breaks by modifying `com.google.cloud.tools.eclipse.util` to import a package from Guava 15.
=> Ensure we only use Guava 20

plugins/com.google.cloud.tools.eclipse.login/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/GoogleLoginService.java
#1381
Setting it for the test constructor isn't really necessary, but to be consistent.
=> Set application name for login API

eclipse/ide-target-platform/category.xml, eclipse/mars/gcp-eclipse-mars.target, eclipse/mars/gcp-eclipse-mars.tpd, eclipse/neon/gcp-eclipse-neon.target, eclipse/neon/gcp-eclipse-neon.tpd, eclipse/oxygen/gcp-eclipse-oxygen.target, eclipse/oxygen/gcp-eclipse-oxygen.tpd, features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml, plugins/com.google.cloud.tools.eclipse.aeri.test/.classpath, plugins/com.google.cloud.tools.eclipse.aeri.test/.project, plugins/com.google.cloud.tools.eclipse.aeri.test/.settings/org.eclipse.core.resources.prefs, plugins/com.google.cloud.tools.eclipse.aeri.test/.settings/org.eclipse.jdt.core.prefs, plugins/com.google.cloud.tools.eclipse.aeri.test/.settings/org.eclipse.m2e.core.prefs, plugins/com.google.cloud.tools.eclipse.aeri.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.aeri.test/build.properties, plugins/com.google.cloud.tools.eclipse.aeri.test/pom.xml, plugins/com.google.cloud.tools.eclipse.aeri.test/src/com/google/cloud/tools/eclipse/aeri/DummyTest.java, plugins/com.google.cloud.tools.eclipse.aeri/.classpath, plugins/com.google.cloud.tools.eclipse.aeri/.project, plugins/com.google.cloud.tools.eclipse.aeri/.settings/org.eclipse.core.resources.prefs, plugins/com.google.cloud.tools.eclipse.aeri/.settings/org.eclipse.jdt.core.prefs, plugins/com.google.cloud.tools.eclipse.aeri/.settings/org.eclipse.m2e.core.prefs, plugins/com.google.cloud.tools.eclipse.aeri/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.aeri/build.properties, plugins/com.google.cloud.tools.eclipse.aeri/pom.xml, pom.xml
#517
- Setting up skeleton bundles.
- Pulling AERI in the target platform. (This doesn't change `sequenceNumber`, and I wonder if it's OK?)
```xml
<target name="GCP for Eclipse Mars" sequenceNumber="1485456851">
```
@briandealwis FYI, I fixed miscellaneous things in the skeletons, including
- various things regarding Java 8 --> Java 7
- `Google, Inc.` --> `Google Inc.`
- `bin/` --> `target/classes/`
- typos in a bundle name
- etc
=> Set up AERI bundles for exception reporting

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProjectTest.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTreeUtilities.java
Also: increase timeout to 10s in DebugNativeAppEngineStandardProjectTest.testDebugLaunch when waiting for server termination
=> Option to define timeout for SwtBotTreeUtilities.waitUntilTreeContainsText

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelper.java
Explicitly call out to `ServerUIPlugin.saveEditors()` before starting the server with `IServer#start()`. Using `ServerUIPlugin.saveEditors()` respects the user's setting in _Preferences > Server > Launching > Save dirty editors before starting the server_. This is the same approach used by the _Servers_ view. There is one downside: if the user says _No_ to saving dirty editors, then the user will see the same puzzling behaviour as they will be prompted a second time as the server launch continues in the background.  But this same behaviour is seen when using the _Servers_ view.
Fixes #1427
=> Explicitly prompt user to save dirty editors before launch

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/ModuleUtilsGetAllModulesTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/ModuleUtilsTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/ModuleUtils.java
Platform/Debug uses _LaunchConfigurationDelegate#getProjectsForProblemSearch()_ to return the list of projects to check for build errors.  Our launch configuration is not quite configured as expected by our superclass's implementation in `AbstractJavaLaunchConfigurationDelegate` and so we seemingly have no projects to check.  This fix provides an implementation of _getProjectsForProblemSearch()_ and _getBuildOrder()_ as derived from the server's configured modules.  The implementation requires obtaining the full list of modules used in a server definition (modules can have child modules — seen particularly in maven projects as per #136).
Fixes #1423
=> Implement LaunchConfigurationDelegate#getProjectsForProblemSearch()

plugins/com.google.cloud.tools.eclipse.appengine.validation/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ApplicationQuickFix.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ToServlet25QuickFix.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/ValidationUtils.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/XsltQuickFix.java
fixes #1420 
Fixes issue where quick fix was overwriting file in memory even if there were unsaved changes in the editor. Attempts to read file from editor, if file is not in the editor, then it must be saved anyway, so just reads from memory.
=> Fix quick fix

plugins/com.google.cloud.tools.eclipse.login/plugin.xml, plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/CredentialHelper.java, plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/GoogleLoginCommandHandler.java, plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/MenuContributionInitializer.java
Moving `MenuContributionInitializer` and `GoogleLoginCommandHandler` to the `.ui` package.
=> Move UI classes to .ui package

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEnginePublishOperationTest.java
It seemed to hang in [one of the builds](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1480#issuecomment-282359911) for unknown reasons.
=> Add timer watchdog to LocalAppEnginePublishOperationTest

plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/ui/AppEngineStandardProjectConvertCommandHandlerTest.java
A _DependencyGraph_ deadlock reared its head in a build again:
```
"main" [1] TIMED_WAITING on org.eclipse.core.internal.jobs.Semaphore@2f5456c3
|     at java.lang.Object.wait(Native Method)
|     - waiting on org.eclipse.core.internal.jobs.Semaphore@2f5456c3
|     at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:39)
|     at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:170)
|     at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:106)
|     at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:82)
|     at org.eclipse.wst.common.componentcore.internal.StructureEdit.getComponentModelRoot(StructureEdit.java:467)
|     at org.eclipse.wst.common.componentcore.internal.StructureEdit.getWorkbenchModules(StructureEdi …
```
=> Avoid WTP DependencyGraph-related deadlocks

plugins/com.google.cloud.tools.eclipse.appengine.validation.test/build.properties, plugins/com.google.cloud.tools.eclipse.appengine.validation/build.properties
I'm seeing inconsistent-class-hierarchy errors within Eclipse as the compiler requires some JFace class definitions when processing `XsltQuickFix` and `ValidationTestUtils`.  We can make them available with the `additional.bundles` directive.
=> Fix inconsistent class hierarchy errors within Eclipse

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializerTest.java
Noticed a test hang in LibraryClasspathContainerInitializerTest.
```
Running com.google.cloud.tools.eclipse.appengine.libraries.LibraryClasspathContainerInitializerTest
!SESSION 2017-02-27 21:41:58.224 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.eclipse.tycho.surefire.osgibooter.headlesstest -testproperties /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/target/surefire.properties
Command-line arguments:  -debug -consolelog -data /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine …
```
=> Add watchdog timer to LibraryClasspathContainerInitializerTest

plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AbstractXmlValidatorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/BannedElementTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/ValidationUtilsTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AbstractXmlValidator.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineBlacklistElement.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidator.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/BannedElement.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/BlacklistScanner.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/JavaServletElement.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/MavenPluginElement.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/PomXmlScanner.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/PomXmlValidator.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlScanner.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidator.java
Creates subclasses of BannedElement that contain a marker ID and severity, to allow validators to add more than one type of marker to a resource during validation.
=> Refactor BannedElement

plugins/com.google.cloud.tools.eclipse.appengine.validation.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XsltSourceQuickFixTest.java, plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/WorkbenchUtil.java
Fixes #1527.
About `org.eclispe.platform`: I had originally thought using `org.eclipse.platform` instead of `org.eclipse.rcp` somehow eliminated the build hang (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1484#issuecomment-282609491), but it wasn't the case, so I am reverting that.
=> Fix build hang on .validation.test

plugins/com.google.cloud.tools.eclipse.appengine.flex/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.ui/plugin.xml
Adds placeholders to our GCP Toolbar's _New_ menu to separate _Standard_ options from _Flexible_.
Fixes #1536
=> Order our New menu to distinguish App Engine Standard from Flexible

plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
`ProjectUtils#waitForProjects()` has a few issues:
- I encountered a live lock problem with #1455 where `ProjectUtils#waitForProjects()` would spin trying to join on the workbench's Auto-Build job.
- Separately @chanseokoh pointed me at a [hung Travis build ](https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/208831940).
- It would spin until all build errors were resolved, which results in tests eventually timing out if those errors are never resolved (e.g., because of network resolution errors outside of our control)
This change ensures:
- we only wait on runnable `Job`s
- we track whether the build errors have reached a fixpoint
- we output debug information after 10s have elapsed (could tune this further)
=> Make ProjectUtils.waitForProjects() more robust

features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml, features/com.google.cloud.tools.eclipse.suite.e45.feature/pom.xml, gcp-repo/metadata.p2.inf, gcp-repo/metadata.product
@chanseokoh @briandealwis 
Do we need to update this anywhere else?
=> update version to 1.0.1

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibraries.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactory.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java, plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineLibrariesSelectorGroup.java
@nbashirbello @akerekes fix #1467 
Soon these classes are going to be used for non-AppEngine libraries such as Cloud SQL. Hence the rename.
=> move AppEngineLibraries to model package and rename

plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
=> Fix ProjectUtils#waitForProject() to use all projects when none are specified

plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/PomXmlScannerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlScannerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/PomXmlScanner.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlScanner.java
Fix #1581 
@chanseokoh @elharo
=> Don't ignore case in xml validation

plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/ApiClientLibrariesPageTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/MessagesTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/ApiClientLibrariesPage.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPage.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/messages.properties, plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.properties, plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibraries.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.ui.test/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineLibrariesSelectorGroupTest.java, plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/LibrarySelectorGroup.java
@briandealwis @akerekes 
This PR refactors the library page so that we can add multiple library groups with different jars.
As an example, this PR defines a new API Client library in an API group that adds the google-api-client, google-oauth-client and google-http-client jars.
=> add client libraries group

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPathTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/SourceAttacherJobTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryClasspathContainerSerializerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainer.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializer.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/SourceAttacherJob.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFactory.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/SerializableAccessRules.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/SerializableAttribute.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/SerializableClasspathEntry.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/SerializableLibraryClasspathContainer.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java
I was looking at the code in .libraries and thought I could improve readability a bit, mainly by using `List` in place of primitive Java arrays.
@akerekes what do you think?
=> Simplify library code

README.md, build/jacoco/pom.xml
- add `com.google.cloud.tools.eclipse.googleapis` and `com.google.cloud.tools.eclipse.appengine.flex`
- tweak `README.md` to add note about including new bundles and fragments in `build/jacoco`
=> Update build/jacoco for new bundles & tests

.travis.yml, build/install-cloudsdk.sh
Rather than download and install the Google Cloud SDK & App Engine Java components for each build, cache the installation and only update when we configure a new version.
This is different than the previous behaviour which always did a `gcloud components update` to update to the latest version.
It's unclear if this will increase performance much, but it will insulate us from failures to download from google.com.
Oh, and this updates to 147.0.0.
=> Configure Travis to cache Google Cloud SDK

README.md, eclipse/pom.xml
Add a `pom.xml` to `eclipse/` to allow generating the `ide-target-platform` without having to build the entire project.
=> Simplify generating ide-target-platform

plugins/com.google.cloud.tools.eclipse.googleapis/.classpath
Necessary, otherwise there's a build error in Eclipse after updating on `master`
=> ran update classpath to add google-api-services-storage-v1-rev98-1.22.0.jar to c.g.c.t.e.googleapis's classpath

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanelTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java, plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/AccountSelectorTest.java, plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/AccountSelector.java
Fixes #1656, primarily. Fixes #1566 too.
Now the entity that auto-selects a single account is the deploy panel, not the `AccountSelector` itself. We already have a test in the panel if an account is auto-selected, so we are covered.
=> Let data binding auto-select single account

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
@akerekes fix #1630 
also corrects capitalization of "flexible" and "standard" environments to bring in sync with other Google docs
=> folder --> directory

build/verify-feature-completeness/pom.xml, features/com.google.cloud.tools.eclipse.suite.e45.feature/p2.inf
Only forbid the GPE _New Android Cloud Project_ support.
Adds main ADT feature to the `build/verify-feature-completeness` to ensure it co-installs alongside ADT.
Fixes #1678
=> Allow co-installing with ADT

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/messages.properties, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java
Clarify message shown when attempting to add a module/project to a server with a module with same Service ID.
> {project} and {project} have same App Engine Service ID: {service}
to
> Cannot add "{project}" as project "{project}" has App Engine Service ID: {service}
Fixes #1030 (as best we can)
=> Change conflicting service message

plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/convert/AppEngineStandardProjectConvertJobTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/FacetUtil.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/WebProjectUtil.java
Update `AppEngineStandardFacet` install-facet to use `WebContent` if the desired `src/main/webapp` default overlaps with the project's source folders (e.g., `src`).  `WebContent` is the default location used by the WTP _Dynamic Web Facet_.
Fixes #1647
=> Ensure no overlap between source paths and WEB-INF location

plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/PomXmlValidatorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/MavenContext.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/PomXmlValidator.java
Uses XPath in pom.xml validation to select groupId elements instead of manually traversing the element tree.
=> Switch to XPath

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/ProjectSelectorSelectionChangedListener.java
Fixes #1726.
Because this is a concurrency issue, it's very difficult to write a test, unless we torture the code that deals with concurrency to become test-centric, which I don't think is a good idea.
=> Reset latest query job references

plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/CleanupOldDeploysJob.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java, plugins/com.google.cloud.tools.eclipse.appengine.flex.test/src/com/google/cloud/tools/eclipse/appengine/flex/FlexFacetInstallDelegateTest.java, plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/CredentialHelperTest.java, plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/CredentialHelper.java
One notable change is that I removed the `credentialFile` clean-up in the `finally` block. Anything (including the credential file) in the `workDirectory` will be cleaned up by [`CleanupOldDeploysJob`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/v1.0.2/plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/CleanupOldDeploysJobTest.java), so there is no point in deleting only the credential file here.
=> Refactoring and code simplification

plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineProjectDeployerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/DeployStagingTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineProjectDeployer.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/DeployStaging.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java
For #1685.
Change the signature of `deploy()` to accept the directory containing the optional config files (`cron.yaml`, `queue.yaml`, etc.).
Details:
For flex deploy, we need to pass the original source locations of the config files when calling `gcloud app deploy`. (Unlike standard, flex staging never copies those files when staging.)
=> Change deploy() signature for flex deploy preparation

plugins/com.google.cloud.tools.eclipse.appengine.compat.test/src/com/google/cloud/tools/eclipse/appengine/compat/GpeMigratorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlValidatorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XsltQuickFixTest.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/TestProjectCreator.java
`.localserver.test` takes more than 4 minutes on Travis, so I changed `TestProjectCreator`. Changes in all the other files are just dumb code clean-up.
Before: `[INFO] com.google.cloud.tools.eclipse.appengine.localserver.test SUCCESS [04:13 min]`
After: `[INFO] com.google.cloud.tools.eclipse.appengine.localserver.test SUCCESS [01:40 min]`
=> Make TestProjectCreator create project lazily

plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/DeployPreferencesConverterTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/standard/StandardDeployCommandHandler.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/DeployPreferencesConverter.java
`toDeployConfiguration()` is a pure function (which is the only method of `DeployPreferencesConverter`), so making it `static`. One less class to worry about states.
=> Make DeployPreferencesConverter stateless

plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/CleanupOldDeploysJobTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/CleanupOldDeploysJob.java
Fixes #1807.
Fortunately, existing tests cover end-to-end testing.
=> Use Files.listFiles() instead of DirectoryStream

plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/StandardDeployJobTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/standard/StandardDeployJob.java
`StandardDeployJob` will become `abstract` (after renaming to `DeployJob`), so it didn't really seem fit to instantiate a concrete class in this test, where all the tests are about `getDeployAppUrl()`. It was easy to make it `static`, so I decided to go ahead not to instantiate concrete classes.
=> Refactor code

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployCommandHandler.java, plugins/com.google.cloud.tools.eclipse.ui.util/src/com/google/cloud/tools/eclipse/ui/util/MessageConsoleUtilities.java
Minor code refactoring. Couldn't resist doing this. Grouping code more locally: now the first part of `launchDeployJob()` is to create and show a console, and the next part is to prepare arguments (`workDirectory`, etc.) for `new DeployJob()`.
=> Refactor DeployCommandHandler

plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/pom.xml
Since `<useUIHarness>` in #1816, `.dataflow.ui.test` throws too much garbage in build logs due to #1105, to the point of Travis not being able to display the whole log: https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/223416573. Adding `org.eclipse.rcp` takes care of it.
=> Add org.eclipse.rcp dep to .dataflow.ui.test/pom.xml to silence Event Admin build log clutters

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/PluginXmlTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/plugin.xml
Fixes #1650.
The reason is basically like in #482: the Java perspective uses Package Explorer, and the instance of a selected project in Package Explorer is `IJavaProject`, not `IProject`. Of course, `IJavaProject` can be adapted to `IProject`.
=> Show GCP preference page from Package Explorer too

plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacetTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/FacetUtil.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidatorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlSourceValidatorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidator.java
Relax the `web.xml` version validation from checking just `version="2.5"` to instead verify that it is compatible with the App Engine standard facet.  Required for Java 8 support (#1057).
=> Check web.xml version support against App Engine facet

plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/messages.properties
Use appengine-plugins-core's `ServiceNameValidator` which unfortunately doesn't provide a helpful message to describe the validation error.  Any suggestions to shorten the service-name description message?
Works around #1830
=> Validate service name field in AppEngineWizardPage

plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml
Fix `.runtime.standard` module types.  Extracted from https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/java8
=> Fix supported module types for .standard.runtime definition

plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowDependencyManagerTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/DataflowDependencyManager.java
Use same pattern as is present in `hasTrackedDataflowDependency()`.
Fixes #1799
=> Avoid NPE in DataflowDependencyManager#hasPinnedDataflowDependency()

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegateTest.java
=> Switch LocalAppEngineServerLaunchConfigurationDelegateTest to use double-quotes for Windows

plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/build.properties, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/src-test/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineXsltTransformTest.java, pom.xml
- ensure XSL templates are being packaged into the bundle
- rename test classes so are picked up by surefire
- specify maven-compiler-plugin source levels
- remove test source from main source
=> Hook in Java 8 support for the build

plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/messages.properties
@chanseokoh fix #1906, maybe.
I'm not sure this is the right approach. Other options include:
1. Add a separate Project name field.
2. add a "-2", "-3" suffix to the eclipse project name if the artifact doubles up. 
I'm not sure it shoudl be impossible to create two eclipse projects in a workspace that have the same Maven artifact ID. They might have different group Ids, for example.
=> check for duplicate project

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesPanelTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/AppYamlPathValidatorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/AppEngineDeployPreferencesPanel.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesPanel.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/AppYamlPathValidator.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/FixedMultiValidator.java
I believe this is a better and maybe proper way to validate the `app.yaml` path field.
The gist of the change is that you call `bindingContext.addValidationStatusProvider()` instead of `bindingContext.bindValue()` to supply a validator in the deploy dialog code. That way, I don't have to force setting the `app.yaml` path field awkwardly. (`bindValue()` addded validators through `UpdateStrategy`, which doesn't allow updating values if there are validation errors.)
Other changes are cascading changes mostly in tests, and luckily, simplify test code. (For example, no need to mock account selection and project selection to suppress any possible validation errors on them, because now I can pinpoint an `app.yaml` validation error status.)
=> Proper way to validate app.yaml path in flex deploy dialog

plugins/com.google.cloud.tools.eclipse.appengine.validation.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/ValidationTestUtils.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/WebXmlValidatorPluginTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlValidatorTest.java
Fixes #1916.
The cause looks like some JSP-specific builder job is run after the test project is deleted. So, the solution here is to delete `InWebContent.jsp` and `InSrc.jsp` before project deletion.
(Other changes are minor simplification.)
=> Delete JSP files in tearDown() in tests

plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/src/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineWebBuilder.java
@chanseokoh workaround #1941.
This may be temporary. I'm looking for a better fix that doesn't prevent downgrades.
=> don't downgrade maven to 1.7

plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/status/StatusUtilTest.java
#1984. The log will now look
```
!ENTRY com.google.cloud.tools.eclipse.util 4 0 2017-05-24 01:08:57.794
!MESSAGE test message from StatusUtilTest
!STACK 0
!ENTRY com.google.cloud.tools.eclipse.util 4 0 2017-05-24 01:08:57.804
!MESSAGE test message from StatusUtilTest: testing
!STACK 0
```
=> Take care of bogus exceptions that look real

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/RunAppEngineShortcutTest.java
Fixes #1995. I don't really understand #1995; it's a bit mysterious. However, I decided not to waste too much time on it. I'm sure we need some lead time for the SWTBot to work properly in this case, and creating it before setting up an App Engine project will do.
=> Give emptyProjectCreator sufficient lead time

eclipse/oxygen/gcp-eclipse-oxygen.target, eclipse/oxygen/gcp-eclipse-oxygen.tpd, pom.xml
Using Oxygen RC2 (…/releases/oxygen/XXX) as RC3 is being staged as we speak at a transient URL.
But WTP RC3 is at a stable URL.  There are no changes to the Platform from RC2 &rarr; RC3 that I can think of that will affect WTP RC2.
=> Update Oxygen for RC2 (WTP RC3)

gcp-repo/metadata.p2.inf
Our CT4E category doesn't appear in the `gcp-repo` p2 repository when built from Maven.  It does appear in our release builds as we explicitly re-publish artifacts as part of the release.  
This fixes our `metadata.p2.inf` to specify an exact range to pull in the category definition.  It also changes some naming to distinguish between the category IU and the capabilities: 
- Use `$version$` to use the version of the `.product`: no need to change the `.p2.inf` file for releases
- Append `.definition` to the capability name, used to pull in the category IU from the product IU, to avoid confusion with the actual category IU.  This capability is required as Tycho's [`assemble-repository` plugin only traverses the _modules_ actually defined in this …
=> Fix gcp-repo/metadata.p2.inf so that category is published in normal Maven builds

plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFlexFacetTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/FlexFacetInstallDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml
Fixes #2034. As discussed in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2034#issuecomment-307829079, we will make the current flex facet require WTP.
=> Make the current flex facet require WTP 

plugins/com.google.cloud.tools.eclipse.test.dependencies/build.properties, plugins/com.google.cloud.tools.eclipse.test.dependencies/plugin.xml, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/javaee_5.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/javaee_6.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/javaee_7.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/javaee_web_services_client_1_2.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/javaee_web_services_client_1_3.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/javaee_web_services_client_1_4.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/jsp_2_1.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/jsp_2_2.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/jsp_2_3.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/web-app_2_5.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/web-app_3_0.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/web-app_3_1.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/web-common_3_0.xsd, plugins/com.google.cloud.tools.eclipse.test.dependencies/xsd/web-common_3_1.xsd, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
This fix includes local copies of the JEE XSDs that are used by the Eclipse XML/XSD validation framework.  The local copies are in our `.test.dependencies` bundle, and are not shipped.
My speculation is that we see XML/XSD validation errors like in #1196 because of some kind of race condition in `ProjectUtils#waitForProjects()` and the WTP/XML validation job.  Perhaps a validation job is only registered after the download of an .xsd is complete? If we hit no network delays then the validation complete before `ProjectUtils#waitForProjects()` completes, and then we see a build error.
Feeling hopeful that this …
Fixes #1196
=> Include local copies of required JEE XSDs 

plugins/com.google.cloud.tools.eclipse.projectselector/src/com/google/cloud/tools/eclipse/projectselector/ProjectSelector.java
Verified on Windows.  Note that Table in OS X always uses `FULL_SELECTION`.
Fixes #2089
=> Use FULL_SELECTION in Project Selector table

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializer.java
And update Google Cloud Core and Storage library definitions from 1.0.0 to 1.2.1.
Note that `google-api-services-storage` is *downgraded* to `v1-rev100-1.22.0` so as 
to correspond to the definition in [`google-cloud-storage` 1.2.1's `pom.xml`](https://repo1.maven.org/maven2/com/google/cloud/google-cloud-storage/1.2.1/google-cloud-storage-1.2.1.pom).
Fixes #2095 
Fixes #2097
=> Implement LibraryClasspathContainerInitializer#getComparisonID()

plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/MajorVersionPipelineRunnerConfigurationTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/PipelineRunner.java, plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/options/JavaProjectPipelineOptionsHierarchy.java, plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/options/PipelineOptionsNamespaces.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
Some fixes for the Dataflow plugins from some quick testing (#2108).
Added some `Preconditions` tests to keep Eclipse nullness checking happy.
Fixes #2108
=> Avoid nullness warnings and NPEs in Dataflow

plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/util/SelectFirstMatchingPrefixListenerTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/util/SelectFirstMatchingPrefixListener.java
Fixes #2119. Fixes #2117.
At the same time, refactored `butcketNameOk()` so that it just returns validation results and let callers update UI.
=> Clear bucket validation error message after validation success / remove unnecessary code

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
Change `LocalAppEngineServerLaunchConfigurationDelegate` to:
- set _automatic-restart=true_ when launching in run mode, and _false_ in debug mode
- only set _max-modules=1_ when launching in debug mode (only relevant for devappserver2; devappserver1 only has a single module)
Makes devappserver 1 or 2 selectable by setting `com.google.cloud.tools.eclipse.appengine.devappserver` property to `1` (default) or `2`.
Requires https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/435
Fixes #1428 
Fixes #2111
=> Set auto-restart based on launch mode, and max-modules=1  in debug mode

plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java
`Combo.removeAll()` removes all combo list items + any text typed into the field. Javadoc:
```
* Removes all of the items from the receiver's list and clear the
* contents of receiver's text field.
```
Therefore, the previous code had to restore the typed text and any text selection. However, we can use `Combo.remove(start, end)` just to remove the combo list items. Javadoc:
```
* Removes the items from the receiver's list which are
* between the given zero-relative start and end
* indices (inclusive).
...
* @exception IllegalArgumentException <ul>
*    <li>ERROR_INVALID_RANGE - if either the start or end are not between 0 and the number of elements in the list minus 1 (inclusive)</li>
```
=> Simplify code that empties Combo items

.travis-toolchains.xml, .travis.yml
- Oracle JDK 7 is no longer present (EOL'd)
- Explicitly specify maximum heap size for Maven build to insulate from machine configuration changes
- previous builds on Travis `precise` report using up to 512m of memory
=> Fix build for Travis 'trusty'

plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/project/GcsDataflowProjectClientTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/project/GcsDataflowProjectClient.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponentTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java
Fixes #2141. Now the staging location will accept GCS paths containing objects, since it will validate only the bucket name part of a path.
Miscs:
- I renamed to _Create_ button that creates a GCS bucket to _Create Bucket_, because otherwise, it can mislead to think it will also create an object. For example, if the input field is `gs://my-bucket/my-object`, it will create the bucket `my-bucket` only. Fortunately, as long as a bucket exists, the Dataflow SDK will create any necessary sub-folder (an object, actually), so there is no need for us to also create an `my-object`.
- `toGcsBucketName()`, which was designed to return only the bucket name part, now removes any trailing forward slashes, as otherwise it will return an empty bucket name.
=> Allow setting GCS paths with object in Dataflow run options

eclipse/ide-target-platform/category.xml, plugins/com.google.cloud.tools.eclipse.test.dependencies/META-INF/MANIFEST.MF
I can check that this does pull in the said bundle, but is this the best?
Another option would be to remove it from the `MANIFEST.MF` in `.test.dependencies`, because no one seems to use it for now. But for completeness, it may be a good idea to leave it there whether it's used or not.
```
Require-Bundle: org.junit;bundle-version="[4.12.0,4.12.1)";visibility:=reexport,
org.hamcrest.core;bundle-version="[1.3.0,1.3.1)";visibility:=reexport,
org.hamcrest.integration;bundle-version="[1.3.0,1.3.1)";visibility:=reexport,
org.hamcrest.library;bundle-version="[1.3.0,1.3.1)";visibility:=reexport
```
=> Add hamcrest.core and .library to category.xml / remove hamcrest.integration from .test.dependencies

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LocalAppEngineConsole.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProjectTest.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTreeUtilities.java
- Change `CloudSdkDebugTarget` to remove the associated console when the ILaunch is removed (following pattern defined in Java and Eclipse launches).  An ILaunch may only be removed much later after a server has transitioned to a STOPPED state.
- Cause the consoles to stop updating themselves once the server transitions to a STOPPED state as a new console is allocated on restart.
Fixes #2212
=> Remove devappserver consoles when corresponding ILaunch is removed

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/LocalAppEngineConsole.java
From #2147 for #2140 marked our `LocalAppEngineConsole` instances as type of `javaStackTraceConsole`.  But other code assume this console can be cast as a `JavaStackTraceConsole` and the CCE is logged and reported through the Eclipse AERI mechanism.
Fixes #2220
=> Back out marking LocalAppEngineConsole as type="javaStackTraceConsole" to avoid CCEs

plugins/com.google.cloud.tools.eclipse.dataflow.core.test/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/ClasspathPipelineOptionsHierarchyFactoryTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/ClasspathPipelineOptionsHierarchyFactory.java, plugins/com.google.cloud.tools.eclipse.dataflow.core/src/com/google/cloud/tools/eclipse/dataflow/core/launcher/options/JavaProjectPipelineOptionsHierarchy.java
Fixes #2223. Apparently, if a project is not set or is not accessible, we currently return `global()` as below. So, if a project isn't a Dataflow project (no `PipelineOptions` type exists), it is safe to return `global()`.
```java
if (project != null && project.isAccessible()) {
...
return pipelineOptionsHierarchyFactory.forProject(project, majorVersion, monitor);
...
}
return pipelineOptionsHierarchyFactory.global(monitor);
```
=> Return empty hierarchy if not Dataflow project

gcp-repo/metadata.product
p2 and Tycho's p2 publishers normally generate unique versions for categories.  Those categories are used by the p2 UIs (e.g., _Install New Software_).   Should we introduce composite repositories at some point (e.g., to reference latest builds), and we drop this _.qualifier_, then we could have a situation with multiple products and categories with the same ID and versions.  So it's best for us to continue using `.qualifier` in product versions for *non-release* builds.
Since we'll have a single release build, the qualifier-less version will be unique (e.g., `1.3.0`) and all will be well.
=> Add note about metadata.product version .qualifier

plugins/com.google.cloud.tools.eclipse.swtbot/.project
I had wondered why I'd see maven errors to do with not being able to resolve `com.google.cloud.tools.eclipse.swtbot`
=> Add maven nature to com.google.cloud.tools.eclipse.swtbot

plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java
=> Ensure WEB-INF directory exists before creating appengine-web.xml

plugins/com.google.cloud.tools.eclipse.test.dependencies/META-INF/MANIFEST.MF
Restores the inclusion of the schema bundles from #2092.
Fixes #1196 (again)
=> Restore the inclusion of schema bundles for .test.dependencies

plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlValidatorTest.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/ThreadDumpingWatchdog.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
Towards fixing #2076.
Wait for `ConvertJob`, fixes #2087
=> Repeatedly wait for problem markers in testValidate_badXml()

features/com.google.cloud.tools.eclipse.suite.e45.feature/p2.inf
Fixes #2255. I did a manual testing by first installing CT4E and then the old Dataflow plugin. It correctly shows a conflict:
=> Specify conflict with old Dataflow plugin

plugins/com.google.cloud.tools.eclipse.util/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/Templates.java
`template/appengine/` is where the freemarker template files (`.ftl`) and one `favicon.ico` reside. I don't think it needs to be in a classpath, as we always provide `template/appengine/` as a base package path:
```java
Configuration configuration = new Configuration(Configuration.VERSION_2_3_25);
configuration.setClassForTemplateLoading(Templates.class, "/templates/appengine");
```
```java
InputStream inputStream = Templates.class
.getResourceAsStream("/templates/appengine/" + sourceName);
```
FYI, the Javadoc of `setClassForTemplateLoading()` is [here](http://freemarker.org/docs/api/freemarker/template/Configuration.html#setClassForTemplateLoading-java.lang.Class-java.lang.String-).
=> Remove unnecessary Bundle-ClassPath in MANIFEST.MF

pom.xml
Workaround repository corruption seen in #2284
=> Disable Maven Aether from resuming file downloads in tests

plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTabTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
Execute pipeline computation using the modal context (`IRunnableWithContext` obtained from the `ILaunchConfigurationDialog`): this launches the computation on a background thread, but spins the UI thread (with a progress bar, if it takes longer than some threshold).  The actual pipeline options form updating is handled done with a busy-indicator.
Fixes #2289
=> Handle pipeline options computation as UI-blocking work

plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponentTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/DefaultedPipelineOptionsComponent.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/DialogPageMessageTarget.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/MessageTarget.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardDefaultRunOptionsPage.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/DefaultRunOptionsPage.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java
Fixes up the `RunOptionsDefaultComponent` and friends to check and handle validation, particularly situations where an "empty" run-options is ok.
- use the _fetch staging locations_ job result to validate the specified project
- `RunOptionsDefaultComponent` explicitly tracks whether its fields should be enabled or not
- `RunOptionsDefaultComponent` explicitly allows an _empty_ configuration to be considered as valid (e.g., for specifying default values like the project default run-options, or the system default run-options)
- _Preferences > Google Cloud Platform > Google Dataflow_ page enablement is based on validity of values shown; an empty configuration is ok
- _Restore Defaults_ clears values, which is valid
- the project dataflow property page's enablement is based on validity of …
=> Ensure run-options validity is propagated

kokoro/windows/continuous.bat
It's useful to see the commands actually executed.
=> Cause build commands to appear in Kokoro log

plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlValidatorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XsltSourceQuickFixTest.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
Applies same approach in #2260, to work around issues seen in #2076.
=> Repeatedly wait for markers in XsltSourceQuickFixTest#testApply()

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/WebFragmentWarPublishTest.java
Log when `WFWPT#setUp()` is called, to see if it's being called twice.  Towards understanding #2284.
=> Check if WebFragmentWarPublishTest#setUp() is being launched twice?

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
An workaround for #2327.  A more comprehensive fix is necessary for #2327 and #2140.
=> Configure debug consoles to use current activate-on-stderr/stdout

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/messages.properties, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java
Deleted / closed projects may still be referenced in server definitions, and selecting the modules may trigger calls into our server delegate to see if they can be removed.  This patch adds some guards to `LocalAppEngineServerDelegate` to check for whether the given module exists.
Fixes #2344
=> Avoid NPEs when dealing with deleted projects

plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/MissingComponentPage.java, plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/messages.properties
Fixes #2349. `generateLayout()` fills in a reasonable layout data for child controls that don't have a data.
=> Fix height issue of App Engine wizard error pages

features/com.google.cloud.tools.eclipse.suite.e45.feature/feature.xml, features/com.google.cloud.tools.eclipse.suite.e45.feature/pom.xml, gcp-repo/metadata.product
=> Version 1.3.1

plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponentTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardDefaultRunOptionsPage.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java
- introduce new `partial` argument on `RunOptionsDefaultsComponent` constructors: if `true` then the component should be able to be partially filled, and be complete providing the field values are valid
- rearrange the ordering of checks in `RunOptionsDefaultsComponent#validate()` as the _fetch staging locations for project P_ serves as a proxy for project validity
- adds new tests to verify that partial support is handled; required properly mocking project validation checks; switched to Mockito's _doXXX.when(obj).yyy()_ syntax as some mocks were classes and wouldn't handle mock-overrides properly
With this patch, I can create new dataflow projects without specifying some or all of the run-options defaults.
=> Make RunOptionsDefaultsComponent able to be partially filled

plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/src/com/google/cloud/tools/eclipse/appengine/deploy/flex/FlexStagingDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/PluginXmlTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/DeployPropertyPageForFlexProjectTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesPanelTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPropertyPage.java, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFacetPresetsTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFlexJarFacetTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFlexWarFacetTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/FlexFacetInstallDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.properties, plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFlexJarFacet.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFlexWarFacet.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/FlexFacetInstallDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/FlexFacetUninstallDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProject.java
Fixes #2104.
_I decided to fork a feature branch while developing flex JAR support. This PR is to be merged to the branch `gae-flex-jar-feature`. I will regularly sync the branch with `master`, which I think will be a trivial task most of the time._
This PR introduces a new App Engine flex JAR facet. Consequently, the current flex facet will be renamed to a WAR facet.
@patflynn and @etanshaul said a few times that there will be a benefit when not having separate facets for the particular use-case where a Spring Boot user changes the packaging option in `pom.xml` from `jar` to `war` (which doesn't do any change to source but makes Spring Boot magically produce a WAR artifact from a plain old Java application). However, as of now, our current facet (WAR) in CT4E is directly coupled with …
=> Add App Engine flex JAR facet

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/build.properties, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/PluginXmlTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployCommandHandlerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployCommandHandler.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployCommandHandler.java
Fixes #2105.
_Merging to the feature branch `gae-flex-jar-feature`_. After the merge, the feature branch becomes complete and can be merged to `master` to enable deploying Maven JAR projects.
- The (existing) flex deploy context menu is enabled if it has the flex JAR facet and has the Maven nature (in addition to current enabled state for the flex WAR project).
- The command handler determines if a project is a WAR or JAR Maven project and uses an appropriate deploy artifact stager.
Again, this will complete the (initial) implementation of deploying a flex JAR Maven project.
=> Add and wire up deploy context menu for Flex JAR Maven projects

plugins/com.google.cloud.tools.eclipse.projectselector.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.projectselector.test/src/com/google/cloud/tools/eclipse/projectselector/MiniSelectorTest.java
Spin the display event loop until a project has been selected.  The selection-change event could be called multiple times.
=> Fix flakey MiniProjectSelector tests

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/AppYamlValidatorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/DeployArtifactValidatorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/RelativeFileFieldSetterTest.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesPanel.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/AppYamlValidator.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/DeployArtifactValidator.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/internal/RelativeFileFieldSetter.java, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/messages.properties
To be used in a global flex deploy dialog (non-existing yet).
Misc: I also took this as an opportunity to refactor `RelativeFileFieldSetter`, so that I can reuse it later in the global deploy dialog.
=> Add WAR/JAR file input field validator

plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/DefaultedPipelineOptionsComponentTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardDefaultRunOptionsPageTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/DefaultedPipelineOptionsComponent.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardDefaultRunOptionsPage.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java, plugins/com.google.cloud.tools.eclipse.projectselector.test/src/com/google/cloud/tools/eclipse/projectselector/MiniSelectorTest.java, plugins/com.google.cloud.tools.eclipse.projectselector/src/com/google/cloud/tools/eclipse/projectselector/MiniSelector.java
Fixes #2410
Add `getProjectId()` helpers that return an `"" ` if no project is selected.  I don't much like this, but it keeps consistency with the helpers to return selected emails and staging locations.
Create tests for `DefaultedPipelineOptionsComponent` and fixed up class behaviour to be more consistent.
=> Fix NPEs and IAEs when creating new Dataflow launch configuration

plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/.project, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/.project
`.libraries.ui` and `.libraries.ui.test` say they're actually called `.libraries` and `.libraries.test`, which conflicts with the actual `.libraries` and `.libraries.test`.
=> Fix project names in .project files to match corresponding projects

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/AppEngineLibrariesSelectorGroupTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProvider.java, plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.standard.ftl
@briandealwis @chanseokoh This will be necessary since the Maven graph doesn't include the SDK as a dependency (nor should it). This is probably how we should have fixed #2350 in the first place.
=> Move SDK into runtime

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProjectTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/CreateAppEngineStandardWtpProjectTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineWtpProject.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProject.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardProjectWizard.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/CreateAppEngineStandardWtpProject.java, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/plugin.xml, plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.flex.ftl, plugins/com.google.cloud.tools.eclipse.util/templates/appengine/pom.xml.standard.ftl
An alternative implementation for #2455 and #2456:
- AES native (Java 7 + 8): downloads and installs `jstl:jstl:1.2` into the `src/main/webapp/WEB-INF/lib`; removes `jstl` from the servlet container (where it didn't belong)
- AES maven (Java 7 + 8): sets up the `pom.xml` to `jstl:jstl:1.2` plus with appropriate `jsp-api` references
- AEF native: downloads and installs `jstl:jstl:1.2` into `lib/` as was happening previously with `servlet-api` and `jsp-api`
- this doesn't feel quite right, but we're not creating a proper WTP server runtime for flex
- AEF maven: adds `jstl:jstl:1.2` to the `pom.xml`
=> Ensure JSP and JSTL are added to new standard and flex projects

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFileTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryFile.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ArtifactRetrieverIntegrationTest.java, plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/ArtifactRetrieverTest.java, plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/ArtifactRetriever.java
This fixes the 0.8.0 problem but I don't think that it addresses #2481. I suspect that bug comes about in `Pom.addDependencies`. The mistake there is looping through all the library files in the library.
These used to be only the files declared in plugin.xml, but can now include files added transitively later. That one needs a little more thought.
=> 0.x.0 versions aren't released

gcloud-eclipse-tools.launch, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/DefaultRunOptionsPage.java
Default project ID should saved as empty string when there is no project selected.
Fixes #2429
=> Avoid NPE in DefaultRunOptionsPage#updatePreferencesFromInputs()

plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/pom.xml
=> .deploy.test needs to include org.eclipse.jdt to detect VMs on macOS

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPathTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPage.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/BuildPath.java
Currently, `listNativeLibrary()` and `computeEntres()` return either
- a singleton list/array of the master container; or
- an empty list/array.
So, to reduce confusion, I'm making them return just the master container (no list/array) or null.
Also we don't make use of the return value of `addNativeLibrary()` (except tests), so I made it `void`.
=> Refactor BuildPath methods

plugins/com.google.cloud.tools.eclipse.appengine.compat.cte13/build.properties
BTW, we should remove `.appengine` from the bundle name.
=> Include plugin.xml in .cte13 bundle

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ImportNativeAppEngineStandardProjectTest.java
#2509 fixed the integration tests with legacy library containers by migrating the containers, but [we still need the wait for the migration to complete]( https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2509/files#r145276541).
=> Fix integration tests

release/release_after_kokoro.sh
I noticed that some of our previous CT4E releases had duplicate bundles (with different timestamps), because we uploaded to the same destination (version directory) as we do multiple cuts during QA. Fortunately, bundles with old timestamps didn't seem to cause any trouble until now. Anyway, it's safe to clean the destination before uploading new binaries.
I've tested this a few times manually.
=> Clean folder before uploading release binaries

plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenCoordinatesUiTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenCoordinatesWizardUiTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenCoordinatesUi.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenCoordinatesWizardUi.java
Separating out the "Create as Maven Project" checkbox and the surrounding UI group from `MavenCoordinatesUi` into a new class `MavenCoordinatesWizardUi`.
This is in preparation for #2470, where we will only support creating a Maven project.
There is no visual or functional change. I verified that the wizards work fine, as they should.
=> Refactor Maven coordinates UI

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviourTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ServletClasspathProvider.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/messages.properties, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProject.java
Fixes #2531.
Puts (copies) appengine-api-1.0-sdk JAR into locally published users' apps, just before starting dev_appserver1.
- Doesn't put the JAR if apps already have one in `WEB-INF/lib`.
- We can keep the current `pom.xml` template and the non-export setting of the JAR.
=> Inject appengine-api-1.0-sdk JAR to local apps

plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineWtpProjectTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProjectTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/CreateAppEngineStandardWtpProjectTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineWtpProject.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/CreateAppEngineFlexWtpProject.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/CreateAppEngineStandardWtpProject.java
Fixes #2535.
Both flex and standard (regardless of Java 7 or Java 8) add JSTL 1.2, so I decided to push down it to the base class.
I suggest to review from bottom to top of the screen — easy to see which code got moved around.
Let's see if tests will pass.
=> Do not put WEB-INF/lib/jstl-1.2.jar for Maven projects

plugins/com.google.cloud.tools.eclipse.ui/pom.xml
This got missed in #2556. Running `mvn` on the command line fails. (I noticed Maven 3.5.0 works without this, and that's why Travis has been working.)
=> Fix pom.xml

plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/flexible/FlexDeployPreferencesPanel.java, plugins/com.google.cloud.tools.eclipse.ui.test/src/com/google/cloud/tools/eclipse/ui/util/event/FileFieldSetterTest.java, plugins/com.google.cloud.tools.eclipse.ui.test/src/com/google/cloud/tools/eclipse/ui/util/event/RelativeFileFieldSetterTest.java, plugins/com.google.cloud.tools.eclipse.ui/src/com/google/cloud/tools/eclipse/ui/util/event/FileFieldSetter.java, plugins/com.google.cloud.tools.eclipse.ui/src/com/google/cloud/tools/eclipse/ui/util/event/RelativeFileFieldSetter.java
- Moved `RelativeFileFieldSetter` to the UI util bundle.
- Created the basic `FileFieldSetter` (extracted from `RelativeFileFieldSetter`). Will be used in the near future.
- Made `RelativeFileFieldSetter` extend `FileFieldSetter`.
=> Add basic FileFieldSetter

plugins/com.google.cloud.tools.eclipse.projectselector.test/src/com/google/cloud/tools/eclipse/projectselector/ProjectRepositoryTest.java, plugins/com.google.cloud.tools.eclipse.projectselector/src/com/google/cloud/tools/eclipse/projectselector/ProjectRepository.java
fix #2578 
@chanseokoh Bump maximum number of projects to 700
Do we want to loop with the refresh token to make multiple requests instead?
=> bump request size to 700 and paginate

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppEngineTabGroupTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/AppEngineTabGroup.java
This wires up the tab. Since the tab defines the env variables, things work as soon as this is wired. I tested the credential env var with a simple Google Translate app locally, and it does work. Couldn't the project ID env var though, as I am not immediately aware of a way to test it.
=> Enable GcpLocalRunTab

plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/src/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineDescriptorTransform.java, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/src/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineStandardFacetChangeListener.java, plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/TemplatesTest.java, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/appEngineWebXmlWithRuntime.txt
@briandealwis fix #2572
A possible fix: this PR now simply removes all automatic downgrades to the java7 runtime. 
The proposal is that if there's a `<runtime>java8</runtime>` in appengine-web.xml, then we leave it alone. The user can manually edit that file to remove it if they really want the legacy runtime.
However we allow people to deploy Java 7 and Servlet 2.5 apps to the Java 8 runtime.
=> Default to java8 runtime

plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/preferences/RunOptionsDefaultsComponent.java
Follow-on from #2599 as these fields aren't used by tests.
=> Hide job fields in RunOptionsDefaultsComponent

plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/ClientApisLibrariesSelectorGroupTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/SwtBotAppEngineActions.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTreeUtilities.java
About #2569. Trying to see what's going on if this fails.
This should log below if all goes right.
```
TreeItem with text {General}: expanded? true
TreeItem with text {Archive File}
TreeItem with text {Existing Projects into Workspace}
TreeItem with text {File System}
TreeItem with text {Preferences}
```
=> Add diagnostic message on project import failure in integration test

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ServiceAccountUtilTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/GcpLocalRunTabTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ServiceAccountUtil.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/GcpLocalRunTab.java, plugins/com.google.cloud.tools.eclipse.projectselector.test/src/com/google/cloud/tools/eclipse/projectselector/ProjectSelectorTest.java, plugins/com.google.cloud.tools.eclipse.projectselector/src/com/google/cloud/tools/eclipse/projectselector/ProjectSelector.java
fix #2604 
@chanseokoh This gets us from a 400 to a 404 for prefixed projects. Not clear why it still doesn't work. Maybe we need a slightly different format for the keyId:
```
String keyId = "projects/" + projectId + "/serviceAccounts/" + serviceAccountId;
```
I'm afraid I had to do a lot of renaming in the tests to wrap my head around the setup. 
```
Nov 27, 2017 6:49:57 PM com.google.cloud.tools.eclipse.appengine.localserver.ui.GcpLocalRunTab createServiceAccountKey
SEVERE: 404 Not Found
{
"code" : 404,
"errors" : [ {
"domain" : "global",
"message" : "Service account projects/google.com:gcloud-for-eclipse-testing/serviceAccounts/gcloud-for-eclipse-testing@appspot.gserviceaccount.com does not exist.",
"reason" : "notFound"
} ],
"message" : "Service account …
```
=> support prefixed project IDs

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/BaseProjectTest.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotWorkbenchActions.java
Two changes for testing purposes to fix #2602.
`BaseProjectTest#tearDown()` resets the workbench, which calls our [`closeAllShells()`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/v1.4.1A/plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotWorkbenchActions.java#L202) to close all `Shell`s providing that they are neither the active workbench window nor the special internal _limbo_ shell (#1362).  But it's possible that closing a shell may trigger other actions such as closing another shell. So we may see SWT exceptions when accessing a now-disposed shell.
The delete-project cleanup in `BaseProjectTest#tearDown()` also seems to produce an error message. So this takes a screen shot (for #501).
=> Log and screencap timeouts on project-deletion, and avoid disposed shells

release/release_after_kokoro.sh
We clean up the GCS bucket first before uploading binaries to make sure old binaries from previous builds get cleaned up first. However, when doing a build for the first time, the folder doesn't exist, and `gsutil rm` fails with a non-zero exit code.
=> Do not fail if "gsutil rm" fails when the destination folder does not exist

eclipse/ide-target-platform/category.xml, features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml, pom.xml
I've not specified the bundle version (i.e., 0.0.0), as I thought we don't need to pin a certain version. Not sure if it'd be better to pin down.
=> Pull org.apache.commons.compress bundle in

gcp-repo/metadata.p2.inf
Bashed the version number to 0.0.0, and changed the category IDs to indicate that we created them.  Which shouldn't matter since they're only ever shown in the IU property dialogs.
=> Provide category descriptions, shown in the Available Software dialog

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/M2RepositoryServiceTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ServiceAccountUtilTest.java
Some tests were missing `fail()`.
I expect builds to pass.
=> Add missing fail() to tests

plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/LoginServiceUi.java
During testing, I noticed if the opt-in dialog could pop up more than once, showing the dialog on the shell from `cancelPressed()` would prevent closing the login progress dialog.
That said, this issue doesn't happen in practice because the opt-in dialog never appears twice, but fixing this is the right thing anyway.
=> Show opt-in dialog after wait dialog closes

plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/messages.properties, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/messages.properties
These 5 identifiers are never referenced.
```
$ git grep update.hierarchy
plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/messages.properties:update.hierarchy=Update Hierarchy
$
$ git grep web.facet.incompatible.title
plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/messages.properties:web.facet.incompatible.title=Incompatible Dynamic Web Module Facet version
$
$ git grep web.facet.incompatible.message
plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/messages.properties:web.facet.incompatible.message=Cannot convert project "{0}": installed Dynamic Web Module facet \
$
$ git grep java.facet.incompatible.title …
```
=> Remove unused messages

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/GcpLocalRunTabTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/ui/GcpLocalRunTab.java
Fixes #2636.
I thought `Paths.get(url.toURI())` did not work as desired, but there was a different reason it was not working.
I believe `Platform.getConfigurationLocation().getURL().toURI()` will never throw an exception unless Eclipse is buggy.
=> Convert URL to Path in a robust way

.travis.yml
Set `SWT_GTK3=0` to cause tests to run against GTK2.
Mitigates #2602.
=> Test Mars using GTK2

plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTabTest.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java
Updating the pipeline options form triggers modify events for each text field changed; each modify event triggers an `updateLaunchConfigurationDialog()`.  With this patch, selecting the DataflowPipelineRunner went from 48 calls to PipelineArgumentsTab#isValid() to 4.
Fixes #2654
=> Suppress updating launch configuration dialog during Pipeline Options updates

eclipse/ide-target-platform/category.xml, eclipse/mars/gcp-eclipse-mars.target, eclipse/mars/gcp-eclipse-mars.tpd, eclipse/neon/gcp-eclipse-neon.target, eclipse/neon/gcp-eclipse-neon.tpd, eclipse/oxygen/gcp-eclipse-oxygen.target, eclipse/oxygen/gcp-eclipse-oxygen.tpd
- Use Orbit's latest release repo to get fixes/patches (recommended practice, even with older releases)
- Use WTP release train repositories (e.g., `/webtools/repository/oxygen`) rather than specific versions; we're using the main Eclipse release train repositories (e.g., `/releases/oxygen`).
- Drop org.eclipse.datatools since it's not used: I included it as it was referenced in GPE
- Use consistent ordering of repositories
=> Tweak target descriptors

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEnginePublishOperationTest.java
One of the failures in #1798 is `ServerUtil.getModule(project)` returning null. (I saw this today too.) This PR is to log the module state at that point to understand which part is failing.
In a normal case, it logs below:
```
[Watchdog] > testPublishingSubmodules(com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEnginePublishOperationTest)
Importing 2 projects:
/usr/local/google/home/chanseok/junit-workspace/sox-server/.project
/usr/local/google/home/chanseok/junit-workspace/sox-shared/.project
* ModuleFactory[org.eclipse.jst.j2ee.server] (not enabled, skipping)
- All factory modules: sox-shared
* ModuleFactory[org.eclipse.jst.jee.server]
- All factory modules: sox-server
- Project modules: sox-server
* ModuleFactory[org.eclipse.wst.web.internal.deployables.static]
- …
```
=> Log diagnostic messages for ServerUtil.getModule() failure

plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
For one of the failures in #1798 (about the "The project cannot be built until build path errors are resolved" error).
Any errors from the projects of #1798 should eventually disappear. Note that `waitForProjects()` doesn't always wait until that happens. For example, if it thinks build errors are not changing, it can give up waiting.
So, I want to wait until there is genuinely no error, with a timeout of 5 minutes. This has two advantages:
1. If `waitForProjects()` somehow slipped an error which can disappear eventually, this will fix the flaky test failure.
1. Otherwise if it times out after 5 minutes, it will mostly likely tell us that the lingering error marker is basically bogus and not going away for more than 5 minutes for some unknown reason.
=> Wait until no error found

.travis.yml, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java, plugins/com.google.cloud.tools.eclipse.googleapis/pom.xml, plugins/com.google.cloud.tools.eclipse.projectselector.test/src/com/google/cloud/tools/eclipse/projectselector/model/GcpProjectTest.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTreeUtilities.java, plugins/com.google.cloud.tools.eclipse.test.dependencies/pom.xml, pom.xml
This PR adds a new profile `errorprone` that invokes the ErrorProne compiler, and fixes some errors identified by ErrorProne.  It changes the Travis build to use this `errorprone` profile.
We can't replace Tycho's use of ECJ as the `tycho-compiler-plugin` is specifically brought in as part of the `eclipse-plugin` packaging, and doesn't offer an option to skip compilation.  Although this double-compilation (ecj + errorprone/javac) increases the compilation time, the additional compilation time is dwarfed by testing time.
I had to rework `com.google.cloud.tools.eclipse.googleapis` and `.test.dependencies` slightly to bring in their dependent libraries using Maven's `<dependencies>` to keep the Travis build happy.  I had tried this approach for #2390 but we were getting a substantial number …
=> Build with ErrorProne on Travis

kokoro/windows/continuous.bat
So, I've tar'ed up an M2 repo (`$HOME/.m2`) containing almost all artifacts and bundles used in Kokoro Oxygen builds. Its size is about 690MB. I uploaded it to a GCS bucket.
I tested downloading the tar and unpacking on Kokoro, and surprisingly, the whole process takes only a few seconds. No more artifact/bundle downloading (for now), so this saves a lot of time.
=> Download and unpack M2 repo cache for Kokoro builds

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, plugins/com.google.cloud.tools.eclipse.bugreport.test/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandlerTest.java, plugins/com.google.cloud.tools.eclipse.bugreport/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandler.java
=> Try gcloud before reporting a bug

kokoro/ubuntu/continuous.sh, kokoro/windows/continuous.bat
Fix #2704 by ensuring builds on Kokoro use Java 8.  Kokoro's JDK/JRE installations are in `C:\Program Files\Java`:
```
T:\src\github\google-cloud-eclipse>dir "C:\Program Files\Java" 
Volume in drive C has no label.
Volume Serial Number is 22E5-2A46
Directory of C:\Program Files\Java
01/04/2018  12:43 PM    <DIR>          .
01/04/2018  12:43 PM    <DIR>          ..
01/04/2018  12:33 PM    <DIR>          jdk-9.0.1
03/30/2015  05:11 PM    <DIR>          jdk1.7.0_75
04/25/2017  01:22 PM    <DIR>          jdk1.8.0_131
07/28/2017  08:56 AM    <DIR>          jdk1.8.0_144
01/04/2018  12:38 PM    <DIR>          jdk1.8.0_152
01/04/2018  12:33 PM    <DIR>          jre-9.0.1
07/28/2017  08:56 AM    <DIR>          jre1.8.0_144
01/04/2018  12:38 PM    <DIR>          jre1.8.0_152
0 File(s) …
```
=> Fix Kokoro builds to use Java 8

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ImportNativeAppEngineStandardProjectTest.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
Fixes #2714.
There was another bug that I did not pass any project to `getAllBuildErrors()`.
=> Wait until no build error

plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/META-INF/MANIFEST.MF
Adds `com.google.cloud.tools.eclipse.appengine.localserver` as a bundle dependency to several of our test projects to ensure the App Engine Standard Runtime runtime and server definitions are found. This change avoids the spurious _ java.lang.NullPointerException: Could not find App Engine Standard runtime type_ errors in the build logs.
Fixes #2715
=> Add .appengine.localserver dependency to prevent spurious NPEs

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
Tests failing:
```
testEndpointsLibraryConfig(com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest)  Time elapsed: 0.007 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "2.0.10"
but: was "2.0.11"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest.testEndpointsLibraryConfig(CloudLibrariesInPluginXmlTest.java:117)
```
=> Bump endpoints-framework to 2.0.11

plugins/com.google.cloud.tools.eclipse.appengine.libraries/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/BaseProjectTest.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/TestProjectCreator.java
Hoping this will avoid occasional preference-loading exception bursts triggered by deleting a project.  For example:
```
!ENTRY org.eclipse.core.resources 4 4 2018-01-16 17:42:57.624
!MESSAGE Exception loading preferences from: /appWithPackage_java8/.settings/org.eclipse.jdt.core.prefs.
!STACK 1
org.eclipse.core.runtime.CoreException: File not found: /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.integration.appengine/target/work/data/appWithPackage_java8/.settings/org.eclipse.jdt.core.prefs.
at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:45)
at org.eclipse.core.internal.filesystem.local.LocalFile.openInputStream(LocalFile.java:406)
at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResource …
```
=> Close projects before deleting them

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelperTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/launching/LaunchHelper.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/messages.properties, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProjectTest.java
As discovered in #2728, `synchronousStart` is not actually required for serializing the server publish and start steps.  This reverts the fix in #2728 and removes the `synchronousStart` attribute.
Fixes #2727
=> Mark the App Engine local server for asynchronous start

plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkContextFunctionTest.java, plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/MockSdkGenerator.java
We can handle the Cloud SDK version check with the mock since the introduction of the `VERSION` file.
=> Enable previously ignored Cloud SDK test

plugins/com.google.cloud.tools.eclipse.appengine.facets/.project, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/.project, plugins/com.google.cloud.tools.eclipse.appengine.newproject/.project, plugins/com.google.cloud.tools.eclipse.appengine.ui.test/.project, plugins/com.google.cloud.tools.eclipse.appengine.ui/.project, plugins/com.google.cloud.tools.eclipse.dataflow.core.test/.project, plugins/com.google.cloud.tools.eclipse.dataflow.ui.test/.project, plugins/com.google.cloud.tools.eclipse.dataflow.ui/.project, plugins/com.google.cloud.tools.eclipse.integration.appengine/.project, plugins/com.google.cloud.tools.eclipse.preferences.test/.project, plugins/com.google.cloud.tools.eclipse.preferences/.project, plugins/com.google.cloud.tools.eclipse.sdk.test/.project, plugins/com.google.cloud.tools.eclipse.sdk.ui/.project, plugins/com.google.cloud.tools.eclipse.sdk/.classpath, plugins/com.google.cloud.tools.eclipse.sdk/.project, plugins/com.google.cloud.tools.eclipse.test.util/.classpath
m2eclipse wants its builder to appear last.  Also remove vestiges of Checkstyle plugin.
=> Adopt m2eclipse ordering for .project and .classpath files

.travis.yml, pom.xml
Instead of configuring Travis to set `SWT_GTK3=0` on Mars, configure _tycho-surefire_ on Maven to set `SWT_GTK3=0` when running Mars.  This should make `mvn verify` more robust for Linux and Mars.
=> Configure tycho-surefire to set SWT_GTK3=0 for Mars

plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/util/CloudSdkProcessWrapper.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java, plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/MessageConsoleWriterListenerTest.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/MessageConsoleWriterListener.java
Extending the existing listener for the managed Cloud SDK output. We'll redirect install output to the (deploy and local run) console too.
=> Extend MessageConsoleWriter listener

README.md
=> Apply and Finish

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java
`appengine-plugins-core`'s `CloudSdkDevAppServer1#stop()` raises an `AppEngineException` if the `/_ah/admin/quit` request returns a non-2XX result.  In such a case, we forcibly terminate the devappserver process.
Fixes #1964 
Fixes #2771
Filed https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/530 to move this up
=> Forcibly terminate server on error from quit-request

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/PomTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/LibraryTest.java
silence some warnings for #2716 
I'm debating how generic we should make this.
=> turn off some expected logging messages in tests

.travis.yml
Uh, wow: 2 minutes to fetch from Orbit, and 2 minutes to fail fetching from docker-editor.openanalytics.eu
```
25726 [INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/latest-R
26240 [INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops2/R20170307180635/repository/
26244 [INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops2/R20170307180635/repository/
148246 [INFO] Adding repository http://docker-editor.openanalytics.eu/update
269492 [WARNING] Failed to access p2 repository http://docker-editor.openanalytics.eu/update, use local cache. Communication with repository at http://docker-editor.openanalytics.eu/update failed.
269689 [INFO] Adding repository http://dadacoalition.org/yedit
281378 [INFO] …
```
=> Annotate Maven build log with elapsed time

plugins/com.google.cloud.tools.eclipse.sdk.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceAreaTest.java, plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java, plugins/com.google.cloud.tools.eclipse.test.util/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/MockSdkGenerator.java
Fixes #2821. Updates the version label whenever preferences are loaded.
Misc.:
- Moved `MockSdkGenerator` to the `.test.util` bundle.
- Renamed variables.
=> Fix Cloud SDK version display

plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkPreferencesTest.java, plugins/com.google.cloud.tools.eclipse.sdk/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkPreferences.java
Fixes #2839.
I noticed `IPreferencesStore` does not have `flush()`, maybe because it is a general abstraction of the preference notion? I think the only way to persist is to actually get the preference node.
=> Persist one-time managed Cloud SDK preferences setup

plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/DeployJob.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java, plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/CloudSdkManagerTest.java, plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceAreaTest.java, plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/InstallManagedCloudSdkStartup.java, plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/UpdateManagedCloudSdkHandler.java, plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/CloudSdkManager.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkPreferences.java
Required making `CloudSdkManager` mockable.
Fixes #2808
=> Trigger installation of the Managed Cloud SDK on selection

plugins/com.google.cloud.tools.eclipse.ui.status/src/com/google/cloud/tools/eclipse/ui/status/ShowGcpStatusHandler.java
Previously clicking on the status button opens new browser tabs.
=> Use a browser-ID to reuse GCP status browser tab

eclipse/ide-target-platform/category.xml, eclipse/neon/gcp-eclipse-neon.target, eclipse/neon/gcp-eclipse-neon.tpd, eclipse/oxygen/gcp-eclipse-oxygen.target, eclipse/oxygen/gcp-eclipse-oxygen.tpd
We pull in the `org.eclipse.license` feature, a vestige from GPE.  But since CT4E is under the ASL, it's unnecessary.
Note: this patch builds on #2860 since it requires regenerating the .target files.
=> Remove Eclipse Public License feature

plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/LibrarySelectorGroup.java
=> Fix spacing in LibrarySelectorGroup

plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/XmlSourceValidator.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/XmlValidator.java
Fixes #2874 
I stripped out the helper-creating exception catching & logging code as the implementations don't handle a case where there is a `null` validation helper.
=> Use IConfigurationElement.createExecutableExtension() to create instances

plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacetTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/src/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineJre8StandardFacetVersionTest.java, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/src/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineStandardFacetVersionChangeTest.java, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/src/com/google/cloud/tools/eclipse/appengine/standard/java8/AppEngineStandardFacetVersionChangeTests.java, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8/plugin.xml
- adds a facet version property `appengine.runtime` to the AES JRE8 facet version to ensure the `<runtime>` value
- use the `appengine.runtime` property to set the `<runtime>` value as required
- rename `AppEngineStandardFacetVersionChangeTests` to ensure they are run by Tycho surefire tests
- fix up tests to reflect the current reality from #2591 
Fixes #2868
=> Make AESv8-related tests work in Eclipse

eclipse/neon/gcp-eclipse-neon.target, eclipse/oxygen/gcp-eclipse-oxygen.target
Orbit updated the pointer on `latest-R` to point to the latest release.
=> Regenerate .target files

plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/CloudSdkManagerTest.java, plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkInstallJobTest.java, plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkModifyJobTest.java, plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/ShowConsoleViewActionTest.java, plugins/com.google.cloud.tools.eclipse.sdk/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/CloudSdkManager.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkInstallJob.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkModifyJob.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/ShowConsoleViewAction.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/messages.properties
Fixes #2838.
Currently, we see the detailed SDK install/update output only when deploying, for which we have a deploy console. For the background install/update jobs, only shown are the brief monitor task names.
This PR creates a new message console for those jobs. The console is created when the job is instantiated. There will be only one console which will be reused across multiple (sequential) install/update jobs.
When users open the job progress view, they will see task names as hyperlinks:
When clicking on the link, it will bring the console to the front.
=> Create and show SDK install/update console for background jobs

features/com.google.cloud.tools.eclipse.suite.feature/p2.inf, features/com.google.cloud.tools.eclipse.suite.feature/pom.xml, gcp-repo/pom.xml, pom.xml
I get inconsistent results with #2893 where the p2 update metadata wasn't always being picked up.  It turns out I had a missing `range()` in the p2ql expression, and fixing that now ensures the metadata is always generated.  I realized that I can can use ant to test that the metadata was generated.
Fixes #2890
=> Fix .e45 feature p2-metadata generation and add tests

plugins/com.google.cloud.tools.eclipse.appengine.newproject/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.ui/plugin.properties, plugins/com.google.cloud.tools.eclipse.appengine.ui/plugin.xml, plugins/com.google.cloud.tools.eclipse.dataflow.ui/plugin.xml, plugins/com.google.cloud.tools.eclipse.ui.test/src/com/google/cloud/tools/eclipse/ui/PluginXmlTest.java, plugins/com.google.cloud.tools.eclipse.ui/plugin.properties, plugins/com.google.cloud.tools.eclipse.ui/plugin.xml
- creates new "cloud" keyword
- moves non-appengine keywords into `com.google.cloud.tools.eclipse.ui`
- adds non-appengine keywords to dataflow wizards too
Fix #2905
=> Add "Cloud" and "Google Cloud Platform" keywords, and minor reorg

plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/CloudSdkManagerTest.java, plugins/com.google.cloud.tools.eclipse.sdk.test/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkModifyJobTest.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkInstallJob.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkModifyJob.java, plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkUpdateJob.java
The name will be "Configuring Google Cloud SDK...".
The externalized strings are still used, so they have not been removed from `messages.properties`.
=> Rename Cloud SDK modify job

plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectWizard.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexProjectWizard.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardProjectWizard.java
(This doesn't fix #2906. Just the first refactoring step to fix it.)
I believe the reason we previously provided the wizard page through the abstract method was that we needed to dynamically create different pages, including the Cloud-SDK-not-found and Java-component-missing error pages.
The two wizards work as usual.
=> Provide App Engine project wizard page directly

plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectWizard.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexProjectWizard.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexWizardPage.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardProjectWizard.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardWizardPage.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/page/NewDataflowProjectWizardLandingPage.java, plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/wizard/NewDataflowProjectWizard.java
Fixes #2906.
@briandealwis can you check if all the three wizards (including the Dataflow one) work on Mac? You can merge with `analytics-dialog-test` as before for testing. They work for me on Linux.
=> Show Analytics opt-in dialog on correct shells

eclipse/ide-target-platform/category.xml, eclipse/neon/gcp-eclipse-neon.target, eclipse/neon/gcp-eclipse-neon.tpd, eclipse/oxygen/gcp-eclipse-oxygen.target, eclipse/oxygen/gcp-eclipse-oxygen.tpd, plugins/com.google.cloud.tools.eclipse.test.dependencies/.classpath, plugins/com.google.cloud.tools.eclipse.test.dependencies/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.test.dependencies/build.properties, plugins/com.google.cloud.tools.eclipse.test.dependencies/logback.xml, plugins/com.google.cloud.tools.eclipse.test.dependencies/src/com/google/cloud/tools/eclipse/test/dependencies/LogConfigurator.java, pom.xml
In debugging #2872, a key observation was that activities were happening on different threads.  `java.util.logging` doesn't log the thread name, [nor can it be configured to do so](https://stackoverflow.com/a/6889151/600339).  Whereas logback can output the thread, and [our logback configuration does so](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.test.dependencies/logback.xml#L4).  We already shunt log4j and commons-logging into SLF4j and thence into Logback in our tests.
This fix brings in the [java.util.logging → SLF4j bridge](https://www.slf4j.org/api/org/slf4j/bridge/SLF4JBridgeHandler.html) and causes it to be installed by a new bundle-activator for `com.google.cloud.tools.eclipse.test.dependencies`.
Another …
=> Cause java.util.logging to shunt to slf4j

plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XmlValidatorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/XsltQuickFixTest.java
For #2909.
- Does not always create a DWP. This is the main change. Other changes in the same class are basically refactoring.
- `testValidate_badXml()` is broken down to two: the later part separated out into `testValidate_badXml_dynamicWebProject()`.
=> Do not always create Dynamic Web project

plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java
I believe #1155 affects only Neon: https://bugs.eclipse.org/bugs/show_bug.cgi?id=510377. With this change, creating a new App Engine standard project will be slightly faster on Oyxgen or later.
=> Suspend ConvertJob only on Neon

plugins/com.google.cloud.tools.eclipse.ui.status/src/com/google/cloud/tools/eclipse/ui/status/PollingStatusServiceImpl.java
This change dials down the logging severity level of the retrieved GCP status as INFO is too high.
=> Downgrade GCP Status logging severity

kokoro/ubuntu/new_release.sh
Removing ".qualifier" from the version can be automated too, of course.
=> Automate removing ".qualifier" in release process

release/copy_repo_to_final_location.py, release/copy_repo_to_final_location_test.py
I tried Python this time. I'm completely new to Python.
This is a post-build script, to copy a Kokoro-built repo to a final, permanent GCS location (e.g., `gs://cloud-tools-for-eclipse/1.6.1`).
What it does is actually simple:
1. Asks the GCS URL of a Kokoro-built URL.
1. Asks the CT4E version (for the name of a final GCS location).
1. Halts if the destination directory already exists.
1. Copy the repo.
1. Make the repo publicly accessible.
=> Add script to copy Kokoro-built repo

plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/CreateAppEngineStandardWtpProjectTest.java
@chanseokoh 
Minor fix so that
java.lang.AssertionError: 
Expected: a collection containing has appengine-api-1.0-sdk
becomes 
java.lang.AssertionError: 
Expected: a collection containing appengine-api-1.0-sdk
=> fix test failure message

features/com.google.cloud.tools.eclipse.suite.feature/feature.xml, features/com.google.cloud.tools.eclipse.suite.feature/pom.xml, gcp-repo/metadata.product
It doesn't matter when we merge this, as long as we make a cut after this. (The actual cut we build against is determined at the time of tagging the repo.)
=> Prepare releasing 1.6.1

plugins/com.google.cloud.tools.eclipse.appengine.compat.test/src/com/google/cloud/tools/eclipse/appengine/compat/gpe/GpeClassicMigratorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.compat.test/src/com/google/cloud/tools/eclipse/appengine/compat/gpe/GpeFacetedMigratorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallationTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/WebProjectUtilTest.java, plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEnginePublishOperationTest.java, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/src/com/google/cloud/tools/eclipse/appengine/standard/java8/GpeConversionTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ChildModuleWarPublishTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/FlexMavenPackagedProjectStagingDelegateTest.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
Change `ProjectUtils.importProject()` to return a map of _project-name_ → _project, since we have this information.  Simplifies `LocalAppEnginePublishOperationTest`.
=> Change importProjects to return a map of name -> project

plugins/com.google.cloud.tools.eclipse.ui.status/src/com/google/cloud/tools/eclipse/ui/status/PollingStatusServiceImpl.java, plugins/com.google.cloud.tools.eclipse.ui.status/src/com/google/cloud/tools/eclipse/ui/status/messages.properties
fix #3006 Shows _Cannot connect to Google Cloud Platform_ on connection errors (e.g., UnknownHostException or NoRouteToHostException), and _Failure retrieving GCP status_ on any other IOExceptions (e.g., JSON parsing error or HTTP non-2XX code.
=> Do not show exception toString() in status menu

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEnginePublishOperationTest.java, plugins/com.google.cloud.tools.eclipse.test.util/META-INF/MANIFEST.MF
Fixes #1798.
Based on the observations in #1798, looks like server modules are sometimes never loaded properly for some unknown reason. We can reinitialize them by closing and reopening projects.
=> Reopen projects if modules are not ready

plugins/com.google.cloud.tools.eclipse.ui/src/com/google/cloud/tools/eclipse/ui/util/event/OpenUriSelectionListener.java
Just noticed we've not been making any use of the exception in the URI-open-error dialog.
=> Surface actual exception to users

kokoro/windows/continuous.bat
I made a mistake in #3022 after which Kokoro ignored the Maven build exit.
=> Make Kokoro build exit with Maven build status

gcp-repo/pom.xml, pom.xml
Regarding #3016.
Initially I put the format configuration only in `gcp-repo/pom.xml`, which added the a postfix only to the display (product) version. I plan to add `-post-release-nightly` so that it would look like `1.6.1.201804251802-post-release-nightly`. However, I thought it is actually nice to put such a postfix to the feature version too, which will clearly show us if the installed version is a nightly build, e.g., in the bug reported from our menu. So I added it to the top-level `pom.xml`.
Things work naturally and properly when it comes to upgrading, as the postfix is the last item to compare. In terms of comparing versions, `1.6.1.201804251802-post-release-nightly` comes after `1.6.1.201804251802`, which matches my plan to build `1.6.1.201804251802-post-release-nightly` after …
=> Configurable build version

kokoro/ubuntu/jar_signing.sh, kokoro/ubuntu/new_release.cfg, kokoro/ubuntu/new_release.sh
Fixes the problem that the current signing step reconstructs the p2 metadata, which reverts the timestamp (and the optional suffix) of the product version  (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3016#issuecomment-385432805).
Extra: unpack an M2 repo cache to speed up builds.
=> Mirror p2 metadata from unsigned repo instead of creating new metadata

plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexProjectWizardTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/CreateAppEngineStandardWtpProjectTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/AppEngineProjectWizard.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexProjectWizard.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/AppEngineStandardProjectWizard.java
Fixes #2996
- ensure `CreateAppEngineStandardWtpProjectTest.testAppEngineLibrariesAdded()` runs with the workspace root scheduling rule
- remove seemingly useless dependency-validator as it's hard-coded to check requirements for App Engine Standard for Java 7 apps
=> Secure scheduling rule for CreateAppEngineStandardWtpProjectTest

plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineConfigFileSchemaLocationProviderTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.validation/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineConfigFileSchemaLocationProvider.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/xsd/appengine-web.xsd, plugins/com.google.cloud.tools.eclipse.appengine.validation/xsd/cron.xsd, plugins/com.google.cloud.tools.eclipse.appengine.validation/xsd/datastore-indexes.xsd, plugins/com.google.cloud.tools.eclipse.appengine.validation/xsd/dispatch.xsd, plugins/com.google.cloud.tools.eclipse.appengine.validation/xsd/dos.xsd, plugins/com.google.cloud.tools.eclipse.appengine.validation/xsd/queue.xsd
Adds a WTP XML schema-location provider to associate schemas based on file name patterns.  This is sufficient to bring in validation and auto-complete on the associated elements.
For now, all but the `appengine-web.xsd` are brought in as `noNamespaceSchemaLocation` as they have no formal namespaces.
Fixes #1757, #1758, #1759, #1760, #1761
=> Incorporate XSDs for AES XML configuration files from App Engine SDK

plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/ThreadDumpingWatchdog.java, plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/TestProjectCreator.java
I think this makes it easier to understand how `ThreadDumpingWatchdog` works.
=> ThreadDumpingWatchdog cleanup

plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegateTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallationTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java, plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/TemplatesTest.java, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/appEngineWebXmlWithRuntime.txt, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/appengineWebXml.txt, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/appengineWebXmlWithService.txt, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/loggingProperties.txt, plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/Templates.java, plugins/com.google.cloud.tools.eclipse.util/templates/appengine/appengine-web.xml.ftl, plugins/com.google.cloud.tools.eclipse.util/templates/appengine/logging.properties.ftl
Fixes #3051.
Fixes #2541.
There are two execution paths where we add `appengine-web.xml` and (now) `logging.properties`:
- Through the project wizard.
- When adding the App Engine Standard facet.
With the [sample code here](https://cloud.google.com/appengine/docs/standard/java/how-requests-are-handled#logging), only WARNING and ERROR are logged because `.level = WARNING` in `logging.properties`.
=> Add logging.properties template

plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEnginePublishOperationTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/BaseProjectTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ChildModuleWarPublishTest.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ProjectContextMenuTest.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotProjectActions.java
- use `IWorkspace#delete(IResource[], …)` to delete all related projects to avoid build errors from dependent projects disappearing
- collapse projects shown in _Project Explorer_ to avoid model-refreshes during project deletion
- ensure maven projects are deleted (`project` field should not be shadowed)
Fixes #3104
=> Avoid warnings in integration tests

pom.xml
Tycho 1.2.0 has been released.  It supports JUnit 5 tests and Java 10.  Nothing that affects us, but keeping up to date is good.
=> Tycho 1.2.0

eclipse/ide-target-platform/category.xml, features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml, pom.xml
Fixes #3102
This change is independent of https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/647 as `appengine-plugins-core` imports the `org.snakeyaml` packages with broad ranges of `[1.17,2)`.
=> Update SnakeYAML to 1.21

plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/CloudSdkStagingHelper.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/ui/navigator/model/AppEngineWebDescriptor.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java, plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineRuntime.java, plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/TemplatesTest.java, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/helloAppEngineJava8.txt, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/helloAppEngineWithPackage.txt, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/helloAppEngineWithoutPackage.txt, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/objectifyWebFilterWithPackage.txt, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/objectifyWebFilterWithoutPackage.txt, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/web25ObjectifyFilter.txt, plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/Templates.java, plugins/com.google.cloud.tools.eclipse.util/templates/appengine/HelloAppEngine.java.ftl, plugins/com.google.cloud.tools.eclipse.util/templates/appengine/ObjectifyWebFilter.java.ftl, plugins/com.google.cloud.tools.eclipse.util/templates/appengine/web.xml.ftl
Fixes #3076
The filter is needed for both Objectify 5 and 6. The filter covers all incoming URLs (`/*`).
- Standard Java 7: `<filter> and <filter-mapping>` in `web.xml`
- Standard Java 8 and Flexible: new `ObjectifyWebFilter` class with the `@WebFilter` annotation (no change in `web.xml`)
=> Add Objectify filter when creating new projects

README.md, eclipse/common-dependencies.tpd, eclipse/neon/gcp-eclipse-neon.target, eclipse/neon/gcp-eclipse-neon.tpd, eclipse/oxygen/gcp-eclipse-oxygen.target, eclipse/oxygen/gcp-eclipse-oxygen.tpd, eclipse/photon/gcp-eclipse-photon.target, eclipse/photon/gcp-eclipse-photon.tpd, eclipse/pom.xml, pom.xml
- pulls out common dependencies into `eclipse/common-dependencies.tpd`
- uses latest SWTBot to ensure consistency across all supported platforms
=> Update to Photon RC3

plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
@briandealwis I remember the original code was basically what you suggested. Now it looks to me it's better to flip the order to prefer an active window and use the workbench window as a last resort. At least this takes care of one case I just encountered where some dialog was open and the opt-in dialog is unresponsive. WDYT?
=> Prefer active window for opt-in dialog

plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/io/ResourceUtilsTest.java, plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/io/ResourceUtils.java
Noticed a lot of traces like the following in the logs.  Oops, `IResourceChangeEvent#getDelta()` may return a `null` delta.
```
!ENTRY org.eclipse.core.resources 4 2 2018-06-12 19:54:05.956
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException
at com.google.cloud.tools.eclipse.util.io.ResourceUtils.getAffectedFiles(ResourceUtils.java:61)
at com.google.cloud.tools.eclipse.appengine.facets.ui.navigator.AppEngineContentProvider.resourceChanged(AppEngineContentProvider.java:122)
at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:297)
```
=> IResourceChangeEvent#getDelta() may return null

plugins/com.google.cloud.tools.eclipse.sdk.ui.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.sdk.ui.test/pom.xml, plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/CloudSdkInstallNotificationTest.java, plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/CloudSdkUpdateNotificationTest.java, plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/ManagedCloudSdkStartupTest.java, plugins/com.google.cloud.tools.eclipse.sdk.ui.test/src/com/google/cloud/tools/eclipse/sdk/ui/MessagesTest.java, plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/CloudSdkInstallNotification.java, plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/ManagedCloudSdkStartup.java, plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/messages.properties
Notifies the user before installing the Cloud SDK.  Installation proceeds after the notification is closed (either fade away or explicitly dismissed). Adds some tests for both installation and updating.  Feedback on wording is welcome!
Fixes #3140
=> Notify user prior to installing Managed Cloud SDK

plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/status/StatusUtilTest.java
Every variable name was blindly and confusingly `error`. Likewise, it was always `test error message`.
Besides that, no behavioral change.
=> Update misleading variable names and string constants

plugins/com.google.cloud.tools.eclipse.sdk.ui.test/pom.xml
Our build logs for `.sdk.ui.tests` are filled with errors like the following:
```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2018-06-20 15:00:06.250
!MESSAGE Event Admin service is not available, unable to publish event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/renderer/requestEnablementUpdate] {org.eclipse.e4.data=ALL}.
!ENTRY org.eclipse.e4.ui.workbench 4 0 2018-06-20 15:00:06.341
!MESSAGE Event Admin service is not available, unable to publish event org.osgi.service.event.Event [topic=org/eclipse/e4/ui/model/basic/PartDescriptorContainer/descriptors/ADD] {ChangedElement=org.eclipse.e4.ui.model.application.impl.ApplicationImpl@22bb5646 (elementId: org.eclipse.e4.legacy.ide.application, tags: [activeSchemeId:org.eclipse.ui.defaultAcceleratorConfiguration, …
```
=> com.google.cloud.tools.eclipse.sdk.ui tests require the workbench

plugins/com.google.cloud.tools.eclipse.ui/src/com/google/cloud/tools/eclipse/ui/util/OpenDropDownMenuHandler.java
Rename `xxx.png` to avoid compiler warning as `xxx` is interpreted as a todo marker.
```
128413 [INFO] --- tycho-compiler-plugin:1.1.0:compile (default-compile) @ com.google.cloud.tools.eclipse.ui ---
128417 [INFO] Compiling 16 source files to /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.ui/target/classes
[…]
128938 [WARNING] /home/travis/build/GoogleCloudPlatform/google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.ui/src/com/google/cloud/tools/eclipse/ui/util/OpenDropDownMenuHandler.java:[52] 
*                icon=&quot;xxx.png&quot; /&gt;
^^^^^^^^^^^^^^^^^^^
XXX.png&quot; /&gt;
```
=> Rename image placeholder to avoid compiler warning

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/ProjectExplorerAppEngineBlockTest.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTreeUtilities.java
I had `ProjectExplorerAppEngineBlockTest` fail locally as the _Deployment Descriptor_ block appeared at a different location in the Project Explorer.  This PR adds a new utility method to wait and return a tree node that matches a given matcher.
=> Add SwtBotTreeUtilities#getMatchingNode() to select matching node

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPageTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/FlexibleLibrariesSelectorGroupTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/CloudLibrariesPage.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui/src/com/google/cloud/tools/eclipse/appengine/libraries/ui/messages.properties, plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibraries.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexWizardPage.java
Objectify 6 can be added to any non-App Engine standard projects, so I'm renaming the group name. (To be fair, I believe Objectify 6 can be used on App Engine standard if >= Java 8, but we are sticking to Objectify 5 for some technical reason.) In that light, it's really hard to give correct names to the field and the UI title. What do you think?
I'll add tests in the meantime.
=> Add library group for extra libraries to non-App Engine standard projects

plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplatesTest.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CodeTemplates.java, plugins/com.google.cloud.tools.eclipse.appengine.ui/src/com/google/cloud/tools/eclipse/appengine/ui/AppEngineRuntime.java, plugins/com.google.cloud.tools.eclipse.util.test/src/com/google/cloud/tools/eclipse/util/TemplatesTest.java, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/objectifyWebListenerWithPackage.txt, plugins/com.google.cloud.tools.eclipse.util.test/testData/templates/appengine/objectifyWebListenerWithoutPackage.txt, plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/Templates.java, plugins/com.google.cloud.tools.eclipse.util/templates/appengine/ObjectifyWebListener.java.ftl
Fixes #3211.
Objectify 6 requires calling `ObjectifyService.init()`, and a Servlet context listener is recommended for a call site: https://github.com/objectify/objectify/wiki/Setup#initialize-the-objectifyservice-required-for-v6
The listener is added only when adding Objectify 6.
=> Add WebListener to call ObjectifyService.init() for Objectify 6 when creating flex projects

plugins/com.google.cloud.tools.eclipse.welcome.test/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.welcome.test/src/com/google/cloud/tools/eclipse/welcome/ContentXmlTest.java, plugins/com.google.cloud.tools.eclipse.welcome/intro/cloud-tools-for-eclipse.xml
The Eclipse Intro/Welcome support for highlighting new content requires that those new content extensions have IDs.  This PR adds unique IDs for each of our extensions, with tests.
=> Ensure intro/welcome content extensions have IDs and names

.github/ISSUE_TEMPLATE.md, plugins/com.google.cloud.tools.eclipse.bugreport.test/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandlerTest.java, plugins/com.google.cloud.tools.eclipse.bugreport/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandler.java
Produces easier-to-read issue submissions.
=> Use HTML comments to hide the helper text in our issue templates

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java
The devappserver launch would issue a warning that the launch's _Program Arguments_ are ignored, but [they are now passed](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java#L323) with #2184.
=> Remove incorrect warning

plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/FacetUtil.java, plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/CreateAppEngineWtpProject.java
Closes #3201: With #3233 we can remove the workarounds for [the WTP DependencyGraph bug](https://bugs.eclipse.org/511793), which was fixed for Oxygen.
This patch also removes some [unused methods and fields in `StandardFacetInstallDelegate`](
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/3234#discussion_r212501279) leftover from removing `ConvertJobSuspender` (#3200).
=> Remove WTP DependencyGraph workarounds

kokoro/ubuntu/jar_signing.sh, kokoro/ubuntu/new_release.sh
Using the new cache (built a while ago by [these instructions](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/wiki/Building-and-Running-Tests-in-Docker)) for release too.
=> Update .m2 cache TAR name

plugins/com.google.cloud.tools.eclipse.bugreport.test/src/com/google/cloud/tools/eclipse/bugreport/ui/BugReportCommandHandlerTest.java
Fix build failures due to release of [JDK 11.0.1](http://jdk.java.net/11/).
=> Fix for Java 11.0.1

kokoro/ubuntu/new_release.sh
https://issuetracker.google.com/119096137 is making `gcloud components update` fail. Following the workaround suggested in the issue tracker.
=> Fix gcloud update issue in Kokoro

gcloud-eclipse-tools.launch
The key in the launch config was a temporary one while developing the managed SDK feature.
=> Remove obsolete tracing option

kokoro/ubuntu/new_release.sh
```
+ gcloud components remove container-builder-local
ERROR: (gcloud.components.remove) The following components are not currently installed [container-builder-local]
[ID: 9163144] Build finished after 9 secs, exit value: 1
```
=> Fix Kokoro build by removing gcloud workaround

README.md
Related: #3308
I've realized there is no mention of `xvfb-run`.
=> Add `xvfb-run` tip for running tests

plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidationTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation.test/src/com/google/cloud/tools/eclipse/appengine/validation/AppEngineWebXmlValidatorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.validation/xsd/appengine-web.xsd
Fixes #3351.
XSD from Cloud SDK 228.0.0. `min-instances` will now allow 0.
=> Update appengine-web.xsd from Cloud SDK 228.0.0

eclipse/eclipse-2018-09/gcp-eclipse-2018-09.target, eclipse/eclipse-2018-09/gcp-eclipse-2018-09.tpd, eclipse/eclipse-2018-12/gcp-eclipse-2018-12.target, eclipse/eclipse-2018-12/gcp-eclipse-2018-12.tpd, eclipse/ide-target-platform/category.xml, eclipse/oxygen/gcp-eclipse-oxygen.target, eclipse/oxygen/gcp-eclipse-oxygen.tpd, eclipse/photon/gcp-eclipse-photon.target, eclipse/photon/gcp-eclipse-photon.tpd
We've been experiencing some real slow-downs when launching Eclipse with our target platforms.  From applying the techniques in [Eclipse bug 516664]( https://bugs.eclipse.org/bugs/show_bug.cgi?id=516664#c10), I discovered that the culprit is that we have Lucene 7.1 and 7.5 bundles in our target platforms, and as a result the Equinox resolver spends lots of time resolving the right package chains.
The Lucene bundles are pulled in from two different paths:
- the `org.eclipse.help` feature,  required by the `org.eclipse.sdk` feature, pulls in `org.apache.lucene.*` bundles with version 7.1.0
- the `org.eclipse.datatools.sqltools.result` bundle, part of JPT, requires the `org.apache.lucene.queryparser` bundle, which was only created for 7.5.0
Since we're not actually providing any JPT/JPA …
=> Drop Eclipse JPT from target platforms to speed launches

README.md
`-Pide-target-platform` is required to actually assemble the target platform.
=> Add -Pide-target-platform to build target platform

plugins/com.google.cloud.tools.eclipse.util/templates/appengine/MockHttpServletResponse.java.ftl
@chanseokoh also avoids warnings about `@Override`
fixes #3415
=> Generate servlet 3 methods only in servlet 3.1 apps

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/plugin.xml
[Objectify 6 requires Java 8](https://github.com/objectify/objectify/blob/master/pom.xml#L86) so also add `javaVersion="1.8"` to the library definition.
=> Update for Objectify 6.0.4

plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/project/ProjectUtils.java
The stacktraces for the odd `ArrayIndexOutOfBoundsException`s (#3277), which occur on project close and delete, seem to stem from the WTP `DependencyGraph` jobs that were causing us problems previously.  This PR causes our `ProjectUtils#waitForProjects()` to wait for these jobs too.  I've run the tests a couple of times and haven't seen a flake.
=> Wait on WTP's DependencyGraph update jobs to avoid AIOOBE on project tear-down

plugins/com.google.cloud.tools.eclipse.appengine.compat/src/com/google/cloud/tools/eclipse/appengine/compat/cte13/CloudToolsEclipseProjectUpdater.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializerTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerResolverJobTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerInitializer.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/LibraryClasspathContainerResolverJob.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/persistence/LibraryClasspathContainerSerializer.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/LibraryClasspathContainerResolverService.java, plugins/com.google.cloud.tools.eclipse.appengine.newproject.test/src/com/google/cloud/tools/eclipse/appengine/newproject/standard/CreateAppEngineStandardWtpProjectTest.java
Cause `LibraryClasspathContainerInitializer` to delegate library resolving to a background job.  This turns `LibraryClasspathContainerInitializer#initialize` into a much more light-weight operation.  
This change in high-level terms:
- `LibraryClasspathContainerInitializer` no longer downloads and resolves artifacts in the requesting thread.  If the container is not properly resolved, it kicks off a `LibraryClasspathContainerResolverJob` via its `requestClasspathContainerUpdate()` method.  This job resolves required dependencies and then updates the classpath container on the project, which triggers an update of the project.
- so `LibraryClasspathContainerResolverService#resolveAll()` should never be called from `LibraryClasspathContainerInitializer`, and hence the …
=> Perform GCP library resolving in background job

.travisci/toolchains.xml, README.md, third_party/com.google.cloud.tools.eclipse.jst.server.core/META-INF/MANIFEST.MF
fixes #3483 @briandealwis 
FYI I couldn't even compile on my new laptop because it didn't have Java 7, and there's no easy way to install this.
=> remove Java 7 toolchain

plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java, plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProjectTest.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTreeUtilities.java, pom.xml
Fixes #3482
`LocalAppEngineServerLaunchConfigurationDelegate#setupDebugTarget()` changes the `RunConfiguration` to add JVM command options to enable JDWP.  But with `RunConfiguration` becoming immutable, these changes were not propagated back to the caller `launch()`.
This patch changes `LocalAppEngineServerLaunchConfigurationDelegate#setupDebugTarget()` to return the updated `RunConfiguration`, which is picked up by `launch()`.  It also adds a check to `DebugNativeAppEngineStandardProjectTest` to check that the _main_ thread is found: no threading information will be available unless the debugger was able to connect to the remote JVM via JDWP.
=> Ensure JVM flags are propagated in LocalAppEngineServerLaunchConfigurationDelegate

eclipse/ide-target-platform/category.xml, features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml, pom.xml
Update our 3rd-party feature with commons-compress' changed OSGi symbolic name.  Fortunately the package names haven't changed and so `appengine-plugins-core`/`com.google.cloud.tools.appengine` is unaffected.
Filed [COMPRESS-498](https://issues.apache.org/jira/browse/COMPRESS-498) about the name change, which seems to have been a mistake.
=> Update to commons-compress' changed BSN

features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml
No need to add to `eclipse/ide-target-repository/category.xml` as `failureaccess` is already being resolved by p2 when creating the `ide-target-repository`.
=> Add com.google.guava.failureaccess to 3rdparty feature

plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/AccountsPanelTest.java, plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/AccountsPanel.java, plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/LabelImageLoader.java
Fixes #3570.
For the image
https://lh3.googleusercontent.com/a-/AAuE7mBeBrCk1V_scMJv6_OOR68BaWs2OZ9OTE0byc94
we should request the size in the new URL format by appending `=s[size]`, e.g.,
https://lh3.googleusercontent.com/a-/AAuE7mBeBrCk1V_scMJv6_OOR68BaWs2OZ9OTE0byc94=s45
Clicking on the latter URL returns a small image.
=> Fix user profile picture URL

.travis.yml, .travisci/toolchains.xml, pom.xml
This PR changes the Travis build from using the Trusty distribution (now EOL) to the Xenial distribution (Ubuntu 16.04 LTS) to pick up more up-to-date JREs.  The hope is that these later JREs may have fixes for the occasional hangs that our Eclipse 2018-09 on Java 8 builds are suffering.  There are a few changes:
- Uses the new `xvfb` service to launch xvfb automagically.
- The `oraclejdk8` is not available in Xenial, so we use `openjdk8` instead.
- It also switches to using Tycho 1.5.0, in case the hangs are caused in p2.
=> Change Travis build to Xenial

plugins/com.google.cloud.tools.eclipse.integration.appengine/src/com/google/cloud/tools/eclipse/integration/appengine/DebugNativeAppEngineStandardProjectTest.java, plugins/com.google.cloud.tools.eclipse.swtbot/src/com/google/cloud/tools/eclipse/swtbot/SwtBotTestingUtilities.java
Since we changed our default from Photon to 2018-09, the integration test on the Kokoro Ubuntu nightly release builds have been failing. (OTOH, Kokoro Windows builds and local builds are OK.)
For whatever reason, the shell with the title "data - testapp_java8/src/main/java/app/engine/test/HelloAppEngine.java - Eclipse Platform" does no get deactivated when the "Debug On Server" window is open. I just tried a different approach to access the "Debug On Server" window.
Building with this branch worked.
Fixes #3596.
=> Fix Kokoro nightly release builds

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
The test fails probably because we have Objectify 6.0.6 published like yesterday.
```
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.609 s <<< FAILURE! - in com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest
testObjectifyLibraryConfig(com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest)  Time elapsed: 0.472 s  <<< FAILURE!
java.lang.AssertionError: expected:<6.0.5> but was:<6.0.6>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at com.google.cloud.tools.eclipse.appengine.libraries.model.CloudLibrariesInPluginXmlTest.testObjectifyLibraryConfig(CloudLibrariesInP …
```
=> Update Objectify version in CloudLibrariesInPluginXmlTest

kokoro/ubuntu/release.sh, plugins/com.google.cloud.tools.eclipse.usagetracker.test/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManagerPluginTest.java, plugins/com.google.cloud.tools.eclipse.usagetracker/.classpath, plugins/com.google.cloud.tools.eclipse.usagetracker/build.properties, plugins/com.google.cloud.tools.eclipse.usagetracker/java-templates/com/google/cloud/tools/eclipse/usagetracker/Constants.java, plugins/com.google.cloud.tools.eclipse.usagetracker/pom.xml, plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java
JSON changes:
- Stop wrapping non-primitive types as a singleton list. This redundant wrapping didn't make sense at all, but Clearcut weirdness required it.
- `log_source_name` --> `log_source`
- ~~`source_extension_json` --> `source_extension_json_proto3` (doesn't seem necessary but following the latest sample)~~
- `client_machine_id` --> `client_install_id` (this has been broken even with Clearcut)
Also restoring source generation for `Constants.java`. See https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/3537/files to verify the reverted changes.
The local test server logs that the JSON is parsed correctly.
```
Request: "POST /v1/firelog/legacy/log?key=... HTTP/1.1"
[...] {
client_info {
client_type: DESKTOP
}
timestamp_millis: 1581013495216
client_timestamp_millis: …
```
=> Migrate Clearcut client-side usage metrics

plugins/com.google.cloud.tools.eclipse.test.dependencies/.project, plugins/com.google.cloud.tools.eclipse.test.dependencies/META-INF/MANIFEST.MF, plugins/com.google.cloud.tools.eclipse.test.dependencies/OSGI-INF/logservice.xml, plugins/com.google.cloud.tools.eclipse.test.dependencies/build.properties, plugins/com.google.cloud.tools.eclipse.test.dependencies/src/com/google/cloud/tools/eclipse/test/dependencies/EclipseLoggingAdapter.java, plugins/com.google.cloud.tools.eclipse.test.dependencies/src/com/google/cloud/tools/eclipse/test/dependencies/LoggerDelegate.java, pom.xml
Our .test.dependencies bundle is set up to redirect java.util.logging to SLF4j/Logback.  This PR redirects Eclipse's logger too, in the hopes that more compact logging will allow #3528 (which introduces the 2019-09 and now 2019-12 platforms) to succeed.
The Eclipse logger implements the `org.eclipse.equinox.ExtendedLogService` interface, which itself extends `org.osgi.service.log.LogService`.  OSGi has since included a new SLF4j-like LoggerFactory/Logger setup.
=> Redirect Eclipse logs during tests to SLF4j/Logback

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/MavenHelperTest.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/model/MavenCoordinates.java, plugins/com.google.cloud.tools.eclipse.appengine.libraries/src/com/google/cloud/tools/eclipse/appengine/libraries/repository/MavenHelper.java, plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/MavenUtils.java
=> Check Android repository too

plugins/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/model/CloudLibrariesInPluginXmlTest.java
6.0.7 is released [yesterday](https://search.maven.org/artifact/com.googlecode.objectify/objectify) and causing a build failure.
=> Fix Objectify library version test

plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/AccountsPanelTest.java, plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/AccountsPanel.java
Fixes #3636 
Strip off any image sizing directives from the avatar URL.  Assumes that the avatar long-codes don't normally include an `=`.
---
I'm not sure why but the account info is returning an empty name; it was working earlier on a different machine.  The login confirmation page doesn't show any information requests for name or email:
I don't know if this is different from before though.
=> Handle avatar URLs with existing resize directives

kokoro/ubuntu/release.sh
Cloud SDK requires Python 3.5+.
=> Fix kokoro build failures

kokoro/ubuntu/release.sh
The original installed Cloud SDK needs Python 2.  After being updated, it needs Python 3.
=> Set CLOUDSDK_PYTHON only after performing the Cloud SDK update

plugins/com.google.cloud.tools.eclipse.appengine.compat.test/src/com/google/cloud/tools/eclipse/appengine/compat/gpe/GpeClassicMigratorTest.java, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/src/com/google/cloud/tools/eclipse/appengine/facets/ui/navigator/model/ModelRefreshTests.java, plugins/com.google.cloud.tools.eclipse.appengine.standard.java8.test/src/com/google/cloud/tools/eclipse/appengine/standard/java8/ConversionTests.java
The update to Tycho 2.5.0 revealed a few mistaken assumptions in the tests — at least, they no longer hold, perhaps because of Tycho's switch to  using the Equinox bundle resolver.  Separating these fixes from #3663 to ensure we're not breaking anything currently.
- `GpeClassicMigratorTest`: NPE seen in tearDown if the test failed to create a project
- `ModelRefreshTests`: perhaps due to the bundle resolving, we now see changes to additional files other than the facet definition file in `org.eclipse.wst.common.component`
- `ConversionTests`: assumed a faceted project was created, even though we didn't ask for it. I'm not sure how this wasn't failing previously!
=> test: fix breakages in tests found during update to Tycho 2.5.0

README.md
update readme with info to reflect that Eclipse 4.22 and later are currently not supported. Eclipse latest is currently on 4.24 now and 4.25 will come out soon.
Related issues got filed in #3659, #3660, #3678; attempts to fix in #3661 but no progress since.
Suggest adding this to readme and removing when this issue actually get fixed.
=> update readme with supported Eclipse versions

features/com.google.cloud.tools.eclipse.3rdparty.feature/pom.xml, plugins/com.google.cloud.tools.eclipse.googleapis/pom.xml, pom.xml
- Update to Tycho 2.6.0: we can't update to 2.7.5 due to eclipse-tycho/tycho/issues/1377
- But use an m2eclipse-specific profile to use Tycho 2.7.5 within the IDE as it includes lifecycle-mapping definitions for the tycho plugins and avoids the need for the now-defunct tycho configurator
- Configure the c.g.c.t.e.googleapis `copy-dependencies` to be executed on workspace change, and avoid the need for the maven-dependency-plugin configurator
=> chore: enable building in latest Eclipse

plugins/com.google.cloud.tools.eclipse.appengine.deploy.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.facets.test/pom.xml, plugins/com.google.cloud.tools.eclipse.appengine.libraries.ui.test/pom.xml, plugins/com.google.cloud.tools.eclipse.googleapis.test/pom.xml, plugins/com.google.cloud.tools.eclipse.login.test/pom.xml, plugins/com.google.cloud.tools.eclipse.ui.test/pom.xml
some poms had their `<disablePrivacyTos/>` tag in the wrong plugin configuration - moved them to `tycho-surefire-plugin`.
Suspected cause of 180 min timeout in latest release attempt
=> fix: correct ptos disable configuration in tests

features/com.google.cloud.tools.eclipse.suite.feature/feature.xml, features/com.google.cloud.tools.eclipse.suite.feature/pom.xml, gcp-repo/metadata.product, plugins/com.google.cloud.tools.eclipse.integration.appengine/pom.xml, plugins/com.google.cloud.tools.eclipse.welcome.test/src/com/google/cloud/tools/eclipse/welcome/ContentXmlTest.java, plugins/com.google.cloud.tools.eclipse.welcome/intro/cloud-tools-for-eclipse.xml
P/TOS is already available in a popup when the app starts and in the preferences section.
=> fix: remove unnecesary welcome page links to ptos

plugins/com.google.cloud.tools.eclipse.login.test/src/com/google/cloud/tools/eclipse/login/ui/AccountSelectorTest.java, plugins/com.google.cloud.tools.eclipse.login/src/com/google/cloud/tools/eclipse/login/ui/AccountSelector.java
Fixes missing tests for `com.google.cloud.tools.eclipse.login.ui.AccountSelector`
=> chore: adapt tests of `AccountSelector`

README.md
Installation instructions are not added since there is a message indicating that they are found in cloud.google.com
=> Update README.md with GAE Java 8 deprecation

kokoro/ubuntu/release.sh
fixes release workflow:
```
ERROR: gcloud failed to load. You are running gcloud with Python 3.5, which is no longer supported by gcloud.
Install a compatible version of Python 3.8-3.12 and set the CLOUDSDK_PYTHON environment variable to point to it.
```
=> chore: update python version in release.sh
